---
title: "Russian_War_Ukraine"
output: html_document
dev: cairo
date: '2022-06-07'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_chunk$set(dev='ragg_png')
#knitr::opts_chunk$set(dev = "cairo_pdf") #for PDF ONLY
knitr::opts_chunk$set(dev = "png", dev.args = list(type = "cairo-png"))
#knitr::opts_chunk$set(dev='cairo_pdf')
#getOption("RStudioGD.backend")

library(jsonlite)
library(stringi)
library(lubridate)
library(data.table)
library(ggplot2)
```

## Load Data

```{r load_data}

print(getOption("RStudioGD.backend"))

filename_eq = 'https://raw.githubusercontent.com/PetroIvaniuk/2022-Ukraine-Russia-War-Dataset/main/data/russia_losses_equipment.json'
filename_pn = 'https://raw.githubusercontent.com/PetroIvaniuk/2022-Ukraine-Russia-War-Dataset/main/data/russia_losses_personnel.json'

df_eq <- fromJSON(sapply(readLines(filename_eq,  warn=FALSE), function(x) stri_replace_all_fixed(x, "NaN", '"NA"')))
df_pn <- fromJSON(sapply(readLines(filename_pn,  warn=FALSE), function(x) stri_replace_all_fixed(x, "NaN", '"NA"')))

setDT(df_eq)
setDT(df_pn)

names(df_eq) = make.names( names(df_eq) )

df = df_eq[df_pn, on =.(date)]

df[, date := as.Date(date)]
df[, date_m := as.Date(ISOdate(year(date), month(date), 1)) ]
df[order(date), p_diff := personnel - shift(personnel)]

ggplot(df, aes(date, personnel)) + geom_line()
ggplot(df, aes(date, POW)) + geom_line()
ggplot(df, aes(date, p_diff)) + geom_point() + geom_smooth(se = FALSE, color = 'red', span = 0.3) + 
  scale_x_date(date_breaks = '1 month') + coord_cartesian(ylim = c(0, 1000))

ggplot(df[, .(pd = sum(p_diff, na.rm = TRUE), .N), by =.(date_m)], aes(date_m, pd)) + geom_line()

df_m =  melt(df[, -c("greatest.losses.direction", "day", "date_m", 'personnel*', 'p_diff', 'POW', 'fuel.tank', 'military.auto', 'mobile.SRBM.system', 'day', 'i.day'), ], id.vars = 'date')
df_m[, value := as.numeric(value)]
df_m[order(date),  value_diff := value - shift(value), by = .(variable) ]
ggplot(df_m, aes(date, value)) + geom_line() + facet_wrap(~variable, scales = 'free' )
ggplot(df_m, aes(date, value_diff)) + geom_point() + facet_wrap(~variable, scales = 'free' ) + geom_smooth(se = FALSE, color = 'red', span = 0.1)
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
