---
title: "distance example"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(proxy)
library(ggplot2)
library(data.table)
library(plyr)
library(gridExtra)


working_folder = 'D:/Github/KaggleSandbox'

source(file.path(working_folder, 'Utils/common.R'))
```

## Examples

```{r distance}

df = expand.grid(x = seq(-1, 1, by =0.01), y = seq(-1, 1, by =0.01))
setDT(df)

#Mahalanobis
df[, r:=as.numeric(dist(df[,.(x, y)], matrix(c(0, 0), nrow = 1), method = 'L2'))]

ggplot(df, aes(x, y, fill = r)) + geom_tile() + scale_fill_custom('jet',discrete = FALSE)

#check all distances -----
dist_measures = c('L1', 'L2', 'Chebyshev')
res = ldply(dist_measures, function(my_dist){  
   cbind(df[,.(x, y)], r=as.numeric(dist(df[,.(x, y)], matrix(c(0, 0), nrow = 1), method = my_dist)), method =  my_dist)
 } )
setDT(res)
#summary(pr_DB, verbosity = c("long"))
ggplot(res, aes(x, y, fill = r)) + geom_tile() + scale_fill_custom('jet',discrete = FALSE) + facet_wrap(~method)

#check Minkowski distances -----
plots = llply(c(0.1, 0.5, 1, 2, 4, 100), function(my_p){  
   temp = cbind(df[,.(x, y)], r=as.numeric(dist(df[,.(x, y)], matrix(c(0, 0), nrow = 1), method = 'Minkowski', p = my_p)), p =  my_p)
  
  ggplot(temp, aes(x, y, fill = r)) + geom_tile() + scale_fill_custom('jet',discrete = FALSE) +ggtitle(sprintf('Minkowski:p = %.1f', my_p))

 } )
marrangeGrob(plots, nrow = 2, ncol = 3, top = NULL)

#check F-metric distances -----
plots = llply(c(0.1, 0.5, 1, 2, 4, 100), function(my_p){  
   f_exp = ifelse(my_p<1,my_p, 1.0 )
   temp = cbind(df[,.(x, y)], r=as.numeric(dist(df[,.(x, y)], matrix(c(0, 0), nrow = 1), method = 'Minkowski', p = my_p)^f_exp ), p =  my_p)
   ggplot(temp, aes(x, y, fill = r)) + geom_tile() + scale_fill_custom('jet',discrete = FALSE) +ggtitle(sprintf('Minkowski p = %.1f', my_p))
 } )
marrangeGrob(plots, nrow = 2, ncol = 3, top = NULL)



```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
