---
title: "Structured Noise"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ambient)
library(dplyr)
```

## Perlin Noise

```{r perlin_noise}
image(noise_perlin(dim = c(300, 400), octaves = 5))
```

## Distance map

```{r dist_map, echo=FALSE}
grid <- long_grid(x = seq(0, 1, length.out = 1000),
                  y = seq(0, 1, length.out = 1000))

grid <- grid %>% 
  mutate(
    noise = gen_worley(x, y, frequency = 5, value = 'distance')
  )

grid %>%  plot(noise)
```


```{r dist_map, echo=FALSE}
grid %>%   mutate(    pattern = gen_waves(x, y, frequency = 5)  ) %>%    plot(pattern)

grid %>% 
  mutate(
    pertube = gen_simplex(x, y, frequency = 5) / 10,
    noise = gen_worley(x + pertube, y + pertube, value = 'distance', frequency = 5)
  ) %>% 
  plot(noise)

# Classic perlin noise (combining 4 different frequencies)
grid %>% 
  mutate(
    noise = fracture(gen_perlin, fbm, octaves = 4, x = x, y = y, freq_init = 5)
  ) %>% 
  plot(noise)

grid %>% 
  mutate(
    noise = fracture(gen_perlin, clamped, octaves = 4, x = x, y = y, freq_init = 5)
  ) %>% 
  plot(noise)
```
