---
title: "RBF Forest"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(proxy)
library(MASS)
library(ggplot2)
library(plyr)
library(dplyr)
library(stringi)
library(caret)
library(gridExtra)

working_folder = 'D:/Github/KaggleSandbox'

source(file.path(working_folder, 'Utils/common.R'))
source(file.path(working_folder, 'Utils/rbf_utils.R'))

rms <-function(y1, y2) sqrt( mean( (y1 - y2)^2 ))

```

## Test

```{r test}
x = seq(0, 1, by = 0.01)
y = 0.2 + 0.4 * x * x + 0.3 *x * sin(15 * x) + 0.05 * cos(50 * x)

df = data.table(x, y)

nodes = as.matrix(c(0.25, 0.75))

model.rbf = rbf.create(df[,.(x)], df$y, nodes, kernel_fun = rbf_linear_kernel)
model.rbf = rbf.create(df[,.(x)], df$y, nodes, kernel_fun = rbf_tp_kernel)
model.rbf = rbf.create(df[,.(x)], df$y, nodes, kernel_fun = rbf_cauchy_kernel)
model.rbf = rbf.create(df[,.(x)], df$y, nodes, kernel_fun = rbf_cubic_kernel)
model.rbf = rbf.create(df[,.(x)], df$y, nodes, kernel_fun = rbf_imquad_kernel)
model.rbf = rbf.create(df[,.(x)], df$y, nodes, kernel_fun = rbf_mquad_kernel)
model.rbf = rbf.create(df[,.(x)], df$y, nodes, kernel_fun = rbf_bump_kernel)
model.rbf = rbf.create(df[,.(x)], df$y, nodes, kernel_fun = rbf_acq_kernel)

y_pred = rbf.predict(model.rbf, df[,.(x)])
ggplot(cbind(df, y_pred), aes(x, y)) + geom_point() + geom_line(aes(x, y_pred), color = 'red')

```

## Test ALL

```{r test_ALL}
x = seq(0, 1, by = 0.01)
y = 0.2 + 0.4 * x * x + 0.3 *x * sin(15 * x) + 0.05 * cos(50 * x)

df = data.table(x, y)

nodes = as.matrix(c(0.5))
#nodes = as.matrix(c(0.25, 0.75))
#nodes = as.matrix(seq(0, 1, by =0.1))

rbf_kernels = list('rbf_linear_kernel' = rbf_linear_kernel, 'rbf_cauchy_kernel' = rbf_cauchy_kernel, 
                   'rbf_cubic_kernel' = rbf_cubic_kernel, 'rbf_gauss_kernel' = rbf_gauss_kernel, 
                   'rbf_bump_kernel' = rbf_bump_kernel, 'rbf_mquad_kernel' = rbf_mquad_kernel, 'rbf_imquad_kernel' = rbf_imquad_kernel,
                   'rbf_tp_kernel' = rbf_tp_kernel, 'rbf_iquad_kernel' = rbf_iquad_kernel, 'rbf_acq_kernel' = rbf_acq_kernel,
                   'rbf_p5_kernel' = rbf_p5_kernel, 'rbf_logistic_kernel' = rbf_logistic_kernel, 'rbf_wendland_kernel' = rbf_wendland_kernel)

df_res = ldply(names(rbf_kernels), function(my_kernel) {
  model.rbf = rbf.create(df[,.(x)], df$y, nodes, kernel_fun = function(x) rbf_kernels[[my_kernel]](x) )  
  y_pred = rbf.predict(model.rbf, df[,.(x)])
  return ( cbind(df, y_pred, my_kernel) )
  })

ggplot(df_res, aes(x, y)) + geom_point(alpha = 0.5) + geom_line(aes(x, y_pred), color = 'red', size = 1) + 
  geom_vline(xintercept = c(0.25, 0.75), linetype = 'dashed') + facet_wrap(~my_kernel)

#x = seq(0, 1, by = 0.1)
#plot(x, rbf_logistic_kernel(10*x))
```

## RBF Boot

```{r rbf_boot}
x = seq(0, 1, by = 0.01)
y = 0.2 + 0.4 * x * x + 0.3 *x * sin(15 * x) + 0.05 * cos(50 * x)
df = data.table(x, y)
df[, id:=seq(nrow(df))]

max_nodes = 20

models = rbf_boot.create(df[,.(x)], df$y, max_nodes, n_runs = 100, kernel_fun = rbf_logistic_kernel)
#models = rbf_boot.create(df[,.(x)], df$y, max_nodes, n_runs = 100, kernel_fun = rbf_tp_kernel)
res = rbf_boot.predict(models, df[,.(x)])
setDT(res)
res_agg = res[, .(y_pred = mean(y_pred), sigma = sd(y_pred), .N ), by =.(id)]

res_agg[df, y := i.y, on=.(id) ]
res_agg[df, x := i.x, on=.(id) ]
res[df, x := i.x, on=.(id) ]

#all fits
ggplot(res, aes(x, y_pred, group = run_id)) + geom_line(color = 'blue', alpha = 0.2) 

#average
ggplot(res_agg, aes(x, y)) + geom_point() + geom_line(aes(x, y_pred), color = 'red', size = 1) + 
  geom_ribbon(aes(x, ymin = y_pred - 2*sigma, ymax = y_pred + 2*sigma), alpha = 0.2, fill = 'blue')

#convergence
res[order(run_id),y_pred_cum := cummean(y_pred), by =.(id) ]
ggplot(res, aes(x, y_pred_cum, group = run_id)) + geom_line(color = 'blue', alpha = 0.2) 

it_error = res[order(id), .(error = rms(df$y, y_pred_cum)), by =.(run_id) ] #it_error[error == min(error)]
ggplot(it_error, aes(run_id, error)) + geom_line()

```

## RBF Boot test all

```{r rbf_boot_test}
x = seq(0, 1, by = 0.01)
y = 0.2 + 0.4 * x * x + 0.3 *x * sin(15 * x) + 0.05 * cos(50 * x)
df = data.table(x, y)
df[, id:=seq(nrow(df))]

max_nodes = 25

df_res = ldply(names(rbf_kernels), function(my_kernel) {
  
  models = rbf_boot.create(df[,.(x)], df$y, max_nodes, n_runs = 100, kernel_fun = function(x) rbf_kernels[[my_kernel]](5*x))
  res = rbf_boot.predict(models, df[,.(x)])
  setDT(res)
  res_agg = res[, .(y_pred = mean(y_pred, na.rm = TRUE), sigma = sd(y_pred, na.rm = TRUE), .N ), by =.(id)]

  
  return ( data.frame(id = res_agg$id, y_pred = res_agg$y_pred, sigma = res_agg$sigma, my_kernel) )
  })

setDT(df_res)

df_res[df, x:=i.x, on =.(id)]
df_res[df, y:=i.y, on =.(id)]

#average
ggplot(df_res, aes(x, y)) + geom_point() + geom_line(aes(x, y_pred), color = 'red', size = 1) + 
  geom_ribbon(aes(x, ymin = y_pred - 2*sigma, ymax = y_pred + 2*sigma), alpha = 0.2, fill = 'blue') + facet_wrap(~my_kernel)

```

## RBF Timing
                       Estimate Std. Error t value Pr(>|t|)    
(Intercept)              -2.664e-01  9.741e-02  -2.735   0.0153 *  
I(max_nodes * max_nodes)  9.883e-05  1.038e-05   9.520 9.50e-08 ***
runs                      3.217e-03  4.335e-04   7.423 2.14e-06 ***

```{r rbf_timing}
run_cases = expand.grid(n_nodes = c(10, 20, 30, 40, 50, 100), boot_samples = c(100, 200, 300))

timing_res = ldply(seq(nrow(run_cases)), function(i){
  
 start_time = Sys.time()
 models = rbf_boot.create(df[,.(x)], df$y, n_nodes = run_cases$n_nodes[i], n_runs = run_cases$boot_samples[i], kernel_fun =rbf_linear_kernel)
 
 data.frame(i, elapsed = as.numeric(Sys.time() - start_time), n_nodes = run_cases$n_nodes[i],  runs = run_cases$boot_samples[i])
})

ggplot(timing_res, aes(n_nodes, elapsed)) + geom_line() + facet_wrap(~runs)

summary(lm(elapsed  ~ I(n_nodes * n_nodes) + runs, timing_res))
```

## RBF Boosting

```{r rbf_boosting}

x = seq(0, 1, by = 0.01)
y = 0.2 + 0.4 * x * x + 0.3 *x * sin(15 * x) + 0.05 * cos(50 * x)
df = data.table(x, y)
df[, id:=seq(nrow(df))]

max_nodes = 32

models_boost =  rbf_boost.create(df[,.(x)],  df$y, 1, max_nodes, n_runs = 30,  growth_rate = 2, shrink_kernel = 0.5, kernel_fun = rbf_mquad_kernel)
res = rbf_boost.predict(models_boost, df[,.(x)], combine_boots = FALSE)

setDT(res)
 
#show all - curves
res[df, x := i.x, on=.(id) ]
ggplot(res, aes(x, y_pred, group = model_id2 )) + geom_line(alpha = 0.3) + facet_wrap(~model_id1 )

#boost results for each step
res_sum = res[, .(y_pred = mean(y_pred)), by =.(id, model_id1 )]
res_sum[df, x := i.x, on=.(id) ]
ggplot(res_sum, aes(x, y_pred, group = model_id1 )) + geom_line()  + facet_wrap(~model_id1 )

#boost results for each step
res_conv = res[, .(y_pred = mean(y_pred)), by =.(id, model_id1 )]
res_conv[order(model_id1), y_pred_cum := cumsum(y_pred), by =.(id)]
res_conv[df, x := i.x, on=.(id) ]
ggplot(res_conv, aes(x, y_pred_cum)) + geom_line(color = 'red', size = 1)  + geom_point(data = df, aes(x, y)) + facet_wrap(~model_id1 )

#Convergence
ggplot(res_conv[order(id), .(error = rms(y_pred_cum, df$y)), by =.(model_id1) ] , aes(model_id1, error)) + geom_line() +  geom_point()

# CV ---------
cv_res = rbf_boost.create_cv(df[,.(x)],  df$y,1, max_nodes = 32, n_runs = 10, max_it = 20, growth_rate =2.0, shrink_kernel = 0.65, nfolds = 10, kernel_fun = rbf_gauss_kernel, dist_fun = 'L1' )
df_cv_res = data.table(it = seq(nrow(cv_res)), avg = apply(cv_res, 1, mean ), sigma = apply(cv_res, 1, sd ), cv_res )
ggplot(df_cv_res, aes(it, avg)) + geom_line() + geom_point() + geom_ribbon(aes(it, ymin = avg - sigma, ymax = avg + sigma), alpha = 0.2, fill = 'blue')
```


## RBF Booting test all

```{r rbf_boost_test}
x = seq(0, 1, by = 0.01)
y = 0.2 + 0.4 * x * x + 0.3 *x * sin(15 * x) + 0.05 * cos(50 * x)
y = as.numeric(x>0.5) + 0.1*rnorm(length(x))
df = data.table(x, y)
df[, id:=seq(nrow(df))]

max_nodes = 32

df_res = ldply(names(rbf_kernels), function(my_kernel) {
  
  models_boost =  rbf_boost.create(df[,.(x)],  df$y, max_nodes, n_runs = 100,  growth_rate =2, kernel_fun = function(x) rbf_kernels[[my_kernel]](x),adaptive = TRUE)
  res = rbf_boost.predict(models_boost, df[,.(x)], combine_boots = TRUE)
  setDT(res)
  
  return ( cbind(res, my_kernel) )
  })

setDT(df_res)

df_res[df, x:=i.x, on =.(id)]
df_res[df, y:=i.y, on =.(id)]

#average
ggplot(df_res[model_id1 == max(model_id1)], aes(x, y)) + geom_point() + geom_line(aes(x, y_pred_cum), color = 'red', size = 1) + facet_wrap(~my_kernel)

ggplot(df_res[, .(error = rms(y_pred_cum,y) ), by =.(model_id1, my_kernel)], aes(model_id1, error)) + geom_line() + geom_point() + facet_wrap(~my_kernel)

```

## RBF with Noise

```{r rbf_boosting}
x = seq(0, 1, by = 0.001)
y = 0.2 + 0.4 * x * x + 0.3 *x * sin(15 * x) + 0.05 * cos(50 * x)
y = as.numeric(x>0.5)
df = data.table(x, yt = y, y = y + 0.01*rnorm(length(y)))
df[, id:=seq(nrow(df))]

ggplot(df, aes(x, y)) + geom_point() + geom_line(aes(x, yt), color = 'red', size = 1)

# CV
cv_res = rbf_boost.create_cv(df[,.(x)],  df$y, max_nodes = 100, n_runs = 30, max_it = 20, growth_rate = 2.0, nfolds = 10, kernel_fun = rbf_linear_kernel, dist_fun = 'L1' )
df_cv_res = data.table(it = seq(nrow(cv_res)), avg = apply(cv_res, 1, mean ), sigma = apply(cv_res, 1, sd ), cv_res )
ggplot(df_cv_res[avg>0], aes(it, avg)) + geom_line() + geom_ribbon(aes(it, ymin = avg - sigma, ymax = avg + sigma), alpha = 0.2, fill = 'blue') + 
  geom_hline(yintercept = 0.1, color = 'red', linetype = 'dashed')

df_cv_res[avg == min(avg)]#0.102632 

# build model
models_boost =  rbf_boost.create(df[,.(x)],  df$y,  max_nodes = 300, n_runs = 100, max_it = 20, growth_rate =2, kernel_fun = rbf_linear_kernel, dist_fun = 'L1' )
res = rbf_boost.predict(models_boost, df[,.(x)], combine_boots = FALSE)
setDT(res)
 
#show all - curves
res[df, x := i.x, on=.(id) ]
ggplot(res, aes(x, y_pred, group = model_id2 )) + geom_line(alpha = 0.3) + facet_wrap(~model_id1 )

#boost results for each step
res_sum = res[, .(y_pred = mean(y_pred)), by =.(id, model_id1 )]
res_sum[df, x := i.x, on=.(id) ]
ggplot(res_sum, aes(x, y_pred, group = model_id1 )) + geom_line()  + facet_wrap(~model_id1 )

#boost results for each step
res_conv = res[, .(y_pred = mean(y_pred)), by =.(id, model_id1 )]
res_conv[order(model_id1), y_pred_cum := cumsum(y_pred), by =.(id)]
res_conv[df, x := i.x, on=.(id) ]
ggplot(res_conv, aes(x, y_pred_cum)) + geom_line(color = 'red', size = 1)  +
  geom_point(data = df, aes(x, y), alpha = 0.1, size = 0.1) + 
  geom_line(data = df, aes(x, yt))  + facet_wrap(~model_id1 )

ggplot(res_conv[model_id1 == max(model_id1)], aes(x, y_pred_cum)) + geom_line(color = 'red', size = 1)  +
  geom_point(data = df, aes(x, y), alpha = 0.1, size = 0.1) + 
  geom_line(data = df, aes(x, yt))  + facet_wrap(~model_id1 )

rms(df$yt, res_conv[model_id1 == 12]$y_pred_cum)


## ------------- Boot model with the same number of nodes
models = rbf_boot.create(df[,.(x)], df$y, max_nodes = 31, n_runs = 1000, kernel_fun = rbf_linear_kernel)
res = rbf_boot.predict(models, df[,.(x)])
setDT(res)

res_agg = res[, .(y_pred = mean(y_pred), sigma = sd(y_pred), .N ), by =.(id)]
res_agg[df, x := i.x, on=.(id) ]

#average
ggplot(df, aes(x, yt)) + geom_line() + geom_line(data = res_agg, aes(x, y_pred), color = 'red', size = 1) + 
  geom_ribbon(data = res_agg, aes(x, ymin = y_pred - 2*sigma, ymax = y_pred + 2*sigma), alpha = 0.2, fill = 'blue', inherit.aes = FALSE)

rms(df$yt, res_agg$y_pred)
rms(df$y, res_agg$y_pred)

ggplot(res_agg, aes(x, y)) + geom_point() + geom_line(aes(x, y_pred), color = 'red', size = 1) + 
  geom_ribbon(aes(x, ymin = y_pred - 2*sigma, ymax = y_pred + 2*sigma), alpha = 0.2, fill = 'blue')

#convergence
res[order(run_id),y_pred_cum := cummean(y_pred), by =.(id) ]

it_error = res[order(id), .(error = rms(df$y, y_pred_cum)), by =.(run_id) ] #it_error[error == min(error)]
ggplot(it_error, aes(run_id, error)) + geom_line() + geom_hline(yintercept = 0.1, color = 'red', linetype = 'dashed')

## ------------- Boot CV
run_cases = expand.grid(nodes = seq(10, 60), runs = c(100, 200, 300, 1000), nfolds = c(2, 3, 4, 5, 6, 7, 8, 9, 10, 20))
cv_res = ldply(seq(nrow(run_cases)), function(run_id){
  cv_res = rbf_boot.create_cv(df[,.(x)], df$y, max_nodes = run_cases$nodes[run_id], boot_runs = run_cases$runs[run_id], nfolds =run_cases$nfolds[run_id],  
                              kernel_params = 1.0, kernel_fun = function(x, c) x, dist_fun = 'L1' )
  data.frame(cv_error = mean(cv_res), max_nodes = run_cases$nodes[run_id], boot_runs = run_cases$runs[run_id], nfolds =run_cases$nfolds[run_id])
})

ggplot(cv_res, aes(max_nodes, cv_error, group = nfolds, color = factor(nfolds) )) + geom_point() +  geom_line() + geom_smooth(se = FALSE, color = 'black') + facet_grid(nfolds~boot_runs) +
   geom_hline(yintercept = 0.1, color = 'red', linetype = 'dashed')
```

## RBF Boosting: Large Scale Test

```{r rbf_boosting_test}

train <- fread(file.path(working_folder,'Playground/Feb2021/data/train.csv'), check.names = TRUE)
test  <- fread(file.path(working_folder,'Playground/Feb2021/data/test.csv'),  check.names = TRUE) # 1459   80
test[, target:=NA]
df = rbind(train, test)

gc(reset=TRUE)

test_index = is.na(df$target)
train_index = !test_index

obj_var = 'target'
all_vars = names(df) %!in_set% c('id', obj_var) #14 variables
all_vars = all_vars[grep('^(cont|cat)', all_vars)]
cat_vars = all_vars[grep('^(cat)', all_vars)]
con_vars = all_vars[grep('^(cont)', all_vars)]

## ------------- Boot CV ------
convert_to_prob <-function(x, train_index){
  if(is.character(x) )x = as.numeric(as.factor(x))
  ecdf(x[train_index])(x)
}
p_vars = stri_join('p_', all_vars)
df[, (p_vars):=lapply(.SD, function(x) convert_to_prob(x, train_index)), .SDcols = all_vars]

#one hot for categorical variables ----
one_hot <- dummyVars(" ~ .", data=df[, cat_vars, with = FALSE])
dt_one_hot <- data.table(predict(one_hot, newdata =df[, cat_vars, with = FALSE]))
df = cbind(df, dt_one_hot)
rfb_vars = c(p_vars, names(dt_one_hot))
#rfb_vars= c(con_vars, names(dt_one_hot))

my_index = sample( which(train_index), 1.0*sum(train_index))
dfs = data.matrix(df[my_index,rfb_vars, with = FALSE])
target = df$target[my_index]

#%% bootsrap runs ----------------
#10 runs with 500 nodes - 4 min

null_rms = rms(target, mean(target) )


run_cases = expand.grid(nodes = c(300), runs = c(30, 40), dist_fun = c('L1'), rbf_kernel = c('rbf_linear_kernel', 'rbf_cauchy_kernel', 'rbf_mquad_kernel'), kernel_scale = c(1,2,3), stringsAsFactors = FALSE )

cv_res = ldply(seq(nrow(run_cases)), function(run_id){
  
  print(sprintf('it: %d out of %d', run_id, nrow(run_cases)))
  
  kernel_fun = function(x) rbf_kernels[[run_cases$rbf_kernel[run_id]]](x * run_cases$kernel_scale[run_id])
  
  cv_res = rbf_boot.create_cv(dfs, target, n_nodes = run_cases$nodes[run_id], n_runs = run_cases$runs[run_id], nfolds = 7, kernel_fun = rbf_kernels[[run_cases$rbf_kernel[run_id]]], dist_fun = run_cases$dist_fun[run_id] )
  data.frame(cv_error = mean(cv_res), cv_sigma = sd(cv_res), n_nodes = run_cases$nodes[run_id], n_runs = run_cases$runs[run_id], dist_fun = run_cases$dist_fun[run_id], 
             kernel_fun = run_cases$rbf_kernel[run_id],  scale = run_cases$kernel_scale[run_id])
})
setDT(cv_res)
#rbf_boot.create_cv(dfs, target, n_nodes = 1000, n_runs = 10, nfolds = 5, kernel_fun = rbf_linear_kernel, dist_fun = 'L1')
#source(file.path(working_folder, 'Utils/rbf_utils.R'))
ggplot(cv_res, aes(kernel_fun, cv_error, group = n_runs/null_rms, color = factor(n_runs) )) + geom_point() +  geom_line() + facet_wrap(~scale) # + facet_wrap(~dist_fun)# + geom_smooth(se = FALSE, color = 'black') + 
 


#cv error: 0.8510029
#target: 0.84309
min(cv_res$cv_error) #0.8533613


#%% boost runs ----------------
models_boost =  rbf_boost.create(dfs, target, max_nodes = 2561, n_runs = 20, max_it = 20, growth_rate = 1.5, kernel_fun = rbf_linear_kernel, dist_fun = 'L1', adaptive =TRUE )
res = rbf_boost.predict(models_boost, df[,rfb_vars, with = FALSE], combine_boots = TRUE)
setDT(res)
df[, target_rbf := res[order(id)][model_id1 == max(model_id1), y_pred_cum]] 
#ggplot(res[order(id), .(error = rms(y_pred_cum, df$target[my_index])), by =.(model_id1) ] , aes(model_id1, error)) + geom_line() +  geom_point()

#boost results for each step, run with combine_boots = FALSE
#res_conv = res[, .(y_pred = mean(y_pred)), by =.(id, model_id1 )]
#res_conv[order(model_id1), y_pred_cum := cumsum(y_pred), by =.(id)]
#ggplot(res_conv[order(id), .(error = rms(y_pred_cum, df$target[my_index])), by =.(model_id1) ] , aes(model_id1, error)) + geom_line() +  geom_point()

# CV ---------
cv_res = rbf_boost.create_cv(dfs, target, max_nodes = 300, n_runs = 40, max_it = 20, nfolds = 5, kernel_fun = rbf_linear_kernel, dist_fun = 'L1', adaptive =TRUE )
df_cv_res = data.table(it = seq(nrow(cv_res)), avg = apply(cv_res, 1, mean ), sigma = apply(cv_res, 1, sd ), cv_res )
ggplot(df_cv_res[avg>0], aes(it, avg)) + geom_line() + geom_ribbon(aes(it, ymin = avg - sigma, ymax = avg + sigma), alpha = 0.2, fill = 'blue')

#runs cv boost cases - grid search for optimal params, linear/mquad, L2
run_cases = expand.grid(nodes = c(1000), runs = c(10), dist_fun = c('L1', 'L2'), rbf_kernel = names(rbf_kernels), stringsAsFactors = FALSE )
cv_res = ldply(seq(nrow(run_cases)), function(run_id){
  cv_res = rbf_boost.create_cv(dfs, target, max_nodes = run_cases$nodes[run_id], n_runs = run_cases$runs[run_id], nfolds = 5, kernel_fun = rbf_kernels[[run_cases$rbf_kernel[run_id] ]], dist_fun = run_cases$dist_fun[run_id] )
  data.frame(cv_it = seq(nrow(cv_res)), cv_error = rowMeans(cv_res), cv_sigma = apply(cv_res,1, sd), 
             n_nodes = run_cases$nodes[run_id], 
             n_runs = run_cases$runs[run_id], 
             dist_fun = run_cases$dist_fun[run_id], 
             kernel_fun = run_cases$rbf_kernel[run_id])
})
setDT(cv_res)
cv_res[order(cv_error)]
ggplot(cv_res, aes(cv_it, cv_error, group = dist_fun, color = factor(dist_fun) )) + geom_point() +  geom_line()  + facet_wrap(~kernel_fun) + # + geom_smooth(se = FALSE, color = 'black') + 
   geom_hline(yintercept = 0.84164, color = 'red', linetype = 'dashed')

   
# Profiles
plots = llply(all_vars, function(var_name) {
  p = plot_profile( df[['target_rbf']][train_index],  df[['target']][train_index], df[[var_name]][train_index], bucket_count = 20, error_band = 'norm') +
    ggtitle(var_name) +  theme(title =element_text(size=6))
  return( ggplotGrob(p) )
})
marrangeGrob(plots, nrow = 5, ncol = 5, top = NULL)
```

## RBF 2D test

```{r rbf_2d_test}

df = data.table(expand.grid(x = seq(-1, 1, by = 0.02), y = seq(-1, 1, by = 0.02)))
df[, target_true:= sin(20*x * y)]
df[, target:= target_true + 0.2*rnorm(nrow(df))]
df[, id := seq(nrow(df))]

ggplot(df, aes(x, y, fill = target)) + geom_tile() + scale_fill_custom('jet', discrete = FALSE)
ggplot(df, aes(x, y, fill = target_true)) + geom_tile() + scale_fill_custom('jet', discrete = FALSE)

#rbf_mquad_kernel, 

models_boost =  rbf_boost.create(df[,.(x, y)], df$target, max_nodes = 512, n_runs = 10, max_it = 100, growth_rate = 2.0, kernel_fun = rbf_linear_kernel, dist_fun = 'L2', adaptive = TRUE)
res = rbf_boost.predict(models_boost, df[,.(x, y)], combine_boots = TRUE)
setDT(res)

res[order(id), .(rms(y_pred_cum, df$target), rms(y_pred_cum, df$target_true)), by = .(model_id1)]

res_df = res[df, on = .(id)]

ggplot(res_df, aes(x, y, fill = y_pred_cum  )) + geom_tile() + scale_fill_custom('jet', discrete = FALSE) + facet_wrap(~model_id1)
#ggplot(res_df, aes(x, y, fill = y_pred  )) + geom_tile() + scale_fill_custom('jet', discrete = FALSE) + facet_wrap(~model_id1)
#0.244613


nodes = ldply(seq(length(models_boost)), function(model_id1) {
      boot_models = models_boost[[model_id1]]
      ldply(seq(length(boot_models)), function(model_id2) {
        data.frame(boot_models[[model_id2]]$nodes, model_id1, model_id2)
      })
    })
ggplot(nodes, aes(x, y)) + geom_point(size = 0.2) + facet_wrap(~model_id1) 

```


## RBF Singular

```{r rbf_singular}
df = data.table(expand.grid(x = c(0, 1), y = c(0, 1)))
df[, v := sample(c(0, 1), nrow(df), replace = TRUE) ]

rbf.create(df[,.(x, y)], df$v, df[,.(x, y)], rbf_linear_kernel, dist_fun = 'L1')



```


```{r submit, echo=FALSE}
  #fwrite(df, file.path(working_folder,'Playground/Feb2021/data/df.csv'))

  #%% boost runs ----------------
  models_boost =  rbf_boost.create(dfs, target, max_nodes = 2561, n_runs = 20, max_it = 20, growth_rate = 1.5, kernel_fun = rbf_linear_kernel, dist_fun = 'L1', adaptive =TRUE )
  res = rbf_boost.predict(models_boost, df[,rfb_vars, with = FALSE], combine_boots = TRUE)
  setDT(res)
  df[, target_rbf := res[order(id)][model_id1 == max(model_id1), y_pred_cum]] 
  

  file = file.path(working_folder, "Playground/Feb2021/submit_v3.rbf.csv")
  fwrite(df[test_index, .(id, target=target_rbf)], file = file, row.names = FALSE)
  zip(paste(file, '.zip', sep = ''), file, flags = '-r9Xj')
  print(file)

```

