---
title: "Unemployment Trends"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(proxy)
library(MASS)
library(ggplot2)
library(plyr)
library(dplyr)
library(stringi)
library(caret)
library(gridExtra)
library(GGally)
library(gpairs)
library(lubridate)
library(expm)  
library(foreach)
library(zoo)  

#optimization
library(Rsolnp)
library(nloptr)

working_folder = 'D:/Github/KaggleSandbox'

source(file.path(working_folder, 'Utils/common.R'))


```

## Load Data

```{r load_data}

df_uer = fread(file.path(working_folder, 'data/mev/UNRATE.csv'))
df_iuic = fread(file.path(working_folder, 'data/mev/ICSA.csv'))
df_pop = fread(file.path(working_folder, 'data/mev/POPTHM.csv'))
df_labor_part = fread(file.path(working_folder, 'data/mev/CIVPART.csv'))
df_uer_weeks = fread(file.path(working_folder, 'data/mev/UEMPMEAN.csv'))

df_uer[, date := as.Date(DATE)]
df_iuic[, date := as.Date(DATE)]
df_iuic[, date_month := make_date(year(date), month(date), 1)]
df_pop[, date := as.Date(DATE)]
df_labor_part[, date := as.Date(DATE)]
df_uer_weeks[, date := as.Date(DATE)]

df_iuic_m = df_iuic[, .(.N, iuic = mean(ICSA, na.rm = TRUE)), by =.(date_month)]

df = df_uer[, .(date, uer = UNRATE)]
df[df_iuic_m, iuic := 1e-3*i.iuic, on=.(date = date_month)]
df[df_pop, pop := 1e-3*i.POPTHM, on=.(date)]
df[df_labor_part, lpart := i.CIVPART, on=.(date)]
df[df_uer_weeks, u_weeks := i.UEMPMEAN, on=.(date)]

df = df[complete.cases(df)]#1967-01-01 - all data becomes 

df[, e_pop :=  pop * (lpart/100) * (1 - 0.01*uer)]
df[, u_pop :=  pop * (lpart/100) * (0.01*uer)]

df[, iuic_rate := 0.1*iuic * (52/12) / (pop * lpart * (1 - 0.01*uer)) ]
df[order(date), e_pop_change := c(0, diff(e_pop)) ]

setorder(df, date)


ggplot(df, aes(date, u_pop/pop)) + geom_line() + geom_line(aes(date, 0.01*uer), color = 'red')
ggplot(df, aes(date, uer)) + geom_line() 
ggplot(df, aes(date, pop)) + geom_line()
ggplot(df, aes(date, e_pop)) + geom_line()
ggplot(df, aes(date, u_pop)) + geom_line()
ggplot(df, aes(date, iuic)) + geom_line()
ggplot(df, aes(date, lpart)) + geom_line()
ggplot(df, aes(date, iuic_rate)) + geom_line()
ggplot(df, aes(date, e_pop_change)) + geom_line()
ggplot(df, aes(date, pop * (lpart/100) * (1 - 0.01*uer))) + geom_line()

ggplot(df, aes(date, pop * (lpart/100) * (1 - 0.01*uer))) + geom_line() + geom_line(aes(date, pop * (lpart/100) * (1 - 0.01*uer) + iuic * (52/12) / 1000), color = 'red')

ggplot(df, aes(date, iuic_rate )) + geom_line()

#ggpairs(df)
```

## Wavelets

```{r wavelets_filter}
library(wavethresh)

df_s = df[date<'2020-03-01',.(date, uer, pop, iuic = iuic)][order(date)]


#wds <- wd(df_s[1:8, uer], filter.number = 1, family="DaubExPhase")
#wr(wds) - df_s[1:64, uer]
x = c(-1, 3, 4, 5, -3, 6, 7, 2)
wds <- wd(x, filter.number = 1, family="DaubExPhase")
haarmat <- GenW(8, filter.number=1, family="DaubExPhase")

haar_x = t(haarmat) %*%  x #forward transform 
haarmat %*%  haar_x #invese transform 

wr(wds$D,  filter.number = 1, family="DaubExPhase")

plot(wds$D)
plot(wds$C)

plot.ts(df_s[1:8, uer])
plot.ts(accessC(wds, level = 2))
plot.ts(accessD(wds, level = 2))
plot(wds)

draw.default(filter.number = 1, family="DaubExPhase")


```

## Signal Filtering

```{r signal_filtering}
library(glmnet)
library(TTR)
library(corrplot)

my_ewma <- function(x, a) {
  s1 <- x[1]
  sk <- s1
  s <- vapply(x[-1], function(x) sk <<- (1 - a) * x + a * sk, 0)
  s <- c(s1, s)
  return(s)
}

get_all_coefs<-function(glmnet_obj){
  res = ldply(glmnet_obj$lambda, function(lambda){
    temp = data.matrix(coef(glmnet_obj,s=lambda))
    data.frame(var_name = rownames(temp), coef = as.numeric(temp), lambda)
  })
  return(res)
}


#try to predict UER from IUIC

fir_weights = rep(1, 10)/10
df[, uer_fir   := frollapply(uer, n = 10, FUN = function(x) sum(x * fir_weights))  ]
df[, uer_fir_t := rollmeanr(uer, k = 10, fill = NA)  ]

ggplot(df, aes(date, uer)) + geom_line() + geom_line(aes(date, uer_fir), color = 'red')
ggplot(df, aes(date, iuic)) + geom_line() 

df_s = df[date<'2020-03-01',.(date, uer, pop, iuic = iuic)][order(date)]

#add lagged vars
for(i in seq(0, 64)) {
  vname = sprintf('iuic_lag_%02d', i)
  df_s[, c(vname) := shift(iuic, i)]  
}

#add haar 
haarmat <- t(GenW(64, filter.number=1, family="DaubExPhase"))
for(i in seq(64)) {
  vname = sprintf('iuic_haar_%02d', i)
  df_s[, c(vname)   := frollapply(iuic, n = 64, FUN = function(x) sum(x * haarmat[i,]))  ]
}

model_vars = names(df_s)[ grep('iuic_lag', names(df_s)) ]

model.lm = lm(formula(stri_join('uer ~', stri_join(model_vars, collapse = ' + '))), df_s)
summary(model.lm)

df_s[, uer_pred := predict(model.lm, df_s)]

ggplot(df_s, aes(date, uer)) + geom_line() + geom_line(aes(date, uer_pred), color = 'red')
#ggplot(df_s, aes(date, uer)) + geom_line() + geom_line(aes(date, iuic_lag_64/100), color = 'red')

coefs = coefficients(model.lm)

ggplot(data.table(val = coefs, name = names(coefs))[name != '(Intercept)'], aes(name, val) ) + geom_bar(stat = 'identity') +  theme(axis.text.x  = element_text(angle=90))

#lasso
x=data.matrix(df_s[, model_vars, with = FALSE])
index = complete.cases(x)
x = x[index,]
y = df_s$uer[index]

#corrplot(cor(x), method="ellipse")

#fit1=glmnet(x,y, family="gaussian")
cvob3=cv.glmnet(x, y, family="gaussian", nfolds = 10)
plot(cvob3)

ggplot(data.frame(rms = cvob3$cvm, rms_hi = cvob3$cvup, rms_lo = cvob3$cvlo, lambda = log(cvob3$lambda)) , aes(lambda, rms) ) + geom_line() + 
  geom_ribbon(aes(ymin = rms_lo, ymax = rms_hi), fill = 'blue', alpha = 0.3) +
  geom_vline(xintercept =  c(log(cvob3$lambda.min),  log(cvob3$lambda.1se), -2), linetype = 'dashed') +
  ggtitle(sprintf('Best RMS %.5f', cvob3$cvm[which(cvob3$lambda == cvob3$lambda.1se)]))

cvob3$cvm[which(cvob3$lambda == cvob3$lambda.min)]
cvob3$cvm[which(cvob3$lambda == cvob3$lambda.1se)]
cvob3$glmnet.fit$df[which(cvob3$lambda == cvob3$lambda.1se)]
cvob3$glmnet.fit$df[which(cvob3$lambda == cvob3$lambda.min)]

coef_path = data.table(get_all_coefs(cvob3))
imp_vars = as.character(unique( coef_path[lambda >= cvob3$lambda.1se & abs(coef) >0, var_name] ))
ggplot(coef_path[var_name %in% imp_vars, ][var_name != '(Intercept)'], aes(log(lambda), coef, group = var_name, color = var_name )) + geom_line() + 
  geom_vline(xintercept = log(cvob3$lambda.1se), linetype = 'dashed') + facet_wrap(~var_name, scales = 'free')

ggplot(coef_path[var_name != '(Intercept)'], aes(var_name, coef, group = lambda, fill = log(lambda) )) + 
    geom_bar(stat = 'identity', position = 'dodge') +  theme(axis.text.x  = element_text(angle=90)) + scale_fill_custom('jet',discrete = FALSE)

all_lambdas = sort(unique(coef_path$lambda))
#which(abs(all_lambdas  - exp(-1))<0.01 )

ggplot(coef_path[var_name != '(Intercept)'][lambda == all_lambdas[42], ], aes(var_name, coef, group = lambda)) + 
    geom_bar(stat = 'identity', position = 'dodge') +  theme(axis.text.x  = element_text(angle=90))

ggplot(coef_path[var_name %in% imp_vars, ][var_name != '(Intercept)'], aes(log(lambda), coef, group = var_name, color = var_name )) + geom_line() + 
  geom_vline(xintercept = c(log(cvob3$lambda.1se), -1), linetype = 'dashed') + facet_wrap(~var_name, scales = 'free')

ggplot(coef_path[var_name %in% imp_vars, ][var_name != '(Intercept)'], aes(log(lambda), coef, group = var_name, color = var_name )) + geom_line() + 
  geom_vline(xintercept = c(log(cvob3$lambda.1se), -1), linetype = 'dashed') + scale_color_custom('mixed')

df_s[, uer_pred := predict(cvob3, newx=data.matrix(df_s[,model_vars, with = F]), s= exp(-1))]

ggplot(df_s, aes(date, uer)) + geom_line() + geom_line(aes(date, uer_pred), color = 'red')

summary(lm('uer ~ uer_pred', df_s))

#ewma with rate 0.86762056331924
df_s[, iuic_ewma := my_ewma(iuic, 0.86762056331924) ]

ggplot(df_s, aes(date, iuic)) + geom_line() + geom_line(aes(date, iuic_ewma), color = 'red')

summary(lm('uer ~ iuic_ewma', df_s))

df_s[, uer_pred := predict(lm('uer ~ iuic_ewma', df_s), df_s)]
ggplot(df_s, aes(date, uer)) + geom_line() + geom_line(aes(date, uer_pred), color = 'red')

#add diff vars ----- 
for(i in seq(0, 64)) {
  vname = sprintf('iuic_diff_%02d', i)
  
  if(i == 0)
    df_s[, c(vname) := shift(iuic, i)]  
  else
    df_s[, c(vname) := shift(iuic, i) - shift(iuic, i-1)]  
    
}

model_diff_vars = names(df_s)[ grep('iuic_diff', names(df_s)) ]

x=data.matrix(df_s[, model_diff_vars, with = FALSE])
index = complete.cases(x)
x = x[index,]
y = df_s$uer[index]

#corrplot(cor(x), method="ellipse")
cvob3=cv.glmnet(x, y, family="gaussian", nfolds = 10)
plot(cvob3)

ggplot(data.frame(rms = cvob3$cvm, rms_hi = cvob3$cvup, rms_lo = cvob3$cvlo, lambda = log(cvob3$lambda)) , aes(lambda, rms) ) + geom_line() + geom_point() + 
  geom_ribbon(aes(ymin = rms_lo, ymax = rms_hi), fill = 'blue', alpha = 0.3) +
  geom_vline(xintercept =  c(log(cvob3$lambda.min),  log(cvob3$lambda.1se), -2), linetype = 'dashed') +
  ggtitle(sprintf('Best RMS %.5f', cvob3$cvm[which(cvob3$lambda == cvob3$lambda.1se)]))

coef_path = data.table(get_all_coefs(cvob3))
imp_vars = as.character(unique( coef_path[lambda >= cvob3$lambda.1se & abs(coef) >0, var_name] ))

ggplot(coef_path[var_name != '(Intercept)'][lambda == cvob3$lambda.1se, ], aes(var_name, coef, group = lambda)) + 
    geom_bar(stat = 'identity', position = 'dodge') +  theme(axis.text.x  = element_text(angle=90))

ggplot(coef_path[var_name != '(Intercept)'][lambda == cvob3$lambda.1se, ], aes(var_name, c(-diff(coef),coef[length(coef)]), group = lambda)) + 
    geom_bar(stat = 'identity', position = 'dodge') +  theme(axis.text.x  = element_text(angle=90))

df_s[, uer_pred := predict(cvob3, newx=data.matrix(df_s[,model_diff_vars, with = F]), s= 'lambda.1se')]
ggplot(df_s, aes(date, uer)) + geom_line() + geom_line(aes(date, uer_pred), color = 'red')

summary(lm('uer ~ uer_pred', df_s))

#reconstruct
diff_coefs = c(coef_path[var_name == '(Intercept)'][lambda == cvob3$lambda.1se,coef], coef_path[var_name != '(Intercept)' & lambda == cvob3$lambda.1se][order(var_name), c(-diff(coef),coef[length(coef)])])
x = data.matrix(df_s[, model_vars, with = FALSE])
df_s[, uer_pred := cbind(intercept = 1, x) %*% diff_coefs]

ggplot(df_s, aes(date, uer)) + geom_line() + geom_line(aes(date, uer_pred), color = 'red')

#add rolling mean vars ----- 
for(i in seq(120)) {
  vname = sprintf('iuic_rm_%03d', i)
  df_s[order(date), c(vname) := rollmeanr(iuic, k = i, fill = NA)]  
}

for(i in seq(120)) {
  vname = sprintf('pop_rm_%03d', i)
  df_s[order(date), c(vname) := rollmeanr(pop, k = i, fill = NA)]  
}

#model_rm_vars = names(df_s)[ grep('iuic_rm', names(df_s)) ]
model_rm_vars = names(df_s)[ grep('pop_rm', names(df_s)) ]

x=data.matrix(df_s[, model_rm_vars, with = FALSE])
index = complete.cases(x)
x = x[index,]
y = df_s$uer[index]

#corrplot(cor(x), method="ellipse")
cvob3=cv.glmnet(x, y, family="gaussian", nfolds = 10, relax = FALSE)
plot(cvob3)

ggplot(data.frame(rms = cvob3$cvm, rms_hi = cvob3$cvup, rms_lo = cvob3$cvlo, lambda = log(cvob3$lambda)) , aes(lambda, rms) ) + geom_line() + geom_point() + 
  geom_ribbon(aes(ymin = rms_lo, ymax = rms_hi), fill = 'blue', alpha = 0.3) +
  geom_vline(xintercept =  c(log(cvob3$lambda.min),  log(cvob3$lambda.1se)), linetype = 'dashed') +
  ggtitle(sprintf('Best RMS %.5f', cvob3$cvm[which(cvob3$lambda == cvob3$lambda.1se)]))

coef_path = data.table(get_all_coefs(cvob3))
coef_path[order(var_name), weight := seq(0, .N-1),  by =.(lambda)]
coef_path[order(var_name,  decreasing = TRUE), adj_coef := cumsum(coef / weight),  by =.(lambda)]
coef_path[, dof:=sum(coef==0), by =.(lambda)]
coef_path[var_name != '(Intercept)', .( sum(coef),  sum(adj_coef)), by =.(lambda)] #sum of the coefs  -0.013400167

imp_vars = as.character(unique( coef_path[lambda >= cvob3$lambda.1se & abs(coef) >0, var_name] ))

ggplot(coef_path[var_name != '(Intercept)'], aes(var_name, log(lambda), fill = coef)) + geom_tile() +  
  theme(axis.text.x  = element_text(angle=90)) + 
  geom_hline(yintercept = log(c(cvob3$lambda.1se, cvob3$lambda.min)), linetype = 'dashed') + 
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0)

ggplot(coef_path[var_name != '(Intercept)'][lambda == cvob3$lambda.1se, ], aes(var_name, coef, group = lambda)) + 
    geom_bar(stat = 'identity', position = 'dodge') +  theme(axis.text.x  = element_text(angle=90))

df_s[, uer_pred := predict(cvob3, newx=data.matrix(df_s[,model_rm_vars, with = F]), s= 'lambda.1se')]
ggplot(df_s, aes(date, uer)) + geom_line() + geom_line(aes(date, uer_pred), color = 'red')

summary(lm('uer ~ uer_pred', df_s))

#reconstruct
rm_coefs = c(coef_path[var_name == '(Intercept)'][lambda == cvob3$lambda.1se,coef], coef_path[var_name != '(Intercept)' & lambda == cvob3$lambda.1se][order(var_name), adj_coef])
x = data.matrix(df_s[, model_vars %!in_set% c('iuic_lag_64'), with = FALSE])[, -nrow(x)]
df_s[, uer_pred := cbind(intercept = 1, x) %*% rm_coefs]

ggplot(df_s, aes(date, uer)) + geom_line() + geom_line(aes(date, uer_pred), color = 'red')

## gen all curves
data_temp = data.matrix(df_s[, model_rm_vars, with = F])

res = ldply(cvob3$lambda, function(my_lambda){
  data.frame(date = df_s$date, uer = df_s$uer,uer_pred = as.numeric(predict(cvob3, newx=data_temp, s = my_lambda)), lambda = my_lambda)
})
setDT(res)

ggplot(res, aes(date, uer_pred, color = log(lambda), group = lambda)) + geom_line() + geom_line(aes(date, uer), color = 'black', size = 1)

ggplot(res[lambda %in% c(cvob3$lambda.1se, cvob3$lambda.min, cvob3$lambda[3]) ], aes(date, uer_pred, color = factor(log(lambda)), group = lambda ) ) + geom_line() + 
  geom_line(aes(date, uer), color = 'black', size = 1)

coef_path[lambda == cvob3$lambda[10] & coef != 0]


#add HAAR vars
#model_rm_vars = names(df_s)[ grep('iuic_rm', names(df_s)) ]
model_haar_vars = names(df_s)[ grep('iuic_haar', names(df_s)) ]

x=data.matrix(df_s[, model_haar_vars, with = FALSE])
index = complete.cases(x)
x = x[index,]
y = df_s$uer[index]

#corrplot(cor(x), method="ellipse")
cvob3=cv.glmnet(x, y, family="gaussian", nfolds = 10, relax = FALSE)
plot(cvob3)

ggplot(data.frame(rms = cvob3$cvm, rms_hi = cvob3$cvup, rms_lo = cvob3$cvlo, lambda = log(cvob3$lambda)) , aes(lambda, rms) ) + geom_line() + geom_point() + 
  geom_ribbon(aes(ymin = rms_lo, ymax = rms_hi), fill = 'blue', alpha = 0.3) +
  geom_vline(xintercept =  c(log(cvob3$lambda.min),  log(cvob3$lambda.1se)), linetype = 'dashed') +
  ggtitle(sprintf('Best RMS %.5f', cvob3$cvm[which(cvob3$lambda == cvob3$lambda.1se)]))

coef_path = data.table(get_all_coefs(cvob3))
coef_path[order(var_name), weight := seq(0, .N-1),  by =.(lambda)]
coef_path[, dof:=sum(coef==0), by =.(lambda)]
coef_path[var_name != '(Intercept)', adj_coef :=  rev(t(haarmat) %*% coef),  by =.(lambda)]

imp_vars = as.character(unique( coef_path[lambda >= cvob3$lambda.1se & abs(coef) >0, var_name] ))

ggplot(coef_path[var_name != '(Intercept)'], aes(log(lambda), coef, fill = var_name)) + geom_bar(stat = 'identity') +
  coord_flip() + scale_fill_custom('mixed') + geom_vline(xintercept = log(c(cvob3$lambda.1se, cvob3$lambda.min)), linetype = 'dashed')
  
ggplot(coef_path[var_name != '(Intercept)'], aes(var_name, log(lambda), fill = coef)) + geom_tile() +  
  theme(axis.text.x  = element_text(angle=90)) + 
  geom_hline(yintercept = log(c(cvob3$lambda.1se, cvob3$lambda.min)), linetype = 'dashed') + 
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0)

ggplot(coef_path[var_name != '(Intercept)'], aes(var_name, log(lambda), fill =  adj_coef)) + geom_tile() +  
  theme(axis.text.x  = element_text(angle=90)) + 
  geom_hline(yintercept = log(c(cvob3$lambda.1se, cvob3$lambda.min)), linetype = 'dashed') + 
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0)

ggplot(coef_path[var_name != '(Intercept)'][lambda == cvob3$lambda.1se, ], aes(var_name, coef, group = lambda)) + 
    geom_bar(stat = 'identity', position = 'dodge') +  theme(axis.text.x  = element_text(angle=90))

ggplot(coef_path[var_name != '(Intercept)'][lambda == cvob3$lambda.1se, ], aes(var_name, rev(t(haarmat) %*% coef), group = lambda)) + 
    geom_bar(stat = 'identity', position = 'dodge') +  theme(axis.text.x  = element_text(angle=90))


df_s[, uer_pred := predict(cvob3, newx=data.matrix(df_s[,model_haar_vars, with = F]), s= 'lambda.1se')]
ggplot(df_s, aes(date, uer)) + geom_line() + geom_line(aes(date, uer_pred), color = 'red')

summary(lm('uer ~ uer_pred', df_s))

#reconstruct
haar_coefs = coef_path[lambda == cvob3$lambda.1se][order(var_name), coef]
rm_coefs = t(haarmat) %*% haar_coefs[-1]
x = data.matrix(rev(df_s[, model_vars %!in_set% c('iuic_lag_64'), with = FALSE]))
df_s[, uer_pred := haar_coefs[1] + x %*% rm_coefs]
ggplot(df_s, aes(date, uer)) + geom_line() + geom_line(aes(date, uer_pred), color = 'red')


## gen all curves
data_temp = data.matrix(df_s[, model_haar_vars, with = F])
res = ldply(cvob3$lambda, function(my_lambda){
  data.frame(date = df_s$date, uer = df_s$uer,uer_pred = as.numeric(predict(cvob3, newx=data_temp, s = my_lambda)), lambda = my_lambda)
})
setDT(res)

ggplot(res, aes(date, uer_pred, color = log(lambda), group = lambda)) + geom_line() + geom_line(aes(date, uer), color = 'black', size = 1)

ggplot(res[lambda %in% c(cvob3$lambda.1se, cvob3$lambda.min, cvob3$lambda[3]) ], aes(date, uer_pred, color = factor(log(lambda)), group = lambda ) ) + geom_line() + 
  geom_line(aes(date, uer), color = 'black', size = 1)

coef_path[lambda == cvob3$lambda[10] & coef != 0]
coef_path[lambda == cvob3$lambda.1se & coef != 0]

model.lm.haar = lm('uer ~ iuic_haar_64 + iuic_haar_01 + iuic_haar_63', df_s)
df_s[, uer_pred := predict(model.lm.haar, df_s[,model_haar_vars, with = F])]
ggplot(df_s, aes(date, uer)) + geom_line() + geom_line(aes(date, uer_pred), color = 'red')

haar_basis = data.table(reshape2::melt(haarmat))
haar_basis[, level := floor(log2(65 - Var1)) ]
haar_basis[level==6,level:=0]
ggplot(haar_basis, aes(Var2,value, group = Var1 )) + geom_line() + facet_wrap(~level) + theme(legend.position = 'none')

```

## Average transition matrix

```{r static_transition}
start_date = '1980-01-01'
states = c('E', 'U', 'N') #E=employed, U=unemployed, N - Not in Labor force 

tr_matrix = t(matrix(c(0.99, 0.01, 0.01, 
                       0.1,   0.8, 0.1,
                       0.0,   0.1, 0.9), nrow = 3))
#6- params
tr_matrix_from_params <- function(tr_rates){
  
  r = exp(tr_rates)
  
  r_eu = r[1] / (1 + r[1] + r[2])
  r_en = r[2] / (1 + r[1] + r[2])
  
  r_ue = r[3] / (1 + r[3] + r[4])
  r_un = r[4] / (1 + r[3] + r[4])
  
  r_ne = r[5] / (1 + r[5] + r[6])
  r_nu = r[6] / (1 + r[5] + r[6])
  
  tr_temp = t(matrix(c(1-r_eu-r_en, r_eu, r_en, 
                       r_ue,   1-r_un-r_ue, r_un,
                       r_ne,   r_nu, 1-r_nu-r_ne), nrow = 3))
  return (tr_temp)
} 

#static monthly
obj_fun <-function(tr_rates_params){
  tr_temp = tr_matrix_from_params(tr_rates_params)
  
  st = df[order(date) & date>=start_date,.(lpart * (1 - 0.01*uer),0.01*lpart * uer, 100-lpart  )]
  st_next = as.matrix(st) %*% (tr_temp)
  
  res = st[-1,] - st_next[-nrow(st_next),]
  return ( norm(as.matrix(res), type = 'F') )
  
    #ggplot() + geom_line(data = cbind(st, df[order(date) & date>=start_date, .(date) ]), aes(date, V2), inherit.aes = FALSE) + geom_line(data = cbind(st_next, df[order(date) & date>=start_date, .(date) ]), aes(date, V2), inherit.aes = FALSE, color = 'red')
  #ggplot() + geom_line(data = cbind(st, df[order(date) & date>=start_date, .(date) ]), aes(date, V1), inherit.aes = FALSE) + geom_line(data = cbind(st_next, df[order(date) & date>=start_date, .(date) ]), aes(date, V1), inherit.aes = FALSE, color = 'red')
  #ggplot() + geom_line(data = cbind(st, df[order(date) & date>=start_date, .(date) ]), aes(date, V3), inherit.aes = FALSE) + geom_line(data = cbind(st_next, df[order(date) & date>=start_date, .(date) ]), aes(date, V3), inherit.aes = FALSE, color = 'red')
}


tr_rates_params = c(-11.407737,  -5.609309, -11.569209, -14.547898,  -5.065347, -14.862557)#static monthly params
res = optim(tr_rates_params, obj_fun, method = 'L-BFGS', control = list(trace = TRUE))
#res = optim(tr_rates, obj_fun, method = 'Nelder-Mead', control = list(trace = TRUE, maxit =  500))

start_date = '1980-01-01'
start_states = as.numeric(df[date==start_date,.(lpart * (1 - 0.01*uer),0.01*lpart * uer, 100-lpart  )])

tr_matrix = tr_matrix_from_params(tr_rates_params)
start_states %*% (tr_matrix %^% 30)
```

## IUIC driven transitions

```{r iuic_transitions}
#library(dfoptim)

start_date = '1980-01-01'
end_date = '2020-01-01'
states = c('E', 'U', 'N') #E=employed, U=unemployed, N - Not in Labor force 

#static monthly
obj_fun <-function(tr_rates_params){
  
  index = df$date>=start_date
  
  date      = df[index, date]
  st        = df[index,.(E=lpart * (1 - 0.01*uer), U = 0.01*lpart * uer, N = 100 - lpart)]
  iuic_rate = df[index, iuic_rate]
  
  st = as.matrix(st)
  st_next = st
  
  #fit annual transition
  stride = 12
  for(j in 2:(nrow(st) - stride)) {
    
    st_temp = st[j,]
    
    for(i in 1:stride) {
      br = iuic_rate[j + i - 2]/0.01
      
      params = br*tr_rates_params[1:6] + tr_rates_params[-(1:6)]
      
      st_temp = st_temp %*% (tr_matrix_from_params(params))
    }
    st_next[j + stride,] = st_temp
  }
  
  res = st - st_next
  return ( norm(as.matrix(res[date <= end_date,]), type = 'F') )
  
  #ggplot() + geom_line(data = cbind(st, df[index, .(date) ]), aes(date, U), inherit.aes = FALSE) + geom_line(data = cbind(st_next, df[index, .(date) ]), aes(date, U), inherit.aes = FALSE, color = 'red')
  #ggplot() + geom_line(data = cbind(st, df[index, .(date) ]), aes(date, E), inherit.aes = FALSE) + geom_line(data = cbind(st_next, df[index, .(date) ]), aes(date, E), inherit.aes = FALSE, color = 'red')
  #ggplot() + geom_line(data = cbind(st, df[index, .(date) ]), aes(date, N), inherit.aes = FALSE) + geom_line(data = cbind(st_next, df[index, .(date) ]), aes(date, N), inherit.aes = FALSE, color = 'red')
  #ggplot() + geom_line(data = cbind(st, df[index, .(date) ]), aes(date, (E+U)/(E+U+N)), inherit.aes = FALSE) + geom_line(data = cbind(st_next, df[index, .(date) ]), aes(date, (E+U)/(E+U+N)), inherit.aes = FALSE, color = 'red')
}

tr_rates_params = c(1.27978427178106, -5.67323498117342, 49.409058108502, 20.9042971355755, 1.12264113480967, 0.56638352411322, -5.78883475986432, -3.65211542845336, -48.9505357368036, 13.9550027827274, -4.91161205468058, -2.74443738181706)#rep(1, 12)
#tr_rates_params = c(rep(0, 6), rep(-2, 6))

#tr_rates_params = c(0.624466113165663, -0.550644085442827, -42.6741137108064, -113.317541518673, -0.947400611828628, 3.7324598895776, 0.475600512332723, -3.98150479813621, 289.803404703998, -65.4518720642512, -5.1265878334206, 7.43952709092029)
res = optim(tr_rates_params, obj_fun, method = 'L-BFGS', control = list(trace = TRUE))
res = solnp(tr_rates_params, fun = obj_fun)

#res = hjk(tr_rates_params, obj_fun, control = list(maxfeval = 1000, info= TRUE))
#tr_rates_params = res$par 
#cat(paste(res$par, collapse=", "))
#res = optim(tr_rates_params, obj_fun, method = 'Nelder-Mead', control = list(trace = TRUE, maxit =  5000))
#res = optim(tr_rates_params, obj_fun, method = 'SANN', control = list(trace = TRUE))
res <- nloptr(x0=tr_rates_params, eval_f=obj_fun,opts= list("algorithm"="NLOPT_LN_SBPLX","xtol_rel"=1.0e-8, maxeval = 1000))
#cat(paste(res$solution, collapse=", "))


start_states = as.numeric(df[date==start_date,.(lpart * (1 - 0.01*uer),0.01*lpart * uer, 100-lpart  )])

tr_matrix = tr_matrix_from_params(tr_rates_params)
start_states %*% (tr_matrix %^% 30)

rownames(tr_matrix)<-states
colnames(tr_matrix)<-states

ggplot(reshape2::melt(tr_matrix), aes(Var1, Var2, fill = value, label = sprintf('%.2f', 100*value) ))  + geom_tile() + geom_text()
```

## DepMix

```{r hmm__transitions_ex}
library(depmixS4)
data('speed')
set.seed(1)

mod <- depmix(response = rt ~ 1, data = speed, nstates = 2, trstart = runif(4))

fm <- fit(mod, emc=em.control(rand=FALSE))
summary(fm)
```


## HMM

```{r hmm__transitions}
#library(depmixS4)
library(HMM)

# Initialise HMM
hmm = initHMM(c("A","B"), c("L","R"), transProbs=matrix(c(.8,.2,.2,.8),2),emissionProbs=matrix(c(.6,.4,.4,.6),2))
print(hmm)
# Sequence of observations
sim = simHMM(hmm, 10)
# Calculate forward probablities
logForwardProbabilities = forward(hmm,sim$observation)
logBackwardProbabilities = backward(hmm,sim$observation)
print(exp(logForwardProbabilities))

viterbi = viterbi(hmm,sim$observation)
print(viterbi)


# Sequence of observation
a = sample(c(rep("L",100),rep("R",300)))
b = sample(c(rep("L",300),rep("R",100)))
observation = c(a,b)
# Viterbi-training
vt = viterbiTraining(hmm,observation,10)
print(vt$hmm)

# Baum-Welch
bw = baumWelch(hmm,observation,10)
print(bw$hmm)
```

```{r dishonestCasino_transitions}

  #dishonestCasino()

  nSim = 2000
  States = c("Fair", "Unfair")
  Symbols = 1:6
  transProbs = matrix(c(0.99, 0.01, 0.02, 0.98), c(length(States), length(States)), byrow = TRUE)
  emissionProbs = matrix(c(rep(1/6, 6), c(rep(0.1, 5), 0.5)), c(length(States), length(Symbols)), byrow = TRUE)
  hmm = initHMM(States, Symbols, transProbs = transProbs, emissionProbs = emissionProbs)
  sim = simHMM(hmm, nSim)
  vit = viterbi(hmm, sim$observation)
  f = forward(hmm, sim$observation)
  b = backward(hmm, sim$observation)
  i <- f[1, nSim]
  j <- f[2, nSim]
  probObservations = (i + log(1 + exp(j - i)))
  posterior = exp((f + b) - probObservations)
  x = list(hmm = hmm, sim = sim, vit = vit, posterior = posterior)
  readline("Plot simulated throws:\n")
  mn = "Fair and unfair die"
  xlb = "Throw nr."
  ylb = ""
  plot(x$sim$observation, ylim = c(-7.5, 6), pch = 3, main = mn, 
      xlab = xlb, ylab = ylb, bty = "n", yaxt = "n")
  axis(2, at = 1:6)
  readline("Simulated, which die was used:\n")
  text(0, -1.2, adj = 0, cex = 0.8, col = "black", "True: green = fair die")
  for (i in 1:nSim) {
      if (x$sim$states[i] == "Fair") 
          rect(i, -1, i + 1, 0, col = "green", border = NA)
      else rect(i, -1, i + 1, 0, col = "red", border = NA)
  }
  readline("Most probable path (viterbi):\n")
  text(0, -3.2, adj = 0, cex = 0.8, col = "black", "Most probable path")
  for (i in 1:nSim) {
      if (x$vit[i] == "Fair") 
          rect(i, -3, i + 1, -2, col = "green", border = NA)
      else rect(i, -3, i + 1, -2, col = "red", border = NA)
  }
  readline("Differences:\n")
  text(0, -5.2, adj = 0, cex = 0.8, col = "black", "Difference")
  differing = !(x$sim$states == x$vit)
  for (i in 1:nSim) {
      if (differing[i]) 
          rect(i, -5, i + 1, -4, col = rgb(0.3, 0.3, 0.3), 
              border = NA)
      else rect(i, -5, i + 1, -4, col = rgb(0.9, 0.9, 0.9), 
          border = NA)
  }
  readline("Posterior-probability:\n")
  points(x$posterior[2, ] - 3, type = "l")
  readline("Difference with classification by posterior-probability:\n")
  text(0, -7.2, adj = 0, cex = 0.8, col = "black", "Difference by posterior-probability")
  differing = !(x$sim$states == x$vit)
  for (i in 1:nSim) {
      if (posterior[1, i] > 0.5) {
          if (x$sim$states[i] == "Fair") 
              rect(i, -7, i + 1, -6, col = rgb(0.9, 0.9, 0.9), 
                border = NA)
          else rect(i, -7, i + 1, -6, col = rgb(0.3, 0.3, 0.3), 
              border = NA)
      }
      else {
          if (x$sim$states[i] == "Unfair") 
              rect(i, -7, i + 1, -6, col = rgb(0.9, 0.9, 0.9), 
                border = NA)
          else rect(i, -7, i + 1, -6, col = rgb(0.3, 0.3, 0.3), 
              border = NA)
      }
  }
  readline("Difference with classification by posterior-probability > .95:\n")
  text(0, -7.2, adj = 0, cex = 0.8, col = "black", "Difference by posterior-probability > .95")
  differing = !(x$sim$states == x$vit)
  for (i in 1:nSim) {
      if (posterior[2, i] > 0.95 || posterior[2, i] < 0.05) {
          if (differing[i]) 
              rect(i, -7, i + 1, -6, col = rgb(0.3, 0.3, 0.3), 
                border = NA)
          else rect(i, -7, i + 1, -6, col = rgb(0.9, 0.9, 0.9), 
              border = NA)
      }
      else {
          rect(i, -7, i + 1, -6, col = rgb(0.9, 0.9, 0.9), 
              border = NA)
      }
  }
  invisible(x)
```

## Create MC simulation simulation

```{r mc_simulation}

start_date = '1980-01-01'
states = c('E', 'U', 'N') #E=employed, U=unemployed, N - Not in Labor force 
n = 1000 #number of people

tr_matrix =  tr_matrix_from_params( tr_rates_params)

start_states = as.numeric(df[date==start_date,.(lpart * (1 - 0.01*uer),0.01*lpart * uer, 100-lpart  )])
 
start_states %*% (tr_matrix %^% 30)

rownames(tr_matrix)<-states
colnames(tr_matrix)<-states
#rowSums(tr_matrix)

df_s = df[order(date) & date>=start_date,.(date, E = lpart * (1 - 0.01*uer), U = 0.01*lpart * uer, N = 100-lpart, UER = uer, iuic, iuic_rate  )]

df_s[, t := seq(0, nrow(df_s)-1)]

#ts is time in state
dt_temp =  data.table(id = seq(n), t = 0, ts = 0, state = sample(states, n, replace = TRUE, prob = c(59.9680, 4.0320, 36.0) ) )

do_sim <- function(steps = 240, dt_in, tr_rates_params){
#df_sim = foreach (i = seq(nrow(df_s)-1), .combine = rbind) %do% {
df_sim = foreach (i = seq(steps), .combine = rbind) %do% {
    cur_states = dt_in[,state]
    ts = dt_in[,ts]
    
    tr_matrix =  tr_matrix_from_params( c(logit(tr_rates_params[1]*df_s$iuic_rate[i]), tr_rates_params[-1]) )
    
    for (j in 1:nrow(dt_in)){
      c_state = cur_states[j]
      probs = tr_matrix[which(states == c_state),]
      n_state = states[which(cumsum(probs) >= runif(1))[1]]
      ts[j] = ifelse(n_state == c_state, ts[j] + 1, 0)
      cur_states[j] = n_state
    }
    #data.table(cur_states, s = dt_temp$state, ts)[cur_states != s]
   res = data.table(id = dt_in$id, t = i, ts, state = cur_states)
   dt_in = res
   return(res)
}
return (df_sim)
}

df_sim = do_sim(240, dt_temp, tr_rates_params)

df_agg = df_sim[, .(.N, ts = mean(ts)), by = .(t, state)]

ggplot(dcast(df_agg, t ~ state, value.var = 'N'), aes(t, 100*U/(E+U))) + geom_line() +
  geom_line(data = df_s, aes(t, UER), color = 'red')

ggplot(dcast(df_agg, t ~ state, value.var = 'N'), aes(t, U)) + geom_line() 

ggplot(dcast(df_agg, t ~ state, value.var = 'ts'), aes(t, U)) + geom_line()
ggplot(dcast(df_agg, t ~ state, value.var = 'ts'), aes(t, E)) + geom_line()


obj_fun_mc <-function(tr_rates_params){
  set.seed(123456)
  df_sim = do_sim(240, dt_temp, tr_rates_params)
  
  df_agg = df_sim[, .(.N, ts = mean(ts)), by = .(t, state)]
  
  temp = dcast(df_agg, t ~ state, value.var = 'N')
  temp[, uer_rate_sim := 100*U/(E+U)]
  temp[df_s, uer_act := i.UER, on =.(t)]
  
  temp[, sum( (uer_rate_sim - uer_act)^2 )]
 
  return ( temp[, sum( (uer_rate_sim - uer_act)^2 )] )
} 

tr_rates_params_mc = c(0.1,  -5.609309, -11.569209, -14.547898,  -5.065347, -14.862557)#static monthly params
res = optim(tr_rates_params_mc, obj_fun_mc, method = 'L-BFGS', control = list(trace = TRUE))
#res = optim(tr_rates, obj_fun, method = 'Nelder-Mead', control = list(trace = TRUE, maxit =  500))

```

