---
title: "Random Search"
author: "Alex"
date: "December 26, 2018"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE, fig.width = 8, fig.height = 5, dpi = 240)
options(warn=-1)

library(data.table)
library(plyr)
library(stringi)
library(stringr)
library(ggplot2)
library(gridExtra)
library(zip)
library(sfsmisc) #for prime
library(deldir)

library(GA)
library(TSP)

library(foreach)
library(microbenchmark)

#working_folder = 'C:/Dev/Kaggle/'
working_folder = 'F:/Github/KaggleSandbox'
#working_folder = file.path(Sys.getenv("HOME"), 'source/github/KaggleSandbox/')


source(file.path(working_folder, '/Utils/common.R'))
```

## Load

```{r data}
 df_all = fread(file.path(working_folder,'Santa/data/cities.csv'), check.names=T)

 setorder(df_all, CityId)

 prime_ids = primes(max(df_all$CityId))

 df_all[,not_prime:=as.numeric(!(CityId %in% prime_ids))]
 
 #fwrite(df_all, file.path(working_folder,'Santa/data/cities.100.csv'))
 
 #df = df_all[1:1001,] #for debugging
 df = df_all
```

## Utils

```{r utils, echo=FALSE}
extra_dist = as.numeric(seq(nrow(df)) %% 10 == 0)

eval_path<-function(nodes, path){
  
  if(path[1] == 0)
    path_ids = c(path, 0) + 1
  else
    path_ids = c(0, path, 0) + 1
  
  x_c = nodes$X[path_ids]
  y_c = nodes$Y[path_ids]
  p_c = nodes$not_prime[path_ids[-length(path_ids)]] #exclude last
  
  dx = diff(x_c)
  dy = diff(y_c)
  
  dist = sum( sqrt(dx * dx + dy * dy) * (1.0 + 0.1 * extra_dist * p_c ) )
  
  return( dist )
}
```

```{r utils, echo=FALSE}

starting_tour = fread(file.path(working_folder, "Santa/data/cpp.solution.tour.txt"),         header = FALSE)$V1
starting_tour = fread(file.path(working_folder, "Santa/data/cpp.solution.tour.1516669.txt"), header = TRUE)$Path

starting_dist = eval_path(df, starting_tour)

starting_dist/1516669.487072

ggplot(cbind(df[starting_tour[1:20000]+1,],segment=factor(floor(seq(length(starting_tour)) / 10000)) ), aes(X, Y, color = segment)) + 
  geom_path() + 
  geom_point(data = df[1,], aes(X, Y), color = 'red')

#compute triangulation
#dxy1 = deldir(df$X, df$Y, plotit = FALSE)
#saveRDS(dxy1, file.path(working_folder, "Santa/data/voronoi.Rds"))
#nn_index = dxy1[['delsgs']][,c('ind1', 'ind2')]
#n_len = sqrt( (df$X[nn_index$ind1] - df$X[nn_index$ind2])^2 + (df$X[nn_index$ind1] - df$X[nn_index$ind2])^2 )
#mean(n_len)
#vor_time = ldply(1000*seq(20), function(i) {
#  pindex = sample.int(nrow(df), i)
#  data.frame(i, elapsed = system.time(deldir(df$X[pindex], df$Y[pindex], plotit = FALSE))[3])})
#ggplot(vor_time, aes(i, elapsed)) + geom_line() +  geom_point()
#timing_fit = lm(elapsed ~ I(i*i), vor_time)
#summary(timing_fit)
#predict(timing_fit, newdata = data.frame(i = 190000))/60

#to choose two cities on the tour randomly, and then reverse the portion of the tour that lies between them
random_tour_1 <- function(tour)
{
  m_tour <- tour
  n <- length(tour)
  m <- sort(1+sample.int(n-2, size = 2))
  i = m[1]
  j = m[2]
  m_tour[i:j] <- rev(tour[i:j])
  return(m_tour)
}

#to choose two cities on the tour randomly, and then swap them
#not a complete shuffle
random_tour_2 <- function(tour)
{
  m_tour <- tour
  n <- length(tour)
  m <- 1+sample.int(n-2, size = 2)#[2, n-1]
  i = m[1]
  j = m[2]
  m_tour[i] <- tour[j]
  m_tour[j] <- tour[i]
  return(m_tour)
}

#to choose one city on the tour randomly, and move its position
random_tour_3 <- function(tour)
{
  n <- length(tour)
  m <- 1+sample.int(n-2, size = 2) #[2, n-1]
  i = m[1] #i moved to j position
  j = m[2]
  
  m_tour <- append(tour[-i],tour[i], after = ifelse(i<j, j-2, j-1) ) 
  
  return(m_tour)
}

#move random section 
random_tour_4 <- function(tour)
{
  n <- length(tour)
  m <- sort(1+sample.int(n-2, size = 2)) #[2, n-1]
  sec_len = 1 + m[2]- m[1]
  
  ms = sample.int(n-sec_len-1, size = 1)
  node_id = m[1]:m[2]
  m_tour <- append(tour[-node_id],tour[node_id], after = ms ) 
  
  return(m_tour)
}


```


```{r utils, echo=FALSE}

maxit = 10000

#r_tour = starting_tour

shifters = c('random_tour_1', 'random_tour_2', 'random_tour_3', 'random_tour_4')

best_len =  eval_path(df, starting_tour)
r_tour = starting_tour
for(i in seq(maxit)){
  
  shift_fun = sample(shifters, 1)
  r_tour_next = do.call(shift_fun, list(r_tour))
  
  r_tour_next_len   = eval_path(df,   r_tour_next)
  
  if(r_tour_next_len<best_len){
    print(sprintf('%6d: %f %f %s', i, best_len, r_tour_next_len, shift_fun))
    best_len = r_tour_next_len
    r_tour = r_tour_next
  }
}
print( best_len - starting_dist )
```

## Estimate variance
```{r estimate_variance, echo=FALSE}

curr_len =  eval_path(df, starting_tour)

res = ldply(seq(256), function(i){
  scale = 0.01
  
  df_t = data.frame(X = df$X + scale*rnorm(nrow(df)), 
                    Y = df$Y + scale*rnorm(nrow(df)), 
                    not_prime = df$not_prime )
  
  data.frame(i, scale , dist = eval_path(df_t, starting_tour))
  })
 
ggplot(res, aes(dist)) + geom_density(adjust = 0.2) + geom_vline(xintercept = curr_len) 
  
```
