---
title: "Santa"
author: "Alex"
date: "November 21, 2018"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE, fig.width = 8, fig.height = 5, dpi = 240)
options(warn=-1)

library(data.table)
library(plyr)
library(stringi)
library(stringr)
library(ggplot2)
library(gridExtra)
library(zip)
library(sfsmisc) #for prime

library(GA)
library(TSP)

library(foreach)
library(microbenchmark)

#working_folder = 'C:/Dev/Kaggle/'
#working_folder = 'F:/Github/KaggleSandbox'
working_folder = file.path(Sys.getenv("HOME"), 'source/github/KaggleSandbox/')


source(file.path(working_folder, '/Utils/common.R'))

```

## Load Data
197769 - nodes

```{r load_data}
 
 df_all = fread(file.path(working_folder,'Santa/data/cities.csv'), check.names=T)

 setorder(df_all, CityId)

 prime_ids = primes(max(df_all$CityId))

 df_all[,not_prime:=as.numeric(!(CityId %in% prime_ids))]
 
 #fwrite(df_all, file.path(working_folder,'Santa/data/cities.100.csv'))
 
 #df = df_all[1:1001,] #for debugging
 df = df_all
 
 #fwrite(df, file.path(working_folder,'Santa/data/cities.1k.csv'))
 
```

## Utils

```{r eval_utils, echo=FALSE}
extra_dist = as.numeric(seq(nrow(df)) %% 10 == 0)

eval_path<-function(path){
  
  if(path[1] == 0)
    path_ids = c(path, 0) + 1
  else
    path_ids = c(0, path, 0) + 1
  
  x_c = df$X[path_ids]
  y_c = df$Y[path_ids]
  p_c = df$not_prime[path_ids[-length(path_ids)]] #exclude last
  
  dx = diff(x_c)
  dy = diff(y_c)
  
  dist = sum( sqrt(dx * dx + dy * dy) * (1.0 + 0.1 * extra_dist * p_c ) )
  
  return( dist )
}

eval_path_s<-function(path){
  
  if(path[1] == 0)
    path_ids = c(path, 0) + 1
  else
    path_ids = c(0, path, 0) + 1
  
  x_c = df$X[path_ids]
  y_c = df$Y[path_ids]
  p_c1 = df$not_prime[path_ids[-length(path_ids)]] #exclude last
  p_c2 = df$not_prime[path_ids[-1]] #exclude first
  
  dx = diff(x_c)
  dy = diff(y_c)
  
  dist = sum( floor(0.5+sqrt(dx * dx + dy * dy) * (1.0 + 0.005 * (p_c1 + p_c2) )) )
  
  return( dist )
}

save_tour <- function(tour, filename){
  df_s = data.table(Path=c(0, tour, 0))
  file = file.path(working_folder, stri_join("santa/", filename) )
  fwrite(df_s, file = file, row.names = FALSE)
}

path = df$CityId

eval_path(path) #446884408

#microbenchmark(eval_path(path))
 
```

## TSP Solution: Linkern

```{r tsp_solultion, echo=FALSE, eval = FALSE}
concorde_path(file.path(Sys.getenv("HOME"), 'source/cpp/concorde/bin'))
#linkern_help()
#concorde_help()

#image(tsp)
#plot(tsp)

#write_TSPLIB(tsp, file.path(working_folder,'Santa/data/data.tsp'), precision = 14)

#tour <- solve_TSP(tsp, method = "concorde")
library(doMC)
registerDoMC(4)

foreach(i = 1:1000)%dopar%{
  
  starting_cycle = sample(c(3,4), 1)
  noise = 0#sample(c(0, 0.01), 1)
  number_of_kicks = nrow(df)*sample(10:100, 1)
  scale=sample(c(100, 1000), 1)
  
  tsp <- ETSP(data.frame(x=scale*(df$X+noise*rnorm(nrow(df))), y = scale*(df$Y+noise*rnorm(nrow(df))), row.names = df$CityI))

  tour <- solve_TSP(tsp, method = "linkern", control = list(clo = sprintf("-Q -I %d -R %d", starting_cycle, number_of_kicks)), precision = 16) #-r number of runs

  tsp_solution = as.numeric(tour)
  
  index1 = which(tsp_solution==1)[1]
  if(index1 == 1 | index1 == length(tsp_solution)){
    tsp_path = tsp_solution[-index1] - 1
  }else{
    tsp_path = c(tsp_solution[(index1+1):length(tsp_solution)], tsp_solution[1:(index1-1)])-1
  }
  current_distance = eval_path(tsp_path)
  print( sprintf('it %d: %f (%f)', i, current_distance, tour_length(tour)) ) # -13020.02 
  
  file = file.path(working_folder, sprintf("Santa/tours/linkern_%d_%d_%d_%d_%d_%d_%d_.csv",round(current_distance),
                                           round(tour_length(tour)), i, starting_cycle, noise, number_of_kicks, scale ))
    fwrite(data.table(tsp_path = c(0, tsp_path), tsp_solution), file = file, row.names = FALSE)
}

```


## TSP Solution: Concorde

```{r tsp_solultion_concorde, echo=FALSE, eval = FALSE}
concorde_path(file.path(Sys.getenv("HOME"), 'source/cpp/concorde/bin'))
#linkern_help()
#concorde_help()

tsp <- ETSP(data.frame(x=df$X, y = df$Y, row.names = df$CityI))
n_of_cities(tsp)
#image(tsp)
#plot(tsp)

current_best = 1523816

#write_TSPLIB(tsp, file.path(working_folder,'Santa/data/data.tsp'))

#tour <- solve_TSP(tsp, method = "concorde")
library(doMC)
registerDoMC(2)

foreach(i = 1:100)%dopar%{
  tour <- solve_TSP(tsp, method = "concorde", control = list(clo = "")) #-r number of runs

  tsp_solution = as.numeric(tour)
  
  index1 = which(tsp_solution==1)[1]
  if(index1 == 1 | index1 == length(tsp_solution)){
    tsp_path = tsp_solution[-index1] - 1
  }else{
    tsp_path = c(tsp_solution[(index1+1):length(tsp_solution)], tsp_solution[1:(index1-1)])-1
  }
  current_distance = eval_path(tsp_path)
  print( sprintf('it %d: %f (%f)', i, current_distance, tour_length(tour)) ) # -13020.02 
  
    file = file.path(working_folder, sprintf("Santa/tours/concorde.%d.%d.csv",round(current_distance), round(tour_length(tour)) ))
    fwrite(data.table(tsp_path = c(0, tsp_path), tsp_solution), file = file, row.names = FALSE)
}

```

## Eval tours

```{r eval_rours, echo=FALSE, eval = FALSE}
filename = file.path(working_folder, "Santa/data/linkern1.tour")

df_c = fread(filename, header = FALSE)

concorde_tour = df_c$V1

eval_path(concorde_tour)
```

## Load multiple tours 
```{r all_eval_tours, echo=FALSE, eval = FALSE}
files = list.files( file.path(working_folder, "Santa/tours/"), pattern = '^linkern.*csv$',  full.names = TRUE)

res = ldply(files, function(fname) {
  df_c = fread(fname, header = TRUE)
  linkern_tour = c(df_c$tsp_path, 0)
  data.table(name = basename(fname), len = eval_path(linkern_tour), time=file.mtime(fname) )
})

ggplot(res, aes(time, len)) + geom_line() + geom_point() + 
  geom_hline(yintercept = 1516928.19, color = 'red')

#i(4), starting_cycle(5), noise(6), number_of_kicks(7) 
tokens = stri_split(basename(files), fixed = '.', simplify = TRUE)
#starting_cycle = 3, 
df_len = data.frame(t_len = as.numeric(tokens[,2]), 
                    c_len = as.numeric(tokens[,3]),
                    r_id  = as.numeric(tokens[,4]),
                    s_cyc = as.numeric(tokens[,5]),
                    noise = as.numeric(tokens[,6]),
                    kicks = as.numeric(tokens[,7])/nrow(df),
                    scale = as.numeric(tokens[,8]))

ggplot(df_len, aes(kicks, t_len, color = factor(s_cyc) )) + 
  geom_point(alpha = 0.7) + 
  geom_hline(yintercept = 1516928.19, color = 'red', linetype = 'dashed') + facet_wrap(~scale)

summary(lm(t_len ~ s_cyc + kicks + scale, df_len))
  
```

## Load a single linkern tour

```{r eval_rours, echo=FALSE, eval = FALSE}
filename = file.path(working_folder, "Santa/tours/linkern.1516928.150329210.1.4.0.15228213.100.csv")

df_c = fread(filename, header = TRUE)

linkern_tour = c(df_c$tsp_path, 0)

eval_path(linkern_tour)
```

## MC Adjust tour

```{r mc_adjust_tours, echo=FALSE, eval = FALSE}
mutate_tour <- function(tour)
{
  #to choose two cities on the tour randomly, and then reverse the portion of the tour that lies between them
  m_tour <- tour
  n <- length(tour)
  m <- sort(sample.int(n, size = 2))
  i = m[1]
  j = m[2]
  m_tour[i:j] <- rev(tour[i:j])
  return(m_tour)
}

filename = file.path(working_folder, "Santa/tours/linkern.1523759.1510046.8.csv")

df_c = fread(filename, header = TRUE)

linkern_tour = df_c$tsp_path[-1]

dist0   = eval_path(linkern_tour)
dist0_s = eval_path_s(linkern_tour)

res= ldply(seq(1000), function(i){
  m_tour = mutate_tour(linkern_tour)
  
  data.table(i, diff = eval_path(m_tour)-dist0, diff_s = eval_path_s(m_tour) - dist0_s)
  
})

ggplot(res, aes(i, diff - diff_s - dist0_s + dist0)) + geom_point()

ggplot(res, aes(diff_s, diff)) + geom_point() + geom_abline(slope = 1, color = 'red')

summary(lm(diff ~ diff_s, res))

```

## Check CPP

```{r eval_rours, echo=FALSE, eval = FALSE}

df_c = fread(file.path(working_folder, "Santa/out.txt"), header = FALSE, skip = 9, sep = ',', 
             nrows = 2e6, colClasses = c('character', 'character', 'numeric', 'numeric', 'numeric'))

df_c[, V1:=as.numeric(sub('.', '', V1, fixed = TRUE)) ]
df_c[, V2:=as.numeric(sub('.', '', V2, fixed = TRUE)) ]

id1 = df_c$V1+1
id2 = df_c$V2+1
dx  = df$X[id1] - df$X[id2]
dy  = df$Y[id1] - df$Y[id2]
p1_c = 1-df$not_prime[id1] 
p2_c = 1-df$not_prime[id2]

df_c[, tp1 :=  p1_c]
df_c[, tp2 :=  p2_c]
df_c[, tdist :=  sqrt(dx*dx + dy * dy) * (1.0 + 0.005 * (2 - (tp1+tp2))) ]
df_c[, diff := V5 - tdist] 
sd(df_c$tdist - df_c$V5)
sd(df_c$V3 - df_c$tp1)
sd(df_c$V4 - df_c$tp2)
df_c[order(diff), ] 


eval_path_simple()

linkern_tour = c(df_c$tsp_path, 0)

eval_path(linkern_tour)
```

## Load a single concorde tour

```{r eval_rours, echo=FALSE, eval = FALSE}
filename = file.path(working_folder, "Santa/data/concorde.tour")
  
concorde_tour = scan(filename, sep = ' ')
concorde_tour = concorde_tour[!is.na(concorde_tour)]
concorde_tour = concorde_tour[-1]

concorde_tour = c(concorde_tour, 0)

eval_path(concorde_tour)
```


## Submit
Best solutions
             1514413.37 (kaggle best)
CurrentBest: 1516928.19

```{r submit, echo=FALSE}
check_tour<-function(tour){
  n = length(tour) 
  return( tour[1] == 0 & tour[n] == 0 & n == (nrow(df) + 1) & all(diff(sort(tour))[-1]==1) )
}

options(scipen = 999) # to save integers

#save_tour = concorde_tour
save_tour = linkern_tour
#save_tour = c(0, tsp_path-1)

df_s = data.table(Path=as.character(save_tour))

eval_path(as.numeric(save_tour) )
check_tour(as.numeric(save_tour))

file = file.path(working_folder, "Santa/solution.csv")
  
fwrite(df_s, file = file, row.names = FALSE)

zip(paste(file, '.zip', sep = ''), file)
  
print(file)

```




