---
title: "Santa"
author: "Alex"
date: "November 21, 2018"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE, fig.width = 8, fig.height = 5, dpi = 240)
options(warn=-1)

library(data.table)
library(plyr)
library(stringi)
library(stringr)
library(ggplot2)
library(gridExtra)
library(zip)
library(sfsmisc) #for prime

library(GA)
library(TSP)

library(foreach)
library(microbenchmark)

#working_folder = 'C:/Dev/Kaggle/'
working_folder = 'F:/Github/KaggleSandbox'

source(file.path(working_folder, '/Utils/common.R'))

```

## Load Data
197769 - nodes

```{r load_data}
 
 df_all = fread(file.path(working_folder,'Santa/data/cities.csv'), check.names=T)

 setorder(df_all, CityId)

 prime_ids = primes(max(df_all$CityId))

 df_all[,not_prime:=as.numeric(!(CityId %in% prime_ids))]
 
 #df = df_all[1:1001,] #for debugging
 df = df_all
 
```

## Utils

```{r eval_utils, echo=FALSE}
extra_dist = as.numeric(seq(nrow(df)) %% 10 == 0)

eval_path_ga<-function(path){
  path_ids = c(0, path, 0) + 1
  
  x_c = df$X[path_ids]
  y_c = df$Y[path_ids]
  p_c = df$not_prime[path_ids[-length(path_ids)]] #exclude last
  
  dx = diff(x_c)
  dy = diff(y_c)
  
  dist = sum( sqrt(dx * dx + dy * dy) * (1.0 + 0.1 * extra_dist * p_c ) )
  
  return( -dist )
}

save_tour <- function(tour, filename){
  df_s = data.table(Path=c(0, tour, 0))
  file = file.path(working_folder, stri_join("santa/", filename) )
  fwrite(df_s, file = file, row.names = FALSE)
}

path = df$CityId[-1]

eval_path(path) #446884408

microbenchmark(eval_path(path))

ggplot(df[1:4,], aes(X, Y)) + geom_point() + 
  geom_path(aes(X, Y), color = 'red') + 
  geom_point(data =df[1,], aes(X, Y), color = 'blue', size = 2 )

 
```

## TSP Solution
1k  - 85613 - 0.66 sec
10k - 

```{r tsp_solultion, echo=FALSE, eval = FALSE}
#Sys.setenv(PATH = stri_join( Sys.getenv('PATH'), ';C:\\cygwin64\\bin'))
#concorde_path('T:/Utils/Concorde/')
#concorde_help()

tsp <- ETSP(data.frame(x=df$X, y = df$Y, row.names = df$CityI))
n_of_cities(tsp)
#image(tsp)
#plot(tsp)

#write_TSPLIB(tsp, file.path(working_folder,'Santa/data/data.tsp'))

#check all methods
if(FALSE) {
  methods <- c("identity", "random", "nearest_insertion",
    "cheapest_insertion", "farthest_insertion", "arbitrary_insertion",
    "nn", "repetitive_nn", "two_opt")
  tours <- lapply(methods, FUN = function(m) solve_TSP(tsp, method = m))
  names(tours) <- methods
  #farthest_insertion - is the best on 1k
}

#tour <- solve_TSP(tsp, method = "concorde") 

tour <- solve_TSP(tsp) 
tour_length(tour)

plot(tsp, tour, tour_col = "red")

tsp_solution = as.numeric(tour)

index1 = which(tsp_solution==1)[1]
if(index1 == 1 | index1 == length(tsp_solution)){
  tsp_path = tsp_solution[-index1]
}else{
  tsp_path = c(tsp_solution[(index1+1):length(tsp_solution)], tsp_solution[1:(index1-1)])-1
}
sprintf('best: %f', eval_path(tsp_path)) # -13020.02 


if(nrow(df)<10000){
ggplot(df, aes(X, Y)) + geom_point() + 
  geom_path(data =df[c(0, tsp_path,0)+1,], aes(X, Y), color = 'red') + 
  geom_point(data =df[1,], aes(X, Y), color = 'blue', size = 2 )
}
saveRDS(tsp_path, file.path(working_folder,'Santa/data/tsp_path.rds'))

```


##Load tours
```{r load_tours, echo=FALSE, eval = FALSE}

tour_files = list.files(file.path(working_folder, "santa/tours/"), pattern = 'solution*', full.names = TRUE)

tours = foreach(i=1:length(tour_files), .combine=cbind ) %do% {
  tour_df = fread(tour_files[i])
  return(tour_df)
}

for (i in seq(ncol(tours))) {
print(eval_path(t(as.matrix(tours[2:nrow(tours),]))[i,] ) )
}

```


## GA solution
```{r ga_solultion, echo=FALSE, eval = FALSE}

best_solution = 1516840.8073343499563634

mutate_tour <- function(object, parent)
{
  #to choose two cities on the tour randomly, and then reverse the portion of the tour that lies between them
  mutate <- parent <- as.vector(object@population[parent,])
  n <- length(parent)
  m <- sort(sample.int(n, size = 2))
  i = m[1]
  j = m[2]
  mutate[i:j] <- rev(parent[i:j])
  return(mutate)
}

mutate_tour_ex <- function(object, parent, mut_pct = 0.01)
{
  #to choose two cities on the tour randomly (at most 0.01% of nodes), and then reverse the portion of the tour that lies between them
  mutate <- parent <- as.vector(object@population[parent,])
  n <- length(parent)
  nw = min(n, max(3, mut_pct*n)) 
  i1 = 1+floor(n*runif(1))   #between 1 and n 
  offset = floor((2*nw + 1)*runif(1)) - nw  #between -nw and +nw
  j1 = max(1, min(n, i1+offset)) #between 1 and n
  i = min(i1, j1)
  j = max(i1, j1)
  mutate[i:j] <- rev(parent[i:j])
  return(mutate)
}

solution_file = file.path(working_folder,'Santa/data/population.all.rds')

suggestedSol = NULL
popSize = 100

if( file.exists(solution_file) ){
  suggestedSol = readRDS(solution_file)
}else{
  #temp = t(as.matrix(tours[2:nrow(tours),]))
  #suggestedSol = temp[ sample.int(nrow(temp),popSize, replace = TRUE), ]
  suggestedSol = t(as.matrix(tours[2:nrow(tours),]))
}

#sapply(seq(nrow(suggestedSol)), function(i)eval_path_ga(suggestedSol[i,]))

#sum(is.na(suggestedSol))
#suggestedSol[1:5,c(1:10,ncol(suggestedSol)) ]

res = ga(type = c( "permutation"), eval_path_ga, 
   names = as.character(df$CityId[-1]),
   lower = 1, upper = max(df$CityId),
   maxiter = 1000,
   popSize = popSize,
   pcrossover = 0.0,
   pmutation = 0.80,
   mutation = mutate_tour,
   monitor = TRUE,
   #mutation = function(object, parent) {mutate_tour_ex(object, parent, mut_pct = 0.1)},
   suggestions = suggestedSol)

saveRDS(res@population, file.path(working_folder,'Santa/data/population.all.rds'))

#head(res@population)
#sapply(seq(nrow(res@population)), function(i)eval_path_ga(res@population[i,]))

summary(res)
   
plot(res)

ggplot(data.frame(fitness = -sort(res@fitness)), aes(seq(length(fitness)), fitness)) + geom_point() + 
  geom_hline(yintercept = best_solution, color = 'red')

ga_solution = as.numeric(res@solution)

sprintf('improved: %e', eval_path(ga_solution)-best_solution) # current best 1516841
#sprintf('best: %f', eval_path_ga(ga_solution)) # 

if(nrow(df)<10000){
ggplot(df, aes(X, Y)) + geom_point() + 
  geom_path(data =df[c(0, ga_solution,0)+1,], aes(X, Y), color = 'red') + 
  geom_point(data =df[1,], aes(X, Y), color = 'blue', size = 2 )
}

```

## Iterative GA solution
```{r it_ga_solultion, echo=FALSE, eval = FALSE}

mutate_tour <- function(object, parent)
{
  #to choose two cities on the tour randomly, and then reverse the portion of the tour that lies between them
  mutate <- parent <- as.vector(object@population[parent,])
  n <- length(parent)
  m <- sort(sample.int(n, size = 2))
  i = m[1]
  j = m[2]
  mutate[i:j] <- rev(parent[i:j])
  return(mutate)
}

plot_list = list()

suggestedSol = NULL

for(i in seq(3, 100)) {

  df_part = df[1:i,]
  
  if(!is.null(suggestedSol))
  {
    #add new city df_part$CityId[i]
    
    #find closest city
    di = (df_part$X[-i] - df_part$X[i])**2 +  (df_part$Y[-i] - df_part$Y[i])**2
    close_city_id = df_part$CityId[ which(di==min(di))[1] ]
    
    temp = matrix(nrow=nrow(suggestedSol), ncol = ncol(suggestedSol)+1)
    #insert new city right after close match 
    for(k in seq(nrow(suggestedSol))){
      if(close_city_id==0){
        temp[k,] = c(suggestedSol[k,], df_part$CityId[i]) #insert at the end
      }else{
        insert_index = which(suggestedSol[k,] == close_city_id)
        temp[k,] = append(suggestedSol[k,], df_part$CityId[i], after = insert_index)
      }
    }
    suggestedSol = temp
    
  }
  
  res = ga(type = c( "permutation"), eval_path, 
     names = as.character(df_part$CityId[-1]),
     lower = 1, upper = max(df_part$CityId),
     maxiter = 100,
     popSize = min(50, exp(lfactorial(nrow(df_part)-1))) ,
     pcrossover = 0.0,
     pmutation = 0.8,
     mutation = mutate_tour,
     monitor = FALSE,
     #mutation = function(object, parent) {mutate_tour_ex(object, parent, mut_pct = 0.1)},
     suggestions = suggestedSol)
  
  #head(res@population)
  suggestedSol = res@population
  
  #summary(res)
     
  #plot(res)
  
  #plot(res@fitness)
  
  ga_solution = as.numeric(res@solution)
  
  print(sprintf('best: %d, %f', i, eval_path(ga_solution))) # -13020.02 
  #plot_list[[paste(i)]] = p
  
  write.csv(data.frame(Path = c(0,ga_solution,0)), 
            file.path(working_folder,sprintf('Santa/data/ga.it.solution.%d.csv', i)),
            row.names = FALSE, quote= FALSE)
}

ggplot(df_part, aes(X, Y)) + geom_point() + 
geom_path(data =df_part[c(0, ga_solution,0)+1,], aes(X, Y), color = 'red') + 
geom_point(data =df_part[1,], aes(X, Y), color = 'blue', size = 2 )



```


```{r cpp_solultion, echo=FALSE, eval = FALSE}

cpp_tour = read.csv(file.path(working_folder,'Santa/data/cpp.solution.tour.100.txt'), header = FALSE)

ggplot(df[cpp_tour$V1+1,], aes(X, Y)) + geom_point() + 
  geom_path(data =df[cpp_tour$V1+1,], aes(X, Y), color = 'red') + 
  geom_point(data =df[1,], aes(X, Y), color = 'blue', size = 2 )

eval_path(cpp_tour$V1[2:(nrow(cpp_tour)-1)])

```

```{r concorde_solultion, echo=FALSE, eval = FALSE}

con_tour = read.csv(file.path(working_folder,'Santa/data/concorde_tour.100.txt'), header = FALSE)
if(nrow(df)<10000){
ggplot(df, aes(X, Y)) + geom_point() + 
  geom_path(data =df[c(con_tour$V1,0)+1,], aes(X, Y), color = 'red') + 
  geom_point(data =df[1,], aes(X, Y), color = 'blue', size = 2 )
}

eval_path(con_tour$V1[2:(nrow(con_tour))])

```

## GA parametric
optimal for 100 params
pcrossover = 0
mutation = 0.8
popSize = 50

elapsed_time
(Intercept) -3.451531   0.238406 -14.478  < 2e-16 ***
p_size       0.040634   0.002870  14.158  < 2e-16 ***
p_mut        2.027431   0.226900   8.935 2.29e-12 ***
max_it       0.009696   0.000393  24.671  < 2e-16 ***

```{r ga_params, echo=FALSE, eval = FALSE}

params = expand.grid(p_size = c(100), 
                     max_it = c(1000),
                     p_cross = c(0), 
                     p_mut = seq(0.2, 1.0, by = 0.2),
                     mut_pct = c(0.001, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6))
#params = expand.grid(p_size = seq(10, 100, 10), p_cross = c(0, 0.1), p_mut = c(0,0.1))

hres = ldply(seq(nrow(params)), function(i) {
  
  print(i)
  
start_time <- Sys.time()
  
 res = ga(type = c( "permutation"), eval_path, 
   names = as.character(df$CityId[-1]),
   lower = 1, upper = max(df$CityId),
   maxiter = params$max_it[i],
   popSize = params$p_size[i],
   pcrossover =  params$p_cross[i],
   pmutation = params$p_mut[i],
   mutation = function(object, parent) {mutate_tour_ex(object, parent, mut_pct = params$mut_pct[i])},
   #suggestions = NULL,
   suggestions = suggestedSol,
   monitor = FALSE,
   seed = 1234345)
 
 elapsed_time = as.numeric(Sys.time() - start_time)
 
 return( cbind(data.frame(i, tour = eval_path(as.numeric(res@solution)), elapsed_time ),params[i,] ))
})
setDT(hres)

#ggplot(hres, aes(p_cross, -tour, group = p_mut, color = factor(p_mut) )) + geom_line() + facet_wrap(~p_size)
ggplot(hres, aes(p_mut, -tour, group = p_size, color = factor(p_size) )) + geom_line() + facet_wrap(mut_pct~max_it)
ggplot(hres, aes(p_mut, elapsed_time, group = p_size, color = factor(p_size) )) + geom_line() + facet_wrap(mut_pct~max_it)

ggplot(hres, aes(p_mut, -tour+max(tour), group = mut_pct, color = factor(mut_pct) )) + 
  geom_line() + geom_point() + facet_wrap(~mut_pct)


summary( lm(elapsed_time ~ p_size + p_mut + max_it, hres) )
```

## Submit
Best solutions
Lin : 1526444.36


```{r submit, echo=FALSE}

df_s = data.table(Path=c(0, ga_solution, 0))

file = file.path(working_folder, "santa/solution.csv")
  
fwrite(df_s, file = file, row.names = FALSE)

zip(paste(file, '.zip', sep = ''), file)
  
print(file)

```

## Eval tours

```{r eval_rours, echo=FALSE, eval = FALSE}

filename = file.path(working_folder, "santa/data/concorde_tour.lin.sub.csv")
  
df_s = fread(filename)

eval_path(df_s$Path[2:(nrow(df_s)-1)])

```




