---
title: "Clicks"
author: "Alex"
date: "March 8, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE, fig.width = 8, fig.height = 5, dpi = 240)
options(warn=-1)

#library(reshape2)
library(ggplot2)
#library(Hmisc)
library(plyr)
library(gridExtra)

library(gbm)
#library(randomForest)
#library(nnet)
#library(e1071)
#library(MASS)
library(corrplot)
library(data.table)
library(lubridate)
library(stringi)
library(zip)
```

## Loand Data

```{r data_load}

# READ DATA ---- 

random_seed = 12345678

working_folder = 'C:/Dev/Kaggle/'
#working_folder = file.path(Sys.getenv("HOME"), 'source/github/KaggleSandbox/')

source(file.path(working_folder, 'Utils/common.R'))

train <- fread(file.path(working_folder,'Clicks/data/train.csv'), check.names = TRUE)
test  <- fread(file.path(working_folder,'Clicks/data/test.csv'),  check.names = TRUE) # 1459   80
gc(reset=TRUE)

#outcome based sampling
set.seed(random_seed)

n_events = sum(train$is_attributed != 0)
n_non_events = sum(train$is_attributed == 0)

n_total = length(train$is_attributed)
non_event_sample_size = min(4*n_events,n_non_events)
sample_size = non_event_sample_size + n_events

non_event_sample = sample.int(n_non_events,non_event_sample_size,replace = FALSE)
sampling_correction = log(( sample_size - n_events ) / (n_total - n_events))

train_index_small = train$is_attributed != 0
train_index_small[ which(train$is_attributed==0)[non_event_sample]] = TRUE

train[,.(.N), by = .(is_attributed)]
train[train_index_small,.(.N), by = .(is_attributed)]

print(sprintf('%d (p = %.4f)', n_events, 100*n_events/n_total))

df = train[train_index_small,]
rm(train)

df[, click_time_sec:=second(click_time)]
df[, click_time_min:=minute(click_time)]
df[, click_time_hour:=hour(click_time)]
df[, click_time_day:=day(click_time)]
df[, click_time_hour_ex:=click_time_hour + (click_time_min + click_time_sec/60)/60]
df[, click_time_seconds := as.double(difftime(click_time, min(click_time), unit="secs"))]

test[, click_time_hour:=hour(click_time)]

gc(reset = T)
tables()

```

## View Data
```{r view_data}

table(df[,.(device)])
table(df[,.(os)])
table(df[,.(is_attributed)])

#ggplot(df[,.(.N, p = mean(is_attributed)), by = .(ip)][N>1,], aes(N, p)) + geom_point()

for (vname in c('app', 'channel', 'os','device','ip')) {
  avg = df[,.(.N, p = mean(get('is_attributed'))), by = vname]
  avg = avg[order(p),]
  rare = avg[N<100,][[vname]] #ggplot(avg, aes(log10(N), p)) + geom_point()
  avg[,ex := seq(0, 1, length.out = nrow(avg))]
  df[,   stri_join(vname,'_ex') := avg$ex[match(get(vname),avg[[vname]])] ]
  test[, stri_join(vname,'_ex') := avg$ex[match(get(vname),avg[[vname]])] ]
   
  df[,   stri_join(vname,'_f') := factor(ifelse(get(vname) %in% rare, -1, get(vname))) ]
  test[, stri_join(vname,'_f') := factor(ifelse(get(vname) %in% rare, -1, get(vname))) ]
}
#foo[, "newcol" := lapply(.SD, mean), by = "id", .SDcols = "oldcol"]
#foo[,"newcol":=mean(get("oldcol")), by="id"]

avg_ip = df[,.(.N, p = mean(is_attributed), 
               os_per_ip = length(unique(os)),  
               app_per_ip = length(unique(app)),
               channel_per_ip = length(unique(channel)) ), by = .(ip)]
df[, ip_count     := avg_ip$N[match(ip,avg_ip$ip) ] ]
df[, ip_count_log := log(ip_count+1) ]
df[, ip_prior := avg_ip$p[match(ip,avg_ip$ip)] ]
df[, os_per_ip := avg_ip$os_per_ip[match(ip,avg_ip$ip)] ]
df[, app_per_ip := avg_ip$app_per_ip[match(ip,avg_ip$ip)] ]
df[, channel_per_ip := avg_ip$channel_per_ip[match(ip,avg_ip$ip)] ]


test[, ip_count     := avg_ip$N[match(ip,avg_ip$ip) ] ]
test[, ip_count_log := log(ip_count+1) ]
test[, ip_prior := avg_ip$p[match(ip,avg_ip$ip)]  ]

#check is the same ip can have multiple os, device or channel
#time diff between clicks and ming time difference is not relevant

df_num = df[, sapply(df, is.numeric ), with =F]
corr_matrix = cor(df_num, use="pairwise.complete.obs")
corr_matrix[is.na(corr_matrix)]<-0
corrplot(corr_matrix,method = "circle",  type = "lower",  tl.cex = 0.6, order = "hclust")
#corrplot(corr_matrix, method = "square", tl.cex = 0.4, order = "hclust")

```

## Tune
```{r model_tune, eval = F}

fit_gbm <- function(formula.all, dfs, dfs_out, shrinkage, max_it, depth, bag_pct){
  
  set.seed(random_seed)

  var.monotone = rep(0, length(model_vars))
  
  model.gbm  = gbm(formula.all,
                   distribution = "bernoulli",
                   n.trees = max_it,
                   cv.folds = 4,
                   shrinkage = shrinkage,
                   interaction.depth=depth,
                   train.fraction = 1.0,
                   bag.fraction = bag_pct,# 0.5 for small samples, 0.7 for large
                   n.cores = 2,
                   var.monotone = var.monotone,
                   data = dfs,
                   verbose = FALSE)

  plot_gbmiterations(model.gbm)
  
  pred.gbm = predict(model.gbm, n.trees = best_it.gbm, type = 'response')
  roc = gbm.roc.area(dfs$is_attributed, pred.gbm) 
  
  pred.gbm_out = predict(model.gbm, n.trees = best_it.gbm, newdata = dfs_out, type = 'response')
  roc_out = gbm.roc.area(dfs_out$is_attributed, pred.gbm_out) 
  
  data.frame(it = seq(max_it), depth, bag_pct, shrinkage, max_it,
             best_it = gbm.perf(model.gbm, plot.it = F), 
             train_error =  model.gbm$train.error, 
             cv_error = model.gbm$cv.error,
             roc = roc,
             roc_out = roc_out,
             min_cv_error = min(model.gbm$cv.error))
}


model_vars = c('app_f','channel_f','os_f','device_f', 'ip_ex')

formula.all = formula(stri_join( 'is_attributed ~ ', stri_join(model_vars, collapse = ' + ')))

set.seed(random_seed)
sample_index1 = sample.int(nrow(df), 50000)
sample_index2 = sample.int(nrow(df),100000)
length(intersect(sample_index1, sample_index2))

dfs1 = df[sample_index1, all.vars(formula.all), with =FALSE]
dfs2 = df[sample_index2, all.vars(formula.all), with =FALSE]

params = expand.grid(depth = c(2,3,4,5,6), 
                     shrinkage = c(0.02,0.01), 
                     max_it = 2000, 
                     bag_pct = c(0.9,0.95,1.0))

res = ldply(seq(nrow(params)), function(i){
  p = params[i,]
  res = fit_gbm(formula.all, dfs1, dfs2, p$shrinkage, p$max_it, p$depth, p$bag_pct)
})

#best cv(4): 2, 1.0, 0.02, 500 (depth, bag, shrink, it)
#best auc  : 3, 1.0, 0.02, 300

setDT(res)

ggplot(res[it>100,], aes(it, cv_error, group = shrinkage, color = factor(shrinkage))) + geom_line() + facet_grid(depth ~ bag_pct)

ggplot(res, aes(depth, best_it, group = shrinkage, color = factor(shrinkage))) + 
  geom_line() + geom_point() +  facet_wrap(~bag_pct)

ggplot(res, aes(depth, min_cv_error, group = shrinkage, color = factor(shrinkage))) + 
  geom_line() + geom_point() +  facet_wrap(~bag_pct)

ggplot(res, aes(depth, roc_out, group = shrinkage, color = factor(shrinkage))) + 
  geom_line() + geom_point() +  facet_wrap(~bag_pct)


print( head(res[order(-roc_out),]) )
```

## Model
                            var     rel.inf
app_f                     app_f 84.78566939
ip_ex                     ip_ex  7.73918798
channel_f             channel_f  6.85732206
os_f                       os_f  0.53114889
device_f               device_f  0.06677186
click_time_hour click_time_hour  0.01989983
```{r model}
set.seed(random_seed)

sapply(df[,sapply(df, is.factor ), with =F], function(x) {length(levels(x))})

cv_folds = 0
max_it = 1000

#model_vars = c('app_ex','device_ex','os_ex','channel_ex','ip_prior')
model_vars = c('app_f','channel_f','os_f','device_f', 'ip_ex')

formula.gbm = formula(stri_join( 'is_attributed ~ ', stri_join(model_vars, collapse = ' + ')))

var.monotone = rep(0, length(model_vars))

model.gbm  = gbm(formula.gbm,
                 distribution = "bernoulli",
                 n.trees = max_it,
                 cv.folds = cv_folds,
                 shrinkage = 0.015,
                 interaction.depth=6,
                 train.fraction = 0.7,
                 bag.fraction = 0.9,# 0.5 for small samples, 0.7 for large
                 n.cores = 2,
                 var.monotone = var.monotone,
                 data = df[, all.vars(formula.gbm), with = F],
                 verbose = FALSE)

plot_gbmiterations(model.gbm)

best_it.gbm = ifelse(cv_folds==0, max_it, gbm.perf(model.gbm, plot.it = F))
best_it.gbm = gbm.perf(model.gbm, plot.it = F) #0.28861

#influence
var_inf = summary(model.gbm, n.trees = best_it.gbm, plotit = F)
plot_gbminfluence(var_inf)
print(var_inf)

plots = plot_gbmpartial(model.gbm, best_it.gbm, as.character(var_inf$var), output_type = 'response')
marrangeGrob(plots, nrow = 2, ncol = 3, top = NULL)

pred.gbm = predict(model.gbm, n.trees = best_it.gbm, type = 'response')
#plot_binmodel_roc(df$is_attributed, pred.gbm)
#plot_binmodel_percentiles(df$is_attributed, pred.gbm, n = 50)
calibrate.plot(df$is_attributed, pred.gbm)
gbm.roc.area(df$is_attributed, pred.gbm) #0.9747768


roc_boot = ldply(seq(128), function(i){
  sample_index = sample.int(nrow(df), 0.1*nrow(df))
  res = data.frame(roc = gbm.roc.area(df$is_attributed[sample_index], pred.gbm[sample_index]))
})
ggplot(roc_boot, aes(roc)) + geom_histogram(bins = 16)

extra_vars = c('ip_ex','ip_count_log','os_per_ip','app_per_ip','channel_per_ip',
               'app_ex','device_ex','channel_ex','os_ex',
               'click_time_day','click_time_min','click_time_sec','click_time_hour','click_time_seconds','click_time_hour_ex',
               'ip_count','ip_prior')

plots = llply(c(all.vars(formula.gbm), extra_vars), function(var_name) {
  p = plot_profile(pred.gbm, df$is_attributed, df[[var_name]], error_band = 'binom', bucket_count = 20) +
    ggtitle(var_name) +  theme(title =element_text(size=8))
  return( p )
})
marrangeGrob(plots, nrow = 2, ncol = 2, top = NULL)

plot_profile(pred.gbm, df$is_attributed, df$app_ex, error_band = 'binom', bucket_count = 20)
plot_profile(pred.gbm, df$is_attributed, df$ip_ex, error_band = 'binom', bucket_count = 20)
plot_profile(pred.gbm, df$is_attributed, df$channel_ex, error_band = 'binom', bucket_count = 20)
plot_profile(pred.gbm, df$is_attributed, factor(df$click_time_hour), error_band = 'binom', bucket_count = 20)

```


## Submit

```{r submit, echo=FALSE}

  #compute prediction (sampling_correction = -6.000771)
  pred.gbm_link = predict(model.gbm, n.trees = best_it.gbm, newdata = test, type = 'link')
  model_pred = 1.0 / (1.0 + exp(-pred.gbm_link - sampling_correction))


  submit <- data.table(click_id = test$click_id, is_attributed = model_pred)
  file = file.path(working_folder, "Clicks/model_pred.csv")
  fwrite(submit, file = file, row.names = FALSE)
  zip(paste(file, '.zip', sep = ''), file, compression_level = 9)
  print(file)

```