---
title: "FNMA Loan Level Data"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
rm(list = ls())

knitr::opts_chunk$set(echo = TRUE, fig.width = 8, fig.height = 5, dpi = 240)
options(warn=-1)

library(plyr)
library(foreach)
library(data.table)
library(stringi)
library(ggplot2)
library(gridExtra)
library(zip)
library(forcats)
library(lubridate)
library(R.utils)
library(zoo)

working_folder = 'D:/Github/KaggleSandbox'
#working_folder = file.path(Sys.getenv("HOME"), 'source/github/KaggleSandbox/')
source(file.path(working_folder, '/Utils/common.R'))

smm2cpr <- function(smm){
  100.0*(1.0 - (1.0 - smm)^12)
}

cpr2smm<- function(cpr){
  (1.0 - (1.0 - cpr/100)^(1/12))
}

pmt  <- function(wac, wam){
  r = wac / 1200.0
  return ( r / (1.0 - (1.0 + r)^(-wam) ))
}
next_sched_balance <-function(wac, wam){
  return ( 1 + wac / 1200.0 - pmt(wac, wam))
}

sched_balance <-function(age, wac, term){
  r = wac / 1200.0
  return (  (1 - (1+r)^(pmax(0, age)-term)) / (1.0 - (1.0 + r)^(-term) ))
}

uwac_model <- function(rate, logistic = FALSE){
  uwac = rate
  
  if(logistic){
    for(i in 2:length(uwac)){
      dr = rate[i-1] - uwac[i-1]
      uwac[i] = uwac[i-1]  -0.06 + (0.01+0.06) * logistic((dr+0.7)/0.2)
    }
  }else{
    for(i in 2:length(uwac)){
      dr = rate[i-1] - uwac[i-1]
      uwac[i] = uwac[i-1] + dr * ifelse(dr > 0, 0.02, 0.04)
    }
  }
  return(uwac)
}

#test_df = data.table(i = seq(0, 360))
#test_df[, pay := pmt(6.0, 360-i)]
#test_df[, n_sb := next_sched_balance(6.0, 360-i)]
#test_df[, sb := sched_balance(i, 6.0, 360)]
```


## Load FNMA loan data
load 1% of loans
```{r load_data}
data_folder = 'W:/loan_level/fnma/raw'
#data_folder = 'D:/loan_level/'

to_date<-function(date_string){
  as.Date(stri_join(ifelse(stri_length(date_string) == 5, '010','01'), date_string), format = '%d%m%Y')
}
to_date2<-function(date_string){
 ns = stri_length(date_string)
 make_date(as.numeric(stri_sub(date_string, ns-3)), as.numeric(stri_sub(date_string, to = ns-4)), 1)
}
#to_date(c('52003','122003'))
#to_date2(c('52003','122003'))
#library(microbenchmark)
#microbenchmark(to_date(c('52003','122003')), to_date2(c('52003','122003')))



### Define the Loan Performance table headers
lppub_column_names <- c("POOL_ID", "LOAN_ID", "ACT_PERIOD", "CHANNEL", "SELLER", "SERVICER",
                        "MASTER_SERVICER", "ORIG_RATE", "CURR_RATE", "ORIG_UPB", "ISSUANCE_UPB",
                        "CURRENT_UPB", "ORIG_TERM", "ORIG_DATE", "FIRST_PAY", "LOAN_AGE",
                        "REM_MONTHS", "ADJ_REM_MONTHS", "MATR_DT", "OLTV", "OCLTV",
                        "NUM_BO", "DTI", "CSCORE_B", "CSCORE_C", "FIRST_FLAG", "PURPOSE",
                        "PROP", "NO_UNITS", "OCC_STAT", "STATE", "MSA", "ZIP", "MI_PCT",
                        "PRODUCT", "PPMT_FLG", "IO", "FIRST_PAY_IO", "MNTHS_TO_AMTZ_IO",
                        "DLQ_STATUS", "PMT_HISTORY", "MOD_FLAG", "MI_CANCEL_FLAG", "Zero_Bal_Code",
                        "ZB_DTE", "LAST_UPB", "RPRCH_DTE", "CURR_SCHD_PRNCPL", "TOT_SCHD_PRNCPL",
                        "UNSCHD_PRNCPL_CURR", "LAST_PAID_INSTALLMENT_DATE", "FORECLOSURE_DATE",
                        "DISPOSITION_DATE", "FORECLOSURE_COSTS", "PROPERTY_PRESERVATION_AND_REPAIR_COSTS",
                        "ASSET_RECOVERY_COSTS", "MISCELLANEOUS_HOLDING_EXPENSES_AND_CREDITS",
                        "ASSOCIATED_TAXES_FOR_HOLDING_PROPERTY", "NET_SALES_PROCEEDS",
                        "CREDIT_ENHANCEMENT_PROCEEDS", "REPURCHASES_MAKE_WHOLE_PROCEEDS",
                        "OTHER_FORECLOSURE_PROCEEDS", "NON_INTEREST_BEARING_UPB", "PRINCIPAL_FORGIVENESS_AMOUNT",
                        "ORIGINAL_LIST_START_DATE", "ORIGINAL_LIST_PRICE", "CURRENT_LIST_START_DATE",
                        "CURRENT_LIST_PRICE", "ISSUE_SCOREB", "ISSUE_SCOREC", "CURR_SCOREB",
                        "CURR_SCOREC", "MI_TYPE", "SERV_IND", "CURRENT_PERIOD_MODIFICATION_LOSS_AMOUNT",
                        "CUMULATIVE_MODIFICATION_LOSS_AMOUNT", "CURRENT_PERIOD_CREDIT_EVENT_NET_GAIN_OR_LOSS",
                        "CUMULATIVE_CREDIT_EVENT_NET_GAIN_OR_LOSS", "HOMEREADY_PROGRAM_INDICATOR",
                        "FORECLOSURE_PRINCIPAL_WRITE_OFF_AMOUNT", "RELOCATION_MORTGAGE_INDICATOR",
                        "ZERO_BALANCE_CODE_CHANGE_DATE", "LOAN_HOLDBACK_INDICATOR", "LOAN_HOLDBACK_EFFECTIVE_DATE",
                        "DELINQUENT_ACCRUED_INTEREST", "PROPERTY_INSPECTION_WAIVER_INDICATOR",
                        "HIGH_BALANCE_LOAN_INDICATOR", "ARM_5_YR_INDICATOR", "ARM_PRODUCT_TYPE",
                        "MONTHS_UNTIL_FIRST_PAYMENT_RESET", "MONTHS_BETWEEN_SUBSEQUENT_PAYMENT_RESET",
                        "INTEREST_RATE_CHANGE_DATE", "PAYMENT_CHANGE_DATE", "ARM_INDEX",
                        "ARM_CAP_STRUCTURE", "INITIAL_INTEREST_RATE_CAP", "PERIODIC_INTEREST_RATE_CAP",
                        "LIFETIME_INTEREST_RATE_CAP", "MARGIN", "BALLOON_INDICATOR",
                        "PLAN_NUMBER", "FORBEARANCE_INDICATOR", "HIGH_LOAN_TO_VALUE_HLTV_REFINANCE_OPTION_INDICATOR",
                        "DEAL_NAME", "RE_PROCS_FLAG", "ADR_TYPE", "ADR_COUNT", "ADR_UPB")
lppub_column_classes <- c("character", "character", "character", "character", "character", "character",
                          "character", "numeric", "numeric", "numeric", "numeric",
                          "numeric", "numeric", "character", "character", "numeric", "numeric",
                          "numeric", "character", "numeric", "numeric", "character", "numeric",
                          "numeric", "numeric", "character", "character", "character",
                          "numeric", "character", "character", "character", "character",
                          "numeric", "character", "character", "character", "character",
                          "numeric", "character", "character", "character", "character",
                          "character", "character", "numeric", "character", "numeric",
                          "numeric", "numeric", "character", "character", "character",
                          "numeric", "numeric", "numeric", "numeric", "numeric", "numeric",
                          "numeric", "numeric", "numeric", "numeric", "numeric", "character",
                          "numeric", "character", "numeric", "numeric", "numeric", "numeric",
                          "numeric", "numeric", "character", "numeric", "numeric", "numeric",
                          "numeric", "character", "numeric", "character", "numeric", "character",
                          "numeric", "numeric", "character", "character", "numeric", "numeric",
                          "numeric", "numeric", "numeric", "numeric", "numeric", "numeric",
                          "numeric", "numeric", "numeric", "numeric", "numeric", "character",
                          "character", "character", "character", "character",
						  "character", "numeric", "numeric")

files = list.files(file.path(data_folder,'/1pct'),glob2rx('*.1pct'), full.names = TRUE )

#'SELLER',	'SERVICER',	'MASTER_SERVICER','MI_CANCEL_FLAG', 'FIRST_PAY', 'REM_MONTHS', 'ORIG_RATE'
select_columns = c(
  'LOAN_ID',	'ACT_PERIOD',	'CHANNEL',	'CURR_RATE',	'ORIG_UPB',	'CURRENT_UPB',	'ORIG_TERM',	'ORIG_DATE',	'LOAN_AGE',	'ADJ_REM_MONTHS',	'OLTV',	'OCLTV',	'NUM_BO',	'DTI',	'CSCORE_B',	'CSCORE_C',	'FIRST_FLAG',	'PURPOSE',	'PROP',	'NO_UNITS',	'OCC_STAT',	'STATE',	'MI_PCT',	'PRODUCT',	'PPMT_FLG',	'IO', 'DLQ_STATUS', 'MOD_FLAG',	'Zero_Bal_Code')

### Load new origination
df = foreach(file_name = files, .combine = rbind) %do% {
  print(file_name)
  #temp = fread(file_name, sep = "|", col.names = lppub_column_names, colClasses = lppub_column_classes, nrows = 10)
  keep_columns = match(select_columns, lppub_column_names)
  temp = fread(file_name, sep = "|", 
               col.names = lppub_column_names[keep_columns], 
               colClasses = lppub_column_classes, 
               select = keep_columns)
  temp = temp[PRODUCT == 'FRM' & MOD_FLAG != 'Y' & IO == 'N' & PPMT_FLG == 'N' & ORIG_TERM == 360]
  temp[, c('PRODUCT', 'MOD_FLAG', 'IO','ORIG_TERM', 'PPMT_FLG'):=NULL]
  
  #all_loans = unique(temp$LOAN_ID)
  #select_loans = sample(all_loans, floor(load_pct*length(all_loans)) )
  #temp = temp[LOAN_ID %in% select_loans]
  
  #gc()
  return(temp)
}

df[, date:= to_date(ACT_PERIOD)]
df[, date_year:= year(date)]
df[, ACT_PERIOD:=NULL]

df[, orig_date:= to_date(ORIG_DATE)]
df[, orig_year:= year(orig_date)]
df[, orig_year_c:= as.character(orig_year)]
df[, ORIG_DATE:=NULL]

df = df[orig_year>=2010]

setkeyv(df, c('LOAN_ID', 'date'))

#Compute prev UPB and delq
df[, upb := 1e-3*CURRENT_UPB]

#replace UPB with scheduled balance for the first 12 months if it is zero
df[CURRENT_UPB == 0 & Zero_Bal_Code == '' & LOAN_AGE <=24, upb :=  1e-3*ORIG_UPB * sched_balance(LOAN_AGE, CURR_RATE, 360) ]
#df[LOAN_ID == '000098915594',.(date, CURRENT_UPB, LOAN_AGE)]

#define PO flag
df[order(date), Zero_Bal_Code_next := shift(Zero_Bal_Code, -1),  by =.(LOAN_ID)] 
df[, po_ind := as.numeric(Zero_Bal_Code_next == '01') *  as.numeric(DLQ_STATUS == '00')] #next month loan will PO, only prepayment from current are considered 

#df[order(date), LOAN_AGE  := na.locf(LOAN_AGE, na.rm = FALSE),  by =.(LOAN_ID)]
df[order(date), CURR_RATE := na.locf(CURR_RATE, na.rm = FALSE), by =.(LOAN_ID)] # the rate should be fixed

df[order(date), sbal := pmax(0, upb * (1 + CURR_RATE/1200) - 1e-3*pmt(CURR_RATE, 360) * ORIG_UPB), by =.(LOAN_ID)] #next month sched balance, assume fixed payment 
df[is.na(sbal), sbal := upb ] #just in case 
df[order(date), delq_24 := frollsum(as.numeric(DLQ_STATUS!='00'), 24), by =.(LOAN_ID) ] 

#df[order(date), unsched_princ := shift(sbal) - upb, by=.(LOAN_ID) ]
#df[order(date), smm := unsched_princ/shift(sbal), by=.(LOAN_ID) ]
#temp

#saveRDS(df, 'D:/loan_level/fnma_1pct.rds')
#df <- readRDS('D:/loan_level/fnma_1pct.rds')

#saveRDS(df, 'D:/loan_level/fnma_10pct.rds')
#df <- readRDS('D:/loan_level/fnma_10pct.rds')
	

#df[Zero_Bal_Code_next == '01' & date == '2005-01-01', LOAN_ID]
#cc(df[LOAN_ID == '999997761057'])
#df[LOAN_ID == '999961864686', .(date, CURR_RATE, LOAN_AGE,ORIG_UPB, upb, CURRENT_UPB, sbal, po_ind, Zero_Bal_Code, DLQ_STATUS, delq_24)]
df = df[!is.na(po_ind)] #remove last date 
```

## show data

```{r show_data}

df_agg = df[,.(.N), by =.(date, Zero_Bal_Code_next)]
ggplot(df_agg, aes(date, N)) + geom_point() + facet_wrap(~Zero_Bal_Code_next, scales = 'free')

df_agg = df[,.(.N, upb = sum(upb, na.rm = TRUE), 
               po = mean(po_ind,na.rm = TRUE), 
               smm = weighted.mean(po_ind, sbal, na.rm = TRUE)), by=.(date)]

ggplot(df_agg, aes(date, N)) + geom_point()
ggplot(df_agg, aes(date, upb)) + geom_point()
ggplot(df_agg, aes(date, upb/N)) + geom_point() + geom_line()
ggplot(df_agg, aes(date, smm2cpr(po) )) + geom_point() + geom_line() + geom_line(aes(date, smm2cpr(smm) ), color = 'red')
ggplot(df_agg, aes(date,  smm2cpr(smm)  )) + geom_point() + geom_line()

df_agg = df[,.(.N, upb = sum(upb, na.rm = TRUE)), by=.(date, orig_year)]
ggplot(df_agg, aes(date, upb, group = orig_year)) + geom_line()

df_agg = df[,.(.N, upb = sum(upb, na.rm = TRUE), smm = weighted.mean(po_ind, sbal, na.rm = TRUE)), by=.(date, orig_year)]
ggplot(df_agg, aes(date, smm, group = orig_year)) + geom_line()

df_agg = df[,.(.N, upb = sum(upb, na.rm = TRUE), smm = weighted.mean(po_ind, sbal, na.rm = TRUE)), by=.(date, PROP)]
ggplot(df_agg, aes(date, smm2cpr(smm), group = PROP)) + geom_line() + facet_wrap(~PROP)
ggplot(df_agg, aes(date, upb/N, group = PROP, color = PROP)) + geom_line()

```

##Load MEV

```{r load_mev}
#load mortgage rate
df_mtg = fread("W:/FRED/MORTGAGE30US.csv")
df_mtg[, date:= make_date(year(DATE), month(DATE), 1)]
df_mtg = df_mtg[, .(rate = mean(MORTGAGE30US, na.rm = TRUE)), by =.(date)] #simple average

df_hpi = fread("W:/FRED/CSUSHPINSA.csv")
df_hpi[, date:= make_date(year(DATE), month(DATE), 1)]
df_hpi[, hpi := CSUSHPINSA]
df_hpi[order(date), hpi_1y := shift(hpi, 12)]
df_hpi[order(date), hpi_2y := shift(hpi, 24)]
df_hpi[, hpa    := 100*(hpi/ hpi_1y - 1)]
df_hpi[, hpa_2y := 100*(hpi/ hpi_2y - 1)]

df_uer = fread("W:/FRED/UNRATE.csv")
df_uer[, date:= make_date(year(DATE), month(DATE), 1)]
df_uer[, uer := UNRATE]


df_mev = df_mtg[df_hpi[,.(date, hpi, hpa, hpa_2y)], on=.(date)]
df_mev = df_mev[df_uer[,.(date, uer)], on=.(date)]
df_mev = df_mev[!is.na(rate)]
df_mev[order(date), rate_1m := shift(rate, 1)]
df_mev[order(date), rate_3m48:=frollmean(rate, 3) - frollmean(rate, 48)]
df_mev[order(date), rate_1m48:=rate               - frollmean(rate, 48)]
df_mev[order(date), rate_3m60:=frollmean(rate, 3) - frollmean(rate, 60)]
df_mev[order(date), rate_1m60:=rate               - frollmean(rate, 60)]
df_mev[order(date), uer_1m60 :=uer                - frollmean(uer,  60)]
df_mev[order(date), uer_1y :=uer - shift(uer, 12)]

setkey(df_mev,'date')

df_busday = data.table(date = min(df$date) + seq(0, max(df$date) - min(df$date)))
df_busday[, date_month := make_date(year(date), month(date), 1)]
df_busday[, date_week := wday(date)]
df_busday = df_busday[date_week %!in% c(1, 7),.(.N), by=date_month][N>15]

# ----------------------------------------
ggplot(df_mev[date>'2000-01-01'], aes(date, rate)) + geom_line()
ggplot(df_mev[date>'2000-01-01'], aes(date, rate_3m48)) + geom_line()
ggplot(df_mev[date>'2000-01-01'], aes(date, rate_1m60)) + geom_line()
ggplot(df_mev[date>'2000-01-01'], aes(date, hpi)) + geom_line()
ggplot(df_mev[date>'2000-01-01'], aes(date, hpa)) + geom_line()

```

##UWAC

```{r uwac_model}
df_agg = df[LOAN_AGE == 1,.(.N, upb = sum(upb, na.rm = TRUE), wac = weighted.mean(CURR_RATE, upb, na.rm = TRUE )), by=.(orig_date)]
ggplot(df_agg, aes(orig_date, wac)) + geom_point() + geom_line() + geom_line(data = df_mev[date>'2009-01-01'], aes(date, rate_1m), color = 'red')

#ccf(df_agg$wac, df_agg$inc, lag.max = 5, plot = FALSE)

df_agg = df[,.(.N, upb = sum(upb, na.rm = TRUE), uwac = weighted.mean(CURR_RATE, upb, na.rm = TRUE )), by=.(date)]
df_mev[df_agg, uwac:=i.uwac, on =.(date)]
df_mev[order(date), uwac_delta := shift(uwac, -1) - uwac]

ggplot(df_mev[date>'2010-01-01'], aes(date, uwac)) + geom_point() + geom_line() + geom_line(aes(date, rate), color = 'red')
ggplot(df_mev[date>'2010-01-01'], aes(rate - uwac, uwac_delta)) + geom_point() + geom_smooth(span = 0.9, se = FALSE, method = 'loess')

df_media = df_mev[date>'2010-01-01', .(date, media_ei_lin = rate - uwac_model(rate), media_ei_log = rate - uwac_model(rate, logistic = TRUE), rate_1m48, rate_1m60) ]

df_media = melt(df_media, id.vars = 'date')
ggplot(df_media, aes(date, value, group = variable, color = variable)) +geom_line() + scale_color_custom('mixed')

#lm(uwac_delta ~ I(rate - uwac), df_mev[date>'2010-01-01' & rate - uwac < 0])

df_mev[order(date), media_ei_lin := rate - uwac_model(rate, logistic = FALSE) ]
df_mev[order(date), media_ei_log := rate - uwac_model(rate, logistic = TRUE) ]

ggplot(df_mev) + geom_line(aes(date, media_ei_log)) + geom_line(aes(date, media_ei_lin))

```

## Create variables

```{r create_variables}

df_mev[order(date), media_ei_lin := rate - uwac_model(rate, logistic = FALSE) ]
df_mev[order(date), media_ei_log := rate - uwac_model(rate, logistic = TRUE) ]

df[df_mev, ei_ratio := 100*(CURR_RATE/i.rate-1), on =.(date)]
df[df_mev, ei       := 100*(CURR_RATE - i.rate   ), on =.(date)]
df[df_mev, ei_1m    := 100*(CURR_RATE - i.rate_1m), on =.(date)]
df[df_mev, hpi       := i.hpi, on =.(date)]
df[df_mev, hpa       := i.hpa, on =.(date)]
df[df_mev, hpa_2y    := i.hpa_2y, on =.(date)]
df[df_mev, hpi_orig  := i.hpi, on =.(orig_date = date)]
df[df_mev, sato   :=  100*(CURR_RATE - i.rate), on =.(orig_date = date)]


df[df_mev, media_ei_log   := i.media_ei_log, on =.(date)]
df[df_mev, media_ei_lin   := i.media_ei_lin, on =.(date)]
df[df_mev, rate_1m48  := i.rate_1m48, on =.(date)]
df[df_mev, rate_3m48  := i.rate_3m48, on =.(date)]
df[df_mev, rate_1m60  := i.rate_1m60, on =.(date)]
df[df_mev, rate_3m60  := i.rate_3m60, on =.(date)]

df[df_mev, uer       := i.uer,      on =.(date)]
df[df_mev, uer_1m60  := i.uer_1m60, on =.(date)]
df[df_mev, uer_1y    := i.uer_1y,   on =.(date)]
df[df_busday, busday := i.N,   on =.(date = date_month  )]



df[, factor := upb / (1e-3*ORIG_UPB) ]
df[, CLTV   :=  OLTV * factor * hpi_orig / hpi ]
df[, hpa_life  :=   hpi/hpi_orig - 1 ]
df[, season := month(date)]
df[, season_s := sprintf('%02d', season) ]
df[, geo_ny  := as.numeric(STATE == 'NY')]
df[, geo_pr  := as.numeric(STATE == 'PR')]
df[, co_borrower  := as.numeric(!is.na(CSCORE_C))]
df[, score_diff   := CSCORE_B - CSCORE_C]

#cum incentive
df[order(date), cum_ei   := 0.01*cumsum(pmax(0, ei - 10)), by =.(LOAN_ID)]
df[order(date), cum_eim  := cumsum(logistic( (ei - 30)/5 )), by =.(LOAN_ID)]

df_agg = df[,.(.N, upb = sum(upb, na.rm = TRUE), po = mean(po_ind, na.rm = TRUE), 
               smm = weighted.mean(po_ind, sbal, na.rm = TRUE ),
               ei = weighted.mean(ei, sbal)), by=.(date)]

#ccf(df_agg$smm, df_agg$ei, lag.max = 5)
ccf(df_agg$smm, df_agg$ei, lag.max = 5, plot = FALSE)

#ggplot(df_agg, aes(smm, inc)) + geom_point()
ggplot(df_agg, aes(date, N)) + geom_point()
ggplot(df_agg, aes(date, upb)) + geom_point()
ggplot(df_agg, aes(date, upb/N)) + geom_point()
ggplot(df_agg, aes(date, ei)) + geom_point() + geom_line() 
ggplot(df_agg, aes(date, po)) + geom_point() + geom_line() + geom_line(aes(date, smm), color = 'red')
ggplot(df_agg, aes(date, ei/2)) + geom_point() + geom_line() + geom_line(aes(date, smm2cpr(smm)), color = 'red')

df_agg = df[,.(.N, upb = sum(upb, na.rm = TRUE), po = mean(po_ind), 
               smm = weighted.mean(po_ind, sbal, na.rm = TRUE )), by=.(LOAN_AGE)]

ggplot(df_agg, aes(LOAN_AGE, upb/N)) + geom_point()
ggplot(df_agg[N>100], aes(LOAN_AGE, po)) + geom_point() + geom_line() + geom_line(aes(LOAN_AGE, smm), color = 'red')

plot_profile(df$po_ind, df$po_ind, df$date)
plot_profile(df$po_ind, df$po_ind, df$ei)
plot_profile(df$po_ind, df$po_ind, df$cum_ei)
plot_profile(df$po_ind, df$po_ind, df$cum_eim)
```


## ML Model

```{r ml_model}
## ----------------------------------------------
library(lightgbm)

set.seed(1321)

t_index_v = sample.int(nrow(df), 2e6)
v_index_v = sample.int(nrow(df), 2e6) %!in_set% t_index_v

obj_var = 'po_ind'
media_vars = c('media_ei_lin', 'media_ei_log', 'rate_1m48', 'rate_1m60', 'rate_3m48', 'rate_3m60')
burnout_vars = c('cum_ei', 'cum_eim', 'factor') #'cum_ei', 'factor'
lgb_vars = c('ei', 'LOAN_AGE', 'season', 'upb', 'PURPOSE', 'OCC_STAT', 'CHANNEL','PROP', 'DTI', 'CSCORE_B', 'co_borrower','score_diff', 'FIRST_FLAG', 'CLTV', 'OLTV', 'rate_1m48', 'sato', 'cum_eim', 'geo_ny', 'geo_pr', 'NO_UNITS', 'hpa', 'hpa_life', 'busday') %!in_set% c('id') #best performance
#lgb_vars = c('ei', 'LOAN_AGE', 'season', 'upb', 'PURPOSE', 'OCC_STAT', 'CHANNEL','DTI', 'CSCORE_B',  'CLTV') %!in_set% c('id') #best performance

my_cat_vars =  names(which(sapply(df[,lgb_vars, with = FALSE], function(x) is.factor(x) | is.character(x) )))

### - logistic regression for loss > 0 -----------
dfs = df[t_index_v, c(obj_var,lgb_vars), with = FALSE]

dtrain <- lgb.Dataset(data.matrix(dfs[, lgb_vars , with = FALSE]), label = dfs[[obj_var]], categorical_feature = my_cat_vars)
dtest  <- lgb.Dataset.create.valid(dtrain, data.matrix(df[v_index_v, lgb_vars , with = FALSE]), label = df$po_ind[v_index_v])

params_bin <- list(objective = "binary")

model.lgb = lgb.train(params = params_bin, data = dtrain, learning_rate = 0.01,
                      valids = list(test = dtest),
                      num_threads = 4, nrounds = 3000,
                      eval_freq = 100, boost_from_average = TRUE, verbose = 1, force_row_wise = TRUE)

cv_error = as.numeric(model.lgb$record_evals$test$binary_logloss$eval)
ggplot(data.frame( i = seq(length(cv_error)), cv_error ), aes(i, cv_error)) + geom_line() + geom_vline(xintercept = model.lgb$best_iter, linetype = 'dashed')

lgb_importance = lgb.importance(model.lgb, percentage = TRUE)
ggplot(lgb_importance[Gain > 0.001], aes(fct_reorder(Feature,Gain), Gain)) + geom_bar(stat = 'identity') + coord_flip()
 
df[, po_pred := predict(model.lgb, data.matrix(df[,lgb_vars, with = F]))]

plot_act_vs_model <-function(df, profile, index = NULL, ...){
  p = NULL
  if(is.null(index)) {
    p = plot_profile(df[['po_pred']], df[['po_ind']], df[[profile]], map_fun = smm2cpr, ...)
  }else{
    p = plot_profile(df[['po_pred']][index], df[['po_ind']][index], df[[profile]][index], map_fun = smm2cpr, ...)
  }
  return( p )
}
plot_act_vs_model(df, 'LOAN_AGE', bucket_count = 50)
plot_act_vs_model(df, 'date', bucket_count = 50)
plot_act_vs_model(df, 'ei', bucket_count = 50)
plot_act_vs_model(df, 'sato', bucket_count = 50)
plot_act_vs_model(df, 'ei_ratio', bucket_count = 50)


#turnover
vname = 'LOAN_AGE'
p1 = plot_act_vs_model(df, vname,  df$ei < 0, bucket_count = 20) + ggtitle('turnover')
p2 = plot_act_vs_model(df, vname,             bucket_count = 20) + ggtitle('prepayment')
grid.arrange(p1, p2)

plot_act_vs_model(df, 'LOAN_AGE', index, bucket_count = 50)

index = df$STATE == 'NY'
plot_act_vs_model(df, 'date')

index = df$PROP == 'PU'
plot_act_vs_model(df, 'date', index)

#all states
plots = llply(unique(df$STATE), function(my_state) { #lgb_vars
  index = df$STATE == my_state
    p =plot_act_vs_model(df, 'date', index, error_band = 'binom') + ggtitle(my_state) +  theme(title =element_text(size=8))
    return( ggplotGrob(p) )
  })
#marrangeGrob(plots, nrow = 6, ncol = 7, top = NULL)
ggsave(filename = "D:/loan_level/profiles_by_state.pdf", plot = marrangeGrob(plots, nrow=3, ncol=4), device = 'pdf', width = 14, height = 8.5, dpi = 360)


#all profiles
plots = llply(names(df) %!in_set% c('LOAN_ID', 'CURRENT_UPB', 'Zero_Bal_Code', 'smm', 'Zero_Bal_Code_next'), function(var_name) { #lgb_vars
  print(var_name)
    p = plot_act_vs_model(df, var_name, bucket_count = 20, error_band = 'binom') + ggtitle(var_name) +  theme(title =element_text(size=8))
    return( ggplotGrob(p) )
  })
#marrangeGrob(plots, nrow = 6, ncol = 7, top = NULL)
ggsave(filename = "D:/loan_level/profiles_all.pdf", plot = marrangeGrob(plots, nrow=4, ncol=4), device = 'pdf', width = 14, height = 8.5, dpi = 360)

plots = llply(c('date','cum_eim', 'cum_ei', 'media_ei_log', 'media_ei_lin', 'rate_1m48', 'rate_3m48', 'rate_1m60', 'rate_3m60', 'uer', 'hpa', 'uer_1m60'), function(var_name) { #lgb_vars
  print(var_name)
    p = plot_act_vs_model(df, var_name, bucket_count = 10, error_band = 'binom') +
      ggtitle(var_name) +  theme(title =element_text(size=8))
    return( ggplotGrob(p) )
  })
marrangeGrob(plots, nrow = 3, ncol = 4, top = NULL)


for(vname in names(df) %!in_set% c('LOAN_ID', 'CURRENT_UPB', 'Zero_Bal_Code', 'smm', 'Zero_Bal_Code_next', 'po_pred', 'date', 'DLQ_STATUS', 'orig_date')) {
  print(vname)
  #vname = 'PURPOSE'
  #vname = 'upb'
  if(is.numeric(df[[vname]])){
    segments = cutq(df[[vname]], probs = seq(0, 1, 0.25))
    buckets = levels(segments)
  }else{
    segments = df[[vname]]
    buckets = df[,.(.N), by =c(vname)][[vname]]
  }
  
  plots_turn = llply(buckets, function(my_level){
     index = segments == my_level & df$ei < 0
     p = plot_act_vs_model(df, 'date', index, error_band = 'binom') + ggtitle(sprintf('%s, turnover (ei < 0)', my_level)) +  theme(title = element_text(size=8))   
    })
  
    plots = llply(buckets, function(my_level){
     index = segments == my_level
     p = plot_act_vs_model(df, 'date', index, error_band = 'binom') + ggtitle(my_level) +  theme(title = element_text(size=8))   
    })
  ggsave(filename = sprintf("D:/loan_level/profiles_%s.pdf", vname), plot = marrangeGrob(c(plots_turn, plots), nrow=2, ncol=2,top = vname), device = 'pdf', width = 14, height = 8.5, dpi = 360)
}

#partial plots --------- 
pdp_index = sample.int(nrow(df), 1000)
data_mat = data.matrix(df[pdp_index,lgb_vars, with = FALSE])

plots = llply(lgb_importance$Feature, function(my_var){
  df_plot = partialPlot(model.lgb, data_mat, xname = my_var, n.pt = 100)
  ggplot(df_plot, aes(x, smm2cpr(y) )) + geom_line() + 
    #geom_rug(data = df[pdp_index, my_var, with = FALSE], aes_string(x=my_var), sides = 'b', alpha = 0.2, size = 0.1, inherit.aes = FALSE) + 
    ggtitle(my_var) + xlab(my_var) + ylab('cpr')
})
marrangeGrob(plots, nrow = 3, ncol = 4, top = NULL)

ggsave(filename = "D:/loan_level/partial_profiles_baseline.pdf", plot = marrangeGrob(plots, nrow=3, ncol=3,top = NULL), device = 'pdf', width = 14, height = 8.5, dpi = 360)

```

#Parametric Model
```{r parametric_model}

t_index_v = sample.int(nrow(df), 5e6)


plot_act_vs_model2 <-function(df, profile, index = NULL, ...){
  p = NULL
  if(is.null(index)) {
    p = plot_profile(df[['model_smm']], df[['po_ind']], df[[profile]], map_fun = smm2cpr, ...)
  }else{
    p = plot_profile(df[['model_smm']][index], df[['po_ind']][index], df[[profile]][index], map_fun = smm2cpr, ...)
  }
  return( p )
}

smm_model <- function(x, params){
    turn_scurve = params[['turn_low']] + (params[['turn_high']] - params[['turn_low']])*logistic((x$ei - params[['turn_scurve_shift']])/params[['turn_scurve_slope']])
    turn_ramp = approx(params[['turn_ramp_x']], params[['turn_ramp_y']], rule = 2, x$LOAN_AGE)$y
    turn_season = approx(params[['turn_season_x']], params[['turn_season_y']], rule = 2, x$season)$y
    turn_fico = approx(params[['turn_fico_x']], params[['turn_fico_y']], rule = 2, x$CSCORE_B)$y
    turn_fico[is.na(x$CSCORE_B)] = 1.0
    turn_cltv = approx(params[['turn_cltv_x']], params[['turn_cltv_y']], rule = 2, x$CLTV)$y
    turn_als = approx(params[['turn_als_x']], params[['turn_als_y']], rule = 2, x$upb)$y
    turn_occ =  params[['turn_occ_y']][ match(x$OCC_STAT, params[['turn_occ_x']])]
    turn_hpal = approx(params[['turn_hpal_x']], params[['turn_hpal_y']], rule = 2, x$hpa_life)$y
    
    refi_scurve = params[['refi_low']] + (params[['refi_high']] - params[['refi_low']])*logistic((x$ei - params[['refi_scurve_shift']])/params[['refi_scurve_slope']])
    refi_ramp = approx(params[['refi_ramp_x']], params[['refi_ramp_y']], rule = 2, x$LOAN_AGE)$y
    refi_als = approx(params[['refi_als_x']], params[['refi_als_y']], rule = 2, x$upb)$y
    refi_cltv = approx(params[['refi_cltv_x']], params[['refi_cltv_y']], rule = 2, x$CLTV)$y
    refi_fico = approx(params[['refi_fico_x']], params[['refi_fico_y']], rule = 2, x$CSCORE_B)$y
    refi_fico[is.na(x$CSCORE_B)] = 1.0
    
    curt_als = approx(params[['curt_als_x']], params[['curt_als_y']], rule = 2, x$upb)$y
    curt_factor = approx(params[['curt_factor_x']], params[['curt_factor_y']], rule = 2, x$factor)$y
    
    refi_burn = approx(params[['refi_burn_x']], params[['refi_burn_y']], rule = 2, x$cum_eim)$y
    refi_hpal = approx(params[['refi_hpal_x']], params[['refi_hpal_y']], rule = 2, x$hpa_life)$y
    
    media_scurve = params[['media_low']] + (params[['media_high']] - params[['media_low']])*logistic((x$media_ei_lin - params[['media_scurve_shift']])/params[['media_scurve_slope']])
    
    refi_occ =  params[['refi_occ_y']][ match(x$OCC_STAT, params[['refi_occ_x']])]
    refi_chn =  params[['refi_chn_y']][ match(x$CHANNEL,  params[['refi_chn_x']])]
    
    
    
    total_smm = turn_scurve * turn_ramp * turn_season * turn_fico * turn_cltv * turn_als * turn_occ * turn_hpal + 
      refi_scurve * refi_ramp * refi_als * refi_fico * refi_cltv * refi_occ * refi_burn * media_scurve * refi_chn * refi_hpal + 
      curt_als * curt_factor
    #total_smm = turn_scurve 
    
    return( pmin(1.0-1e-9, pmax(1e-9, total_smm)) )
}

#library(microbenchmark)
#microbenchmark(approx(params[['turn_season_x']], params[['turn_season_y']], rule = 2, sample.int(12, 100000, replace = TRUE))$y)

objective_function <- function(df_in, index){
  return( df_in[index, mean(sbal * (po_ind * log(model_smm) + (1-po_ind) * log(1-model_smm)),rm.na = TRUE)  ] )
}

turn_objective_function <- function(params_in){
  df[turn_index, model_smm := smm_model(.SD, params_in)]
  objective_function(df, turn_index)
}
refi_objective_function <- function(params_in){
  df[t_index_v, model_smm := smm_model(.SD, params_in)]
  objective_function(df, t_index_v)
}

## FIT Turnover S-Curve (-8.078541)
params = list('turn_low' = cpr2smm(6.2), 'turn_high' = cpr2smm( 10.1), 'turn_scurve_shift' = -22.48904, 'turn_scurve_slope' = 18.61279 , #'turn_scurve_slope' = 18.61279, 
              'turn_ramp_x' = c(0,    3,    6,  12,  24,  36), 
              'turn_ramp_y' = c(0.1, 0.3, 0.5, 0.8, 0.9, 1.0),
              'turn_fico_x' = c(680,   720, 760,  780, 800), 
              'turn_fico_y' = c(1.16, 1.11, 1.05, 1.0, 0.9),
              'turn_cltv_x' = c(80,  90), 
              'turn_cltv_y' = c(1.0, 0.6),
              'turn_als_x' = c(50,  100), 
              'turn_als_y' = c(1.3, 1.0),
              'turn_hpal_x' = c(-0.05, 0), 
              'turn_hpal_y' = c( 0.5, 1),
              'turn_occ_x' = c('I', 'P', 'S'),
              'turn_occ_y' = c(0.9, 1.0, 1.1),
              'turn_season_x' = c(1,     2,  3,   4,   5,   6,  7,  8,    9, 10, 11, 12),
              'turn_season_y' = c(0.85,1.12,1.15,1.2,1.2,1.15,1.1,1.05,1.05,1.0,0.9,0.8),
              'refi_low' = cpr2smm(0), 'refi_high' = cpr2smm(20), 'refi_scurve_shift' =  64.95642243, 'refi_scurve_slope' = 20.74949680,
              'refi_ramp_x' = c(0,    3,    6,  12), 
              'refi_ramp_y' = c(0.1, 0.4, 0.9, 1.0),
              'refi_als_x' = c(50, 100, 200, 300, 400, 450), 
              'refi_als_y' = c(0, 0.4, 1.0, 1.7, 2.2, 2.8),
              'refi_fico_x' = c(650, 680, 700,  740, 760, 800), 
              'refi_fico_y' = c(0.6, 0.7, 0.8,  1.0, 1.2, 1.3),
              'refi_cltv_x' = c(75,  90), 
              'refi_cltv_y' = c(1.0, 0.6),
              'refi_burn_x' = c(30,  60), 
              'refi_burn_y' = c(1.0, 0.8),
              
              'refi_hpal_x' = c(-0.1, 0), 
              'refi_hpal_y' = c( 0.5, 1),
              'refi_occ_x' = c('I', 'P', 'S'),
              'refi_occ_y' = c(0.55, 1.0, 0.7),
              'refi_chn_x' = c('B', 'R', 'C'),
              'refi_chn_y' = c(1.15, 0.95, 1.0),
              
              'media_low' = 0.7, 'media_high' = 1.6, 'media_scurve_shift' = -0.45, 'media_scurve_slope' = -0.12,
              
              'curt_als_x' = c(5, 10, 15, 20, 35), 
              'curt_als_y' = c(cpr2smm(80),cpr2smm(28), cpr2smm(20),cpr2smm(10), 0.0),
              'curt_factor_x' = c(0, 0.1, 0.5), 
              'curt_factor_y' = c(2.0, 1.5, 1.0)
              )  

#    -15.98697

df[, model_smm := smm_model(.SD, params)]
objective_function(df, t_index_v)
#plot_act_vs_model2(df, 'ei', bucket_count = 25)
plot_act_vs_model2(df, 'media_ei_lin', bucket_count = 10)
plot_act_vs_model2(df, 'busday', bucket_count = 10)

plot_act_vs_model2(df, 'upb', bucket_count =  100)
plot_act_vs_model2(df, 'date', bucket_count =  25)
plot_act_vs_model2(df, 'CLTV', bucket_count =  100)
plot_act_vs_model2(df, 'ei', bucket_count = 100)
plot_act_vs_model2(df, 'LOAN_AGE', bucket_count = 100)
plot_act_vs_model2(df, 'upb', bucket_count = 100)
plot_act_vs_model2(df, 'CSCORE_B', bucket_count = 50)
plot_act_vs_model2(df, 'rate_1m48', bucket_count = 10)
plot_act_vs_model2(df, 'media_ei_lin', bucket_count = 10)
plot_act_vs_model2(df, 'cum_eim', bucket_count = 50)
plot_act_vs_model2(df, 'ei_ratio', bucket_count = 50)
plot_act_vs_model2(df, 'factor', bucket_count = 100)
plot_act_vs_model2(df, 'OCC_STAT', bucket_count = 100)
plot_act_vs_model2(df, 'CHANNEL', bucket_count = 100)
plot_act_vs_model2(df, 'DTI', bucket_count = 100)
plot_act_vs_model2(df, 'hpa_life', bucket_count = 100)

#S-Curves
plot_profile(df$DTI, df$DTI, df$date, bucket_count = 25)

my_index =  df$ei<0
plot_act_vs_model2(df, 'DTI', my_index, bucket_count = 100)
plot_act_vs_model2(df, 'season_s', my_index, bucket_count = 100)
plot_act_vs_model2(df, 'OCC_STAT', my_index, bucket_count = 100)
plot_act_vs_model2(df, 'CHANNEL', my_index, bucket_count = 100)
plot_act_vs_model2(df, 'hpa_life',my_index, bucket_count = 100)
plot_act_vs_model2(df, 'CSCORE_B',my_index, bucket_count = 50)



plot_act_vs_model2(df, 'upb', my_index, bucket_count = 50)
plot_act_vs_model2(df, 'ei', my_index, bucket_count = 50)
plot_act_vs_model2(df, 'factor', my_index, bucket_count = 50)
plot_act_vs_model2(df, 'CLTV', my_index, bucket_count = 50)
plot_act_vs_model2(df, 'LOAN_AGE', my_index, bucket_count = 50)
plot_profile(df$upb[my_index], df$upb[my_index], df$CLTV[my_index], bucket_count = 25)


my_vars = c('ei', 'LOAN_AGE', 'season_s',  'upb', 'PURPOSE', 'OCC_STAT', 'CHANNEL','PROP', 'CSCORE_B',  'CLTV', 'OLTV',  'cum_ei','cum_eim', 'media_ei_lin')
plots = llply(my_vars, function(my_var){
  plot_act_vs_model2(df, my_var, bucket_count = 10) + ggtitle(my_var)
})
marrangeGrob(plots, nrow = 3, ncol = 4, top = NULL)


#s-curves  
buckets = cutq(df$upb, seq(0, 1, length.out = 13))
plots = llply(levels(buckets), function(my_level){
  plot_act_vs_model2(df, 'LOAN_AGE', buckets == my_level, bucket_count = 25) + ggtitle(my_level)
})
marrangeGrob(plots, nrow = 3, ncol = 4, top = NULL)

buckets = df$CHANNEL
plots = llply(unique(buckets), function(my_level){
  plot_act_vs_model2(df, 'ei', buckets == my_level, bucket_count = 25) + ggtitle(my_level)
})
marrangeGrob(plots, nrow = 3, ncol = 4, top = NULL)




turn_index = which(df$ei < 0) %in_set% t_index_v
objective_function(df, turn_index)
plot_act_vs_model2(df, 'ei', turn_index, bucket_count = 10)
plot_act_vs_model2(df, 'LOAN_AGE', turn_index, bucket_count = 25)
plot_act_vs_model2(df, 'date', turn_index, bucket_count = 25)
plot_act_vs_model2(df, 'season_s', turn_index, bucket_count = 25)
plot_act_vs_model2(df, 'CLTV', turn_index, bucket_count = 50)
plot_act_vs_model2(df, 'upb', turn_index, bucket_count = 100)
plot_act_vs_model2(df, 'CSCORE_B',turn_index, bucket_count = 10)


my_vars = c('ei', 'LOAN_AGE', 'season_s',  'upb', 'PURPOSE', 'OCC_STAT', 'CHANNEL','PROP', 'CSCORE_B',  'CLTV', 'OLTV',  'cum_ei')
plots = llply(my_vars, function(my_var){
  plot_act_vs_model2(df, my_var, bucket_count = 10) + ggtitle(my_var)
})
marrangeGrob(plots, nrow = 3, ncol = 4, top = NULL)


library(rBayesianOptimization)
turn_obj <- function(turn_low,turn_high, turn_scurve_shift, turn_scurve_slope) {
  
  params_ex = params
  params_ex['turn_low'] = turn_low
  params_ex['turn_high'] = turn_high
  params_ex['turn_scurve_shift'] = turn_scurve_shift
  params_ex['turn_scurve_slope'] = turn_scurve_slope
  
  df[order(date), model_smm := smm_model(.SD, params_ex), by = .(LOAN_ID)]

  list(Score = objective_function(df, index),    Pred = 0)
}
## Set larger init_points and n_iter for better optimization result
OPT_Res <- BayesianOptimization(turn_obj,
                                bounds = list('turn_low' = c(cpr2smm(3), cpr2smm(6)),
                                              'turn_high' = c(cpr2smm(6), cpr2smm(12)),
                                              'turn_scurve_shift' = c(-100, 0),
                                              'turn_scurve_slope' = c(10, 100)),
                                init_points = 4, n_iter = 20,
                                acq = "ei", #ucb, ei, poi
                                kappa = 2.576, eps = 0.0,
                                verbose = TRUE)

#1D optimization variable -------------
turn_obj_1d <- function(x, param_name, param_index = 0) {
  params_mod = params
  
  if(param_index == 0){
    params_mod[[param_name]] = x
  }else{
    params_mod[[param_name]][param_index] = x
  }
  
  df[t_index_v, model_smm := smm_model(.SD, params_mod)]

  objective_function(df, index)
}
optimize(function(x) turn_obj_1d(x,"turn_low"),interval = c(cpr2smm(4), cpr2smm(6)), maximum = TRUE) #2.000866

#grid search 
res = ldply(seq(10, 50, by = 5), function(x) c(x, turn_obj_1d(x, "turn_scurve_slope")) )
ggplot(res, aes(V1, V2)) + geom_point() + geom_line()


### GRID search
#'media_low' = 0.7, 'media_high' = 1.6, 'media_scurve_shift' = -0.45, 'media_scurve_slope' = -0.1,
param_grid = expand.grid(media_low = seq(0.5, 1.0, length.out = 10), media_high = seq(1.0, 2.0, length.out = 10))
res = ldply(seq(nrow(param_grid)), function(i){
  print(i)
  
  my_params = params
  my_params[['media_low']] = param_grid$media_low[i]
  my_params[['media_high']] = param_grid$media_high[i]
  
  df[, model_smm := smm_model(.SD, my_params)]

   data.frame(objective = objective_function(df, t_index_v), 
              media_low = param_grid$media_low[i], 
              media_high =  param_grid$media_high[i])
  #data.frame(x, deviance = summary(glm.model)$deviance)
})
setDT(res)
res[objective==max(objective)]
ggplot(res, aes(media_scurve_shift, media_scurve_slope, fill = (objective-min(objective)), label = sprintf("%.4f",objective-min(objective) ) )) + geom_tile() +  scale_fill_custom('mixed', discrete = FALSE) + theme_bw() +  geom_text()
ggplot(res, aes(media_scurve_shift, media_scurve_slope, fill = (objective), label = sprintf("%.4f",objective ) )) + geom_tile() +  scale_fill_custom('mixed', discrete = FALSE) + theme_bw() +  geom_text()




#using R optimization --------------
turn_obj_ex <- function(x, param_names, params) {
  params_in = params
  for(i in 1:length(x)){
    params_in[[param_names[i]]] =x[i] 
  }
  return( -turn_objective_function(params_in))
}

refi_obj_ex <- function(x, param_names, params) {
  params_in = params
  for(i in 1:length(x)){
    params_in[[param_names[i]]] =x[i] 
  }
  return( -refi_objective_function(params_in))
}

#param_names = c('refi_scurve_shift', 'refi_scurve_slope', 'refi_low', 'refi_high')
param_names =c('media_low', 'media_high', 'media_scurve_shift', 'media_scurve_slope')
init_params = sapply(param_names, function(x) params[[x]])
optim(init_params, function(x)refi_obj_ex(x, param_names, params), method  = "Nelder-Mead", control = list(trace = 6, maxit = 600)) #2.000866

#using dfoptim -------------- "-8.06527"
library(dfoptim)
hjk(init_params,  function(x)refi_obj_ex(x, param_names, params), control = list(maxfeval = 100, info = TRUE))
mads(init_params, function(x)refi_obj_ex(x, param_names, params), control = list(maxfeval = 100, info = TRUE))
```

#Burnout optimization
```{r burnout_parameters}
library(gam)

index   = sample.int(nrow(df), 2e6)
index_v = sample.int(nrow(df), 2e6) %!in_set% index

#Simple cum incentive with LGB
# 10bp is the best threshold  -----------------
res = ldply(seq(0, 50, by = 1), function(x){
  
  df[order(date), cum_ei_test  := 0.01*cumsum(pmax(0, ei - x)), by =.(LOAN_ID)]
  my_vars = c(lgb_vars, 'cum_ei_test')
  dtrain.t <- lgb.Dataset(                     data.matrix(df[index,   my_vars,  with = FALSE]), label = df$po_ind[index],    init_score = logit(df$po_pred[index]))
  dtest.t  <- lgb.Dataset.create.valid(dtrain, data.matrix(df[index_v, my_vars,  with = FALSE]), label = df$po_ind[index_v],  init_score = logit(df$po_pred[index_v]))

  model.lgb.test = lgb.train(params = list(objective = "binary"), data = dtrain.t, learning_rate = 0.01,
                        valids = list(test = dtest.t),
                        num_threads = 4, nrounds = 1000,  eval_freq = 50, early_stopping_rounds = 100, force_row_wise=TRUE)
  
  cv_error = as.numeric(model.lgb.test$record_evals$test$binary_logloss$eval)
  #ggplot(data.frame( i = seq(length(cv_error)), cv_error ), aes(i, cv_error)) + geom_line()
  
  #po_pred.test = logistic(predict(model.lgb.test, data.matrix(df[,.(ei, cum_ei_test)]), rawscore=TRUE) +  logit(df$po_pred))
  #plot_profile(po_pred.test, df$po_ind, df$cum_ei_test)
  #plot_profile(df$po_pred, df$po_ind, df$cum_ei_test)
  
  data.frame(x, it = model.lgb.test$best_iter, error = cv_error[model.lgb.test$best_iter], max_error = max(cv_error), min_error = min(cv_error) )
  #data.frame(x, deviance = summary(glm.model)$deviance)
})
setDT(res)
res[error == min(error)]
ggplot(res, aes(x, error)) + geom_line() + geom_point() + geom_vline(xintercept = res[error == min(error), x], linetype = 'dashed')
ggplot(res, aes(x, it)) + geom_line() + geom_point() 

#Burnout S-Curve  -----------------
burn_params = expand.grid(shift = seq(0, 100, by = 1), width = seq(5, 50, by = 1))
res = ldply(seq(nrow(burn_params)), function(i){
  
  df[order(date), cum_eim_test  := cumsum(logistic( (ei - burn_params$shift[i])/burn_params$width[i] )), by =.(LOAN_ID)]
  my_vars = c(lgb_vars, 'cum_eim_test')
  dtrain.t <- lgb.Dataset(                       data.matrix(df[index,   my_vars, with = FALSE]), label = df$po_ind[index],    init_score = logit(df$po_pred[index]))
  dtest.t  <- lgb.Dataset.create.valid(dtrain.t, data.matrix(df[index_v, my_vars, with = FALSE]), label = df$po_ind[index_v],  init_score = logit(df$po_pred[index_v]))

  model.lgb.test = lgb.train(params = list(objective = "binary"), data = dtrain.t, learning_rate = 0.01,
                        valids = list(test = dtest.t),
                        num_threads = 4, nrounds = 1000,  eval_freq = 50, early_stopping_rounds = 100, force_row_wise=TRUE)
  
  cv_error = as.numeric(model.lgb.test$record_evals$test$binary_logloss$eval)
  #ggplot(data.frame( i = seq(length(cv_error)), cv_error ), aes(i, cv_error)) + geom_line()
  
  #po_pred.test = logistic(predict(model.lgb.test, data.matrix(df[,.(ei, cum_ei_test)]), rawscore=TRUE) +  logit(df$po_pred))
  #plot_profile(po_pred.test, df$po_ind, df$cum_ei_test)
  #plot_profile(df$po_pred, df$po_ind, df$cum_ei_test)
  
  data.frame(i, it = model.lgb.test$best_iter, error = cv_error[model.lgb.test$best_iter], max_error = max(cv_error), min_error = min(cv_error), shift = burn_params$shift[i], width = burn_params$width[i] )
})
setDT(res)
res[error == min(error)]
ggplot(res, aes(shift, width, fill = 100*(error/min(error)-1), label = sprintf("%.4f", 100*(error/min(error) - 1) ) )) + geom_tile() +  scale_fill_custom('mixed', discrete = FALSE) + theme_bw()# +  geom_text()
ggplot(res, aes(shift, width, fill = it, label = sprintf("%d", it) )) + geom_tile() + scale_fill_custom('mixed', discrete = FALSE)# + geom_text()




#Simple cum incentive
# 10bp is the best threshold  -----------------
res = ldply(seq(0, 20, by = 2), function(x){
  print(x)
  df[order(date), cum_ei  := 0.01*cumsum(pmax(x, ei)), by =.(LOAN_ID)]
  gam.model = gam(po_ind ~ s(cum_ei) , data = df[index,.(po_ind, cum_ei)], binomial(link = "logit"), offset = logit(df$po_pred[index]), weights =df$sbal[index]/sum(df$sbal[index]) )
  #gam.model = gam(po_ind ~ lo(cum_ei, ei) , data = df[index,.(po_ind, cum_ei, ei)], binomial(link = "logit"), offset = logit(df$po_pred[index]), weights =df$sbal[index]/sum(df$sbal[index]) )
  #plot(gam.model)
  sum.model = summary(gam.model)
  data.frame(x, deviance = sum.model$deviance, null.deviance = sum.model$null.deviance)
  #data.frame(x, deviance = summary(glm.model)$deviance)
})
setDT(res)
res[deviance == min(deviance)]
ggplot(res, aes(x, deviance/null.deviance)) + geom_line() + geom_vline(xintercept = res[deviance == min(deviance), x], linetype = 'dashed')

#Burnout S-Curve
# 10bp is the best threshold  -----------------
burn_params = expand.grid(shift = seq(100, 100, by = 10), width = seq(4, 16, by = 2))
res = ldply(seq(nrow(burn_params)), function(i){
  print(i)
  
  df[order(date), cum_eim  := cumsum(logistic( (ei - burn_params$shift[i])/burn_params$width[i] )), by =.(LOAN_ID)]
   gam.model = gam(po_ind ~ s(cum_eim) , data = df[index,.(po_ind, cum_eim)], binomial(link = "logit"), offset = logit(df$po_pred[index]))
  #gam.model = gam(po_ind ~ s(cum_eim) , data = df[index,.(po_ind, cum_eim)], binomial(link = "logit"), offset = logit(df$po_pred[index]), weights =df$sbal[index]/sum(df$sbal[index]) )

  #plot(gam.model)
  sum.model = summary(gam.model)
  data.frame(deviance = sum.model$deviance, null.deviance = sum.model$null.deviance, shift = burn_params$shift[i], width = burn_params$width[i])
  #data.frame(x, deviance = summary(glm.model)$deviance)
})
setDT(res)
res[deviance == min(deviance)]
ggplot(res[deviance<null.deviance], aes(shift, width, fill = 1-deviance/null.deviance, label = sprintf("%.1f", null.deviance - deviance) )) + 
  geom_tile() + geom_text() +  scale_fill_custom('mixed', discrete = FALSE)

ggplot(df[LOAN_ID == '000097473153'], aes(date, cum_eim)) + geom_line()
ggplot(df[LOAN_ID == '000097473153'], aes(date, ei_1m)) + geom_line()
```


