---
title: "FNMA Loan Level Data"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
rm(list = ls())

knitr::opts_chunk$set(echo = TRUE, fig.width = 8, fig.height = 5, dpi = 240)
options(warn=-1)

library(plyr)
library(foreach)
library(data.table)
library(stringi)
library(ggplot2)
library(gridExtra)
library(zip)
library(forcats)
library(lubridate)
library(R.utils)

working_folder = 'D:/Github/KaggleSandbox'
#working_folder = file.path(Sys.getenv("HOME"), 'source/github/KaggleSandbox/')
source(file.path(working_folder, '/Utils/common.R'))

```


## Load FNMA loan data
load 1% of loans
```{r load_data}
data_folder = 'W:/loan_level/fnma/raw'

### Define the Loan Performance table headers
lppub_column_names <- c("POOL_ID", "LOAN_ID", "ACT_PERIOD", "CHANNEL", "SELLER", "SERVICER",
                        "MASTER_SERVICER", "ORIG_RATE", "CURR_RATE", "ORIG_UPB", "ISSUANCE_UPB",
                        "CURRENT_UPB", "ORIG_TERM", "ORIG_DATE", "FIRST_PAY", "LOAN_AGE",
                        "REM_MONTHS", "ADJ_REM_MONTHS", "MATR_DT", "OLTV", "OCLTV",
                        "NUM_BO", "DTI", "CSCORE_B", "CSCORE_C", "FIRST_FLAG", "PURPOSE",
                        "PROP", "NO_UNITS", "OCC_STAT", "STATE", "MSA", "ZIP", "MI_PCT",
                        "PRODUCT", "PPMT_FLG", "IO", "FIRST_PAY_IO", "MNTHS_TO_AMTZ_IO",
                        "DLQ_STATUS", "PMT_HISTORY", "MOD_FLAG", "MI_CANCEL_FLAG", "Zero_Bal_Code",
                        "ZB_DTE", "LAST_UPB", "RPRCH_DTE", "CURR_SCHD_PRNCPL", "TOT_SCHD_PRNCPL",
                        "UNSCHD_PRNCPL_CURR", "LAST_PAID_INSTALLMENT_DATE", "FORECLOSURE_DATE",
                        "DISPOSITION_DATE", "FORECLOSURE_COSTS", "PROPERTY_PRESERVATION_AND_REPAIR_COSTS",
                        "ASSET_RECOVERY_COSTS", "MISCELLANEOUS_HOLDING_EXPENSES_AND_CREDITS",
                        "ASSOCIATED_TAXES_FOR_HOLDING_PROPERTY", "NET_SALES_PROCEEDS",
                        "CREDIT_ENHANCEMENT_PROCEEDS", "REPURCHASES_MAKE_WHOLE_PROCEEDS",
                        "OTHER_FORECLOSURE_PROCEEDS", "NON_INTEREST_BEARING_UPB", "PRINCIPAL_FORGIVENESS_AMOUNT",
                        "ORIGINAL_LIST_START_DATE", "ORIGINAL_LIST_PRICE", "CURRENT_LIST_START_DATE",
                        "CURRENT_LIST_PRICE", "ISSUE_SCOREB", "ISSUE_SCOREC", "CURR_SCOREB",
                        "CURR_SCOREC", "MI_TYPE", "SERV_IND", "CURRENT_PERIOD_MODIFICATION_LOSS_AMOUNT",
                        "CUMULATIVE_MODIFICATION_LOSS_AMOUNT", "CURRENT_PERIOD_CREDIT_EVENT_NET_GAIN_OR_LOSS",
                        "CUMULATIVE_CREDIT_EVENT_NET_GAIN_OR_LOSS", "HOMEREADY_PROGRAM_INDICATOR",
                        "FORECLOSURE_PRINCIPAL_WRITE_OFF_AMOUNT", "RELOCATION_MORTGAGE_INDICATOR",
                        "ZERO_BALANCE_CODE_CHANGE_DATE", "LOAN_HOLDBACK_INDICATOR", "LOAN_HOLDBACK_EFFECTIVE_DATE",
                        "DELINQUENT_ACCRUED_INTEREST", "PROPERTY_INSPECTION_WAIVER_INDICATOR",
                        "HIGH_BALANCE_LOAN_INDICATOR", "ARM_5_YR_INDICATOR", "ARM_PRODUCT_TYPE",
                        "MONTHS_UNTIL_FIRST_PAYMENT_RESET", "MONTHS_BETWEEN_SUBSEQUENT_PAYMENT_RESET",
                        "INTEREST_RATE_CHANGE_DATE", "PAYMENT_CHANGE_DATE", "ARM_INDEX",
                        "ARM_CAP_STRUCTURE", "INITIAL_INTEREST_RATE_CAP", "PERIODIC_INTEREST_RATE_CAP",
                        "LIFETIME_INTEREST_RATE_CAP", "MARGIN", "BALLOON_INDICATOR",
                        "PLAN_NUMBER", "FORBEARANCE_INDICATOR", "HIGH_LOAN_TO_VALUE_HLTV_REFINANCE_OPTION_INDICATOR",
                        "DEAL_NAME", "RE_PROCS_FLAG", "ADR_TYPE", "ADR_COUNT", "ADR_UPB")
lppub_column_classes <- c("character", "character", "character", "character", "character", "character",
                          "character", "numeric", "numeric", "numeric", "numeric",
                          "numeric", "numeric", "character", "character", "numeric", "numeric",
                          "numeric", "character", "numeric", "numeric", "character", "numeric",
                          "numeric", "numeric", "character", "character", "character",
                          "numeric", "character", "character", "character", "character",
                          "numeric", "character", "character", "character", "character",
                          "numeric", "character", "character", "character", "character",
                          "character", "character", "numeric", "character", "numeric",
                          "numeric", "numeric", "character", "character", "character",
                          "numeric", "numeric", "numeric", "numeric", "numeric", "numeric",
                          "numeric", "numeric", "numeric", "numeric", "numeric", "character",
                          "numeric", "character", "numeric", "numeric", "numeric", "numeric",
                          "numeric", "numeric", "character", "numeric", "numeric", "numeric",
                          "numeric", "character", "numeric", "character", "numeric", "character",
                          "numeric", "numeric", "character", "character", "numeric", "numeric",
                          "numeric", "numeric", "numeric", "numeric", "numeric", "numeric",
                          "numeric", "numeric", "numeric", "numeric", "numeric", "character",
                          "character", "character", "character", "character",
						  "character", "numeric", "numeric")


files = list.files(data_folder,glob2rx('2016*.bz2'), full.names = TRUE )
select_columns = c(
  'LOAN_ID',	'ACT_PERIOD',	'CHANNEL',	'SELLER',	'SERVICER',	'MASTER_SERVICER',	'ORIG_RATE',	'CURR_RATE',	'ORIG_UPB',	'ISSUANCE_UPB',	'CURRENT_UPB',	'ORIG_TERM',	'ORIG_DATE',	'FIRST_PAY',	'LOAN_AGE',	'REM_MONTHS',	'ADJ_REM_MONTHS',	'MATR_DT',	'OLTV',	'OCLTV',	'NUM_BO',	'DTI',	'CSCORE_B',	'CSCORE_C',	'FIRST_FLAG',	'PURPOSE',	'PROP',	'NO_UNITS',	'OCC_STAT',	'STATE',	'MSA',	'MI_PCT',	'PRODUCT',	'PPMT_FLG',	'IO', 'DLQ_STATUS', 'MOD_FLAG',	'MI_CANCEL_FLAG',	'Zero_Bal_Code',	'ZB_DTE',	'LAST_UPB', 'SERV_IND
')


### Load new origination
df = foreach(file_name = files[1], .combine = rbind) %do% {
  print(file_name)
  temp = fread(file_name, sep = "|", col.names = lppub_column_names, colClasses = lppub_column_classes, select = select_columns)
  #temp[, c(drop_columns):=NULL]
  #gc()
  return(temp)
}

df[, date:= as.Date(stri_join('01',ACT_PERIOD), format = '%d%m%Y')]
df[, date_year:= year(date)]

df[, orig_date:= as.Date(stri_join('01',ORIG_DATE), format = '%d%m%Y')]
df[, orig_year:= year(orig_date)]

df[, balance := pmax(ORIG_UPB, CURRENT_UPB, na.rm = TRUE)]
#df[LOAN_ID == '000098915594',.(date, CURRENT_UPB, LOAN_AGE)]
#df[,duplicated:=duplicated(LOAN_ID)]
df[, po_ind := as.numeric(Zero_Bal_Code == '01')]
#temp
```

## show data

```{r load_data}
df_agg = df[,.(.N, bal = sum(CURRENT_UPB, na.rm = TRUE), po = mean(po_ind)), by=.(date)]

ggplot(df_agg, aes(date, N)) + geom_point()
ggplot(df_agg, aes(date, po)) + geom_point() + geom_line()

```



