---
title: "Enviroment Monitoring"
output: html_document
date: '2022-05-25'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(influxdbclient)
library(ggplot2)
library(data.table)
library(plyr)
library(stringi)
library(lubridate)
library(plotly)

temp_c2f <- function(temp_c) {  temp_c * 1.8 + 32 }
```

## R Markdown

```{r cars}
# You can generate an API token from the "API Tokens Tab" in the UI
token = "bV2rtj74ZN2OVtDC-hibmOY3FujyGauOggfkt9OlC4Z4bx3iy1trt-5QLZvEYrbltWuEggEU_rLNKwkzDvzM6Q=="

client <- InfluxDBClient$new(url = "http://192.168.1.2:8086",
    token = token,
    org = "Home")

client$health()
client$ready()
```

## Load Tempreture Data
Changed Air Filter 5/29/2022

```{r load_data, echo=FALSE}
#tables <- client$query('from(bucket: "home_assistant") |> range(start: -7d)')
#tables <- client$query('from(bucket: "home_assistant")')
my_query = 'from(bucket: "home_assistant")
          |> range(start: -7d)
          |> filter(fn: (r) => r["_measurement"] == "°C")
          |> filter(fn: (r) => r["_field"] == "value")
          |> filter(fn: (r) => r["domain"] == "sensor")
          |> filter(fn: (r) => r["entity_id"] == "temperature_sensor_temperature" or r["entity_id"] == "leak_sensor_temperature" or r["entity_id"] == "temp_bedroom_temperature" or r["entity_id"] == "temp_media_temperature")
          |> filter(fn: (r) => r["friendly_name"] == "Temperature Sensor (Temperature)" or r["friendly_name"] == "Temp Bedroom (Temperature)" or r["friendly_name"] == "Temp Media (Temperature)" or r["friendly_name"] == "Temp Outside (Temperature)")
          |> filter(fn: (r) => r["source"] == "HA")
          |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)
          |> yield(name: "mean")'
tables <- client$query(stri_replace_all(my_query, '', fixed = '\n'))

#X = read.table(readLines(file.csv, warn = FALSE),header=TRUE,sep=”,”)
#X = read.table(readLines(file.choose(), warn = FALSE),header=TRUE,sep=”,”)

num_values = sapply(tables, function(x) is.numeric(x[['_value']]))
str_values = sapply(tables, function(x) is.character(x[['_value']])) 

#df <- data.table(ldply(tables[num_values], data.frame))
df   = rbindlist(tables[num_values], fill=TRUE)
df_s = rbindlist(tables[str_values], fill=TRUE)

#df_s[entity_id == 'lumi_lumi_weather_bff2ef07_temperature']
#df[entity_id == 'lumi_lumi_weather_bff2ef07_temperature']

names(df) <- make.names(names(df))

df[order(time), dt := difftime(time, shift(time), units = 'mins'), by = .(entity_id,X_field)]
df[order(time), dv := X_value - shift(X_value), by = .(entity_id,X_field)]


ggplotly( ggplot(df[X_field == 'value'], aes(time, temp_c2f(X_value), group = friendly_name, color = friendly_name)) + geom_step() + geom_point() )
ggplotly( ggplot(df[X_field == 'value'], aes(time, X_value, group = friendly_name, color = friendly_name)) + geom_step() + geom_point() )
ggplot(df[X_field == 'value'], aes(time, X_value, group = friendly_name, color = friendly_name)) + geom_step() + geom_point()

```


## Load Humidity Data
Changed Air Filter 5/29/2022

```{r load_data, echo=FALSE}
my_query = 'from(bucket: "home_assistant")
  |> range(start: -7d)
  |> filter(fn: (r) => r["_measurement"] == "%")
  |> filter(fn: (r) => r["_field"] == "value")
  |> filter(fn: (r) => r["domain"] == "sensor")
  |> filter(fn: (r) => r["entity_id"] == "temp_media_humidity" or r["entity_id"] == "temp_bedroom_humidity")
  |> filter(fn: (r) => r["friendly_name"] == "Temp Bedroom (Humidity)" or r["friendly_name"] == "Temp Media (Humidity)")
  |> filter(fn: (r) => r["source"] == "HA")
  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)
  |> yield(name: "mean")'
tables <- client$query(stri_replace_all(my_query, '', fixed = '\n'))

num_values = sapply(tables, function(x) is.numeric(x[['_value']]))
str_values = sapply(tables, function(x) is.character(x[['_value']])) 

#df <- data.table(ldply(tables[num_values], data.frame))
df   = rbindlist(tables[num_values], fill=TRUE)
df_s = rbindlist(tables[str_values], fill=TRUE)

#df_s[entity_id == 'lumi_lumi_weather_bff2ef07_temperature']
#df[entity_id == 'lumi_lumi_weather_bff2ef07_temperature']

names(df) <- make.names(names(df))
df[friendly_name == 'Temperature Sensor (Temperature)', friendly_name:= 'Temp Outside (Temperature)']

df[order(time), dt := difftime(time, shift(time), units = 'mins'), by = .(entity_id,X_field)]
df[order(time), dv := X_value - shift(X_value), by = .(entity_id,X_field)]

ggplot(df[X_field == 'value'], aes(time, X_value, group = friendly_name, color = friendly_name)) + geom_step() + geom_point()
ggplot(df[X_field == 'value'], aes(dt, group = friendly_name, fill = friendly_name)) + geom_histogram() + facet_wrap(~friendly_name)


```
