---
title: "H1B Salary"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)

options(datatable.integer64='character')

library(data.table)
library(readxl)
library(ggplot2)
library(stringi)
library(forcats)
library(foreach)
library(wesanderson)

#memory.limit(36000)

working_folder = 'D:/Github/KaggleSandbox/'
#working_folder = file.path(Sys.getenv("HOME"), 'source/github/KaggleSandbox/')

source(file.path(working_folder, 'Utils/common.R'))

```

## Convert Data
```{r convert_data, eval = FALSE}

#files = list.files(file.path(working_folder,'h1b_salary/data'), glob2rx('H-1B_Disclosure_Data_FY*.xlsx'), full.names = TRUE)
files = list.files(file.path(working_folder,'h1b_salary/data'), glob2rx('*.xlsx'), full.names = TRUE)

foreach(file = files) %do% {
  df_temp = read_excel(file)
  fwrite(df_temp, stri_join(file, '.csv') )
  gc(reset=TRUE)
}
```

## Load Data
https://www.foreignlaborcert.doleta.gov/performancedata.cfm
```{r load_data}
keep_columns = c('CASE_STATUS', 'CASE_SUBMITTED', 'DECISION_DATE', 'VISA_CLASS',	
                 'EMPLOYER_NAME', 'EMPLOYER_CITY',	'EMPLOYER_STATE','EMPLOYER_POSTAL_CODE',	'EMPLOYER_COUNTRY', 'JOB_TITLE','SOC_CODE', 'SOC_NAME','SOC_TITLE', 'NAIC_CODE',
                 'TOTAL_WORKERS', 'FULL_TIME_POSITION', 'PREVAILING_WAGE','PW_WAGE_LEVEL',
                 'WAGE_RATE_OF_PAY_FROM',	'WAGE_RATE_OF_PAY_TO', 'WAGE_UNIT_OF_PAY','WILLFUL_VIOLATOR',
                 'WORKSITE_CITY', 'WORKSITE_COUNTY', 'WORKSITE_STATE','ORIGINAL_CERT_DATE', 'filename')


#files = list.files(file.path(working_folder,'h1b_salary/data'), glob2rx('H-1B_Disclosure_Data_FY1*.xlsx.csv'), full.names = TRUE)
files = list.files(file.path(working_folder,'h1b_salary/data'), "^H-1B_Disclosure_Data_FY1[89].*\\.xlsx\\.csv$", full.names = TRUE)

df = foreach(file = files, .combine = function(...) rbind(..., fill = TRUE, use.names = TRUE) ) %do% {
  print(file)
  #df_temp = fread(file, nrows = 1000)
  df_temp = fread(file)
  
  if('WAGE_RATE_OF_PAY_FROM_1' %in% names(df_temp)){
    df_temp[, WAGE_RATE_OF_PAY_FROM := WAGE_RATE_OF_PAY_FROM_1]
    df_temp[, WAGE_RATE_OF_PAY_TO   := WAGE_RATE_OF_PAY_TO_1]
    df_temp[, WAGE_UNIT_OF_PAY      := WAGE_UNIT_OF_PAY_1]
    df_temp[, PREVAILING_WAGE       := PREVAILING_WAGE_1]
    df_temp[, WORKSITE_CITY         := WORKSITE_CITY_1]
    df_temp[, WORKSITE_STATE        := WORKSITE_STATE_1]
    df_temp[, WORKSITE_COUNTY       := WORKSITE_COUNTY_1]
  }
  
  if('NAICS_CODE' %in% names(df_temp)){
    df_temp[, NAIC_CODE := NAICS_CODE]
  }
  df_temp[, DECISION_DATE  := as.character(DECISION_DATE)]
  df_temp[, CASE_SUBMITTED := as.character(CASE_SUBMITTED)]
  
  
  #df_temp[, DECISION_DATE  := as.Date(DECISION_DATE, tryFormats = c("%Y-%m-%d", "%m/%d/%Y", "%Y/%m/%d"))]
  #df_temp[, CASE_SUBMITTED := as.Date(CASE_SUBMITTED, tryFormats = c("%Y-%m-%d", "%m/dm/%Y", "%Y/%m/%d"))]
  
  #tryFormats = c("%Y-%m-%d", "%Y/%m/%d")
  
  df_temp[, filename := basename(file)]
  
  return(df_temp[, keep_columns %in_set% names(df_temp), with = FALSE])
}

df[, .(.N, sum(is.na(NAIC_CODE))), by = .(filename)]
table(df$WILLFUL_VIOLATOR)

df[,  WAGE_RATE_OF_PAY_FROM := as.numeric(stri_replace(WAGE_RATE_OF_PAY_FROM, '', regex = '[$,]', mode = 'all'))]
df[,  WAGE_RATE_OF_PAY_TO   := as.numeric(stri_replace(WAGE_RATE_OF_PAY_TO,   '', regex = '[$,]', mode = 'all'))]
df[,  PREVAILING_WAGE       := as.numeric(stri_replace(PREVAILING_WAGE ,   '', regex = '[$,]', mode = 'all'))]
df[, CASE_SUBMITTED := as.Date(CASE_SUBMITTED, tryFormats = c("%Y-%m-%d", "%m/%d/%Y", "%Y/%m/%d"))]
df[, DECISION_DATE := as.Date(DECISION_DATE, tryFormats = c("%Y-%m-%d", "%m/%d/%Y", "%Y/%m/%d"))]

df[, case_year := year(CASE_SUBMITTED)]
df[is.na(WAGE_RATE_OF_PAY_FROM), .(.N), by = .(filename)]

#


#Meta Data on H-1B visas ----
files = list.files(file.path(working_folder,'h1b_salary/data/datahubexport'), glob2rx('*datahubexport*.csv'), full.names = TRUE)

df_meta = foreach(file = files, .combine = rbind) %do%{  fread(file) }
names(df_meta) <- make.names(names(df_meta))

df_meta[, i_appr := as.numeric(Initial.Approvals)]
df_meta[, i_deni := as.numeric( Initial.Denials)]
df_meta[, c_appr := as.numeric(Continuing.Approvals)]
df_meta[, c_deni := as.numeric( Continuing.Denials)]
df_meta[, year := factor(Fiscal.Year, ordered  = TRUE)]

gc(reset=TRUE)

```

## JC vs NYC

```{r jc_nyc, echo=FALSE}
df[, .(.N), by = .(filename)]
df[, WORKSITE_CITY:= toupper(WORKSITE_CITY)]
df[WORKSITE_CITY == 'NEW YORK CITY', WORKSITE_CITY:= 'NEW YORK']


all_names = unique(df$EMPLOYER_NAME)
jp_names = all_names[grep('(JPMORGAN)', all_names)]
citi_names = all_names[grep('(CITIGROUP|CITIBANK)', all_names)]

#dfs = df[VISA_CLASS=='H-1B', .(EMPLOYER_NAME, CASE_SUBMITTED, CASE_STATUS, JOB_TITLE, SOC_TITLE, WORKSITE_CITY, WORKSITE_STATE, 
#                          WAGE_RATE_OF_PAY_FROM, WAGE_RATE_OF_PAY_TO, WAGE_UNIT_OF_PAY, PREVAILING_WAGE, PW_WAGE_LEVEL)]

dfs = df[VISA_CLASS == "H-1B" & WAGE_UNIT_OF_PAY == 'Year' & EMPLOYER_NAME %in% c(jp_names, citi_names) & WORKSITE_CITY %in% c('JERSEY CITY', 'NEW YORK')]
dfs[, base_pay := 1e-3*pmax(WAGE_RATE_OF_PAY_FROM, WAGE_RATE_OF_PAY_TO, na.rm = TRUE) ]
dfs[, bank := ifelse(EMPLOYER_NAME %in% jp_names, "jpm", 'citi')]

dfs[base_pay > 100, .(.N, mean(base_pay, na.rm = TRUE), max(base_pay, na.rm = TRUE)), by = .(bank, WORKSITE_CITY, PW_WAGE_LEVEL)]

ggplot(dfs, aes(WORKSITE_CITY, base_pay)) + geom_boxplot() + facet_grid(PW_WAGE_LEVEL~bank) + coord_flip()

dfs[base_pay>250, .(EMPLOYER_NAME,JOB_TITLE, SOC_NAME, base_pay, PREVAILING_WAGE, WORKSITE_CITY )]

df_plot = dfs[base_pay>=150, .(WORKSITE_CITY, bank, base_pay)]
ggplot(dfs[base_pay>=200, ], aes(base_pay, group = WORKSITE_CITY, color = WORKSITE_CITY)) + stat_ecdf() + facet_grid(~bank)

dfs[base_pay>=200, .(.N, max_base = max(base_pay), p84_base = quantile(base_pay, 0.84), p85_base = quantile(base_pay, 0.85) ), by =.(WORKSITE_CITY, bank)][order(bank, WORKSITE_CITY)]

dfs[base_pay>=200 & SOC_NAME!="FINANCIAL MANAGERS", .(.N, max_base = max(base_pay), p90_base = quantile(base_pay, 0.92)), by =.(WORKSITE_CITY, bank)][order(bank, WORKSITE_CITY)]


jpm_jc_ecdf = df_plot[WORKSITE_CITY == 'JERSEY CITY' & bank == 'jpm', ecdf(base_pay)]

df_plot[,base_pay_ecdf := ecdf(base_pay)(base_pay), by =.(WORKSITE_CITY, bank)]
df_plot[,base_pay_eq := quantile(base_pay, jpm_jc_ecdf(base_pay)), by =.(WORKSITE_CITY, bank)]

ggplot(df_plot) + geom_step(aes(x = base_pay, y = base_pay_eq,          group = WORKSITE_CITY, color = WORKSITE_CITY)) +  facet_grid(~bank)
ggplot(df_plot[base_pay<200]) + geom_step(aes(x = base_pay, y = 100*(base_pay_eq/base_pay-1), group = WORKSITE_CITY, color = WORKSITE_CITY)) +  facet_grid(~bank) +  geom_hline(yintercept = 0.0, linetype = 'dashed')

#bootstrap
df_boot = foreach(i = seq(100),  .combine = rbind) %do% {
  df_boot_i = df_plot[, .(base_pay_boot = sample(base_pay, .N, replace= TRUE)), by = .(WORKSITE_CITY, bank)]
  df_boot_i[, i:=i]
  
  jpm_jc_ecdf_boot = df_boot_i[WORKSITE_CITY == 'JERSEY CITY' & bank == 'jpm', ecdf(base_pay_boot)]
  df_boot_i[,base_pay_eq := quantile(base_pay_boot, jpm_jc_ecdf_boot(base_pay_boot), names = FALSE), by =.(WORKSITE_CITY, bank)]
}

ggplot(df_boot[WORKSITE_CITY == 'NEW YORK']) + geom_step(aes(x = base_pay_boot, y = base_pay_eq/base_pay_boot, group = i), color = 'blue', alpha = 0.2) +  
  geom_hline(yintercept = 1.0, linetype = 'dashed') +  facet_grid(~bank)

#bootstrap 250
df_boot = foreach(i = seq(100),  .combine = rbind) %do% {
  df_boot_i = df_plot[, .(base_pay_boot = sample(base_pay, .N, replace= TRUE)), by = .(WORKSITE_CITY, bank)]
  
  jpm_jc_ecdf_boot = df_boot_i[WORKSITE_CITY == 'JERSEY CITY' & bank == 'jpm', ecdf(base_pay_boot)]
  #df_boot_i[,base_pay_eq := quantile(base_pay_boot, jpm_jc_ecdf_boot(base_pay_boot), names = FALSE), by =.(WORKSITE_CITY, bank)]
  
  df_boot_i = df_boot_i[,  .(base_pay_eq=quantile(base_pay_boot, jpm_jc_ecdf_boot(250), names = FALSE)), by =.(WORKSITE_CITY, bank)]
  df_boot_i[, i:=i]
}
ggplot(df_boot[WORKSITE_CITY == 'NEW YORK']) + geom_density(aes(base_pay_eq/250), adjust = 1.0) + geom_rug(aes(base_pay_eq/250)) + facet_grid(~bank)
df_boot[WORKSITE_CITY == 'NEW YORK', mean(base_pay_eq/250), by =.(bank)]

#
ggplot(dfs[base_pay>150, ], aes(base_pay, group = WORKSITE_CITY, color = WORKSITE_CITY)) + stat_qq() + facet_grid(~bank)

dfs_agg = dfs[wage > 100, .(.N, avg=mean(wage, na.rm = TRUE), p95 = quantile(wage, p=0.95, na.rm = TRUE), pwage95 = quantile(PREVAILING_WAGE, p=0.95, na.rm = TRUE)), by = .(bank, WORKSITE_CITY, PW_WAGE_LEVEL)]

ggplot(dfs_agg, aes(PW_WAGE_LEVEL, p95, group = WORKSITE_CITY, fill = WORKSITE_CITY)) + geom_bar(stat= 'identity', position = 'dodge') + facet_wrap(~bank)

library(gbm)
library(gridExtra)
library(plyr)
library(forcats)

dfs[, emp_name := factor(bank) ]
dfs[, location := factor(WORKSITE_CITY) ]
dfs[, wage_level := factor(PW_WAGE_LEVEL) ]
dfs[, soc_name_top5 := fct_lump_n(SOC_NAME, 5) ]
dfs[, job_title_top5 := fct_lump_n(JOB_TITLE, 5) ]


formula.all = formula (paste( 'base_pay ~', paste(c('emp_name', 'location', 'wage_level','soc_name_top5', 'job_title_top5'), collapse = '+')) )

dfs_train = dfs[, all.vars(formula.all), with = FALSE] 

model.gbm = gbm(formula.all, 
                data = dfs_train, 
                distribution = 'gaussian',
                n.trees = 2000,
                shrinkage = 0.01, #0.001
                bag.fraction = 0.5,
                interaction.depth = 3,
                cv.folds = 10,
                train.fraction = 1.0,
                n.cores = 4,
                verbose = FALSE)

best_it = gbm.perf(model.gbm, method = 'cv')
plot_gbmiterations(model.gbm)

#show importance
vars.importance = summary(model.gbm, n.trees = best_it, plotit=FALSE) # influence
plot_gbminfluence(vars.importance)
print(vars.importance)
#write.clipboard(vars.importance, sep = '\t')

plots = plot_gbmpartial(model.gbm, best_it, as.character(vars.importance$var), output_type = 'link')
marrangeGrob(plots, nrow=2, ncol=2)

dfs[, base_pay_pred := predict(model.gbm, n.trees = best_it, newdata = .SD)]

ggplot(dfs, aes(base_pay_pred, base_pay)) + geom_point() + facet_wrap(~location)

plot_profile(dfs$base_pay_pred, dfs$base_pay, dfs$JOB_TITLE, error_band = 'norm')

partial(model.gbm, pred.var = 'location', plot = TRUE, train = dfs_train[base_pay > 200], prob = FALSE,ice = TRUE, plot.engine = "ggplot2", n.trees = best_it)
partial(model.gbm, pred.var = 'emp_name', plot = TRUE, train = dfs_train[base_pay > 200], prob = FALSE,ice = TRUE, plot.engine = "ggplot2", n.trees = best_it)

df_test    = dfs_train[location == 'JERSEY CITY' & emp_name  == 'jpm' & base_pay > 100]
df_test_ny = copy(df_test) 
df_test_ny[, location := 'NEW YORK']
#df_test_ny[, emp_name := 'citi']

predict(model.gbm, n.trees = best_it, newdata = df_test_ny) / predict(model.gbm, n.trees = best_it, newdata = df_test)

df_test[, wage_pred    :=  predict(model.gbm, n.trees = best_it, newdata = df_test)]
df_test[, wage_pred_ny :=  predict(model.gbm, n.trees = best_it, newdata = df_test_ny)]

ggplot(df_test, aes(wage_pred, wage_pred_ny/wage_pred - 1)) + geom_point()
```

## Plot statistics

```{r plot_stat, echo=FALSE}

df_meta_year = df_meta[, .(.N, 
                           i_appr = sum(i_appr, na.rm = TRUE),
                           i_deni = sum(i_deni, na.rm = TRUE),
                           c_appr = sum(c_appr, na.rm = TRUE), 
                           c_deni = sum(c_deni, na.rm = TRUE)), by = .(year)]

df_meta_year[, t_deni := i_deni + c_deni]
df_meta_year[, t_appr := i_appr + c_appr]
df_meta_year[, t_aply := t_deni + t_appr]

ggplot(melt(df_meta_year, id.vars = 'year')[variable!= 'N'], aes(year,   value, group =  variable, color = variable)) + geom_line()

#deni ratio #307,653 - total approval
ggplot(df_meta_year, aes(year, t_deni/(t_appr + t_deni) )) + geom_point() + geom_line()
ggplot(df_meta_year, aes(year, i_deni/(i_appr + i_deni) )) + geom_point() + geom_line()
ggplot(df_meta_year, aes(year, c_deni/(c_appr + c_deni) )) + geom_point() + geom_line()
ggplot(df_meta_year, aes(year, t_deni + t_appr )) + geom_point() + geom_line()
ggplot(df_meta_year, aes(year, t_appr )) + geom_point() + geom_line()

#ggplot(df_meta_year) + geom_line(aes(year, i_appr)) + geom_line(aes(year, t_deni))

df_meta[order(c_appr)]

```

## JPM Wages

H-1B visas 649083 in 2019
```{r plot_wages, echo=FALSE}

table(df$WAGE_UNIT_OF_PAY_1, df$VISA_CLASS)

dfs = df[VISA_CLASS=='H-1B', .(EMPLOYER_NAME, CASE_SUBMITTED, CASE_STATUS, JOB_TITLE, SOC_TITLE, WORKSITE_CITY, WORKSITE_STATE, 
                          WAGE_RATE_OF_PAY_FROM, WAGE_RATE_OF_PAY_TO, WAGE_UNIT_OF_PAY, PREVAILING_WAGE, PW_UNIT_OF_PAY, PW_WAGE_LEVEL)]

all_names = unique(df$EMPLOYER_NAME)
jp_names = all_names[grep('(JPMORGAN)', all_names)]
citi_names = all_names[grep('(CITIGROUP|CITIBANK)', all_names)]
luxsoft_names =  all_names[grep('(LUXOFT USA|DXC TECHNOLOGY SERVICES LLC)', all_names)]

df_agg = df[, .(.N, med = median(1e-3*WAGE_RATE_OF_PAY_FROM,  na.rm = TRUE),  p80 = quantile(1e-3*WAGE_RATE_OF_PAY_FROM, probs = 0.8, na.rm = TRUE, names = FALSE)), by =.(EMPLOYER_NAME)]

ggplot(df_agg[N>200 & p80 > 150], aes(fct_reorder(EMPLOYER_NAME, p80), p80)) + geom_bar(stat = 'identity') +  coord_flip()


dfs[EMPLOYER_NAME %in% jp_names][order(-WAGE_RATE_OF_PAY_FROM)]

#table(dfs[EMPLOYER_NAME %in% jp_names, WAGE_UNIT_OF_PAY_1]) #only annual pays

df[is.na(WAGE_RATE_OF_PAY_FROM), .(.N), by = .(filename)]

ggplot(df[EMPLOYER_NAME %in% jp_names], aes(1e-3*WAGE_RATE_OF_PAY_FROM, group = CASE_STATUS, color = CASE_STATUS)) + stat_ecdf() + facet_wrap(~case_year)
ggplot(df[EMPLOYER_NAME %in% jp_names], aes(1e-3*WAGE_RATE_OF_PAY_FROM, group = CASE_STATUS, color = CASE_STATUS)) + stat_ecdf()

ggplot(df[EMPLOYER_NAME %in% jp_names], aes(CASE_SUBMITTED, 1e-3*WAGE_RATE_OF_PAY_FROM, color = CASE_STATUS)) + geom_point(alpha = 0.3)

ggplot(df[EMPLOYER_NAME %in% citi_names], aes(CASE_SUBMITTED, 1e-3*WAGE_RATE_OF_PAY_FROM, color = CASE_STATUS)) + geom_point(alpha = 0.3)

ggplot(df[EMPLOYER_NAME %in% citi_names & CASE_STATUS  == 'CERTIFIED'], aes(SOC_TITLE, 1e-3*WAGE_RATE_OF_PAY_FROM)) + geom_boxplot() + coord_flip()
ggplot(df[EMPLOYER_NAME %in% jp_names & CASE_STATUS  == 'CERTIFIED'], aes(SOC_TITLE, 1e-3*WAGE_RATE_OF_PAY_FROM)) + geom_boxplot() + coord_flip()

ggplot(df[CASE_STATUS  == 'CERTIFIED' & EMPLOYER_NAME %in% c(emp_set,luxsoft_names) ], aes(EMPLOYER_NAME, 1e-3*WAGE_RATE_OF_PAY_FROM)) + geom_boxplot() + coord_flip()

#LUXsoft
ggplot(df[EMPLOYER_NAME %in% luxsoft_names & CASE_STATUS  == 'CERTIFIED'], aes(DECISION_DATE, 1e-3*WAGE_RATE_OF_PAY_FROM)) + geom_point() + facet_wrap(~SOC_TITLE)

ggplot(df[EMPLOYER_NAME %in% luxsoft_names & CASE_STATUS  == 'CERTIFIED'], aes(SOC_TITLE, 1e-3*WAGE_RATE_OF_PAY_FROM)) + geom_boxplot() + coord_flip()

ggplot(df[EMPLOYER_NAME %in% luxsoft_names & CASE_STATUS  == 'CERTIFIED'], aes(WORKSITE_CITY)) + geom_bar()

ggplot(df[EMPLOYER_NAME %in% luxsoft_names & CASE_STATUS  == 'CERTIFIED'], aes( 1e-3*WAGE_RATE_OF_PAY_FROM, group = EMPLOYER_NAME, fill = EMPLOYER_NAME)) + geom_density(alpha = 0.5)


df[EMPLOYER_NAME %in% citi_names][order(-WAGE_RATE_OF_PAY_FROM)][1:100, .(CASE_SUBMITTED,EMPLOYER_NAME, JOB_TITLE, SOC_NAME,PREVAILING_WAGE,WAGE_RATE_OF_PAY_FROM, WORKSITE_CITY)]
df[EMPLOYER_NAME %in% luxsoft_names & WORKSITE_STATE == 'TX'][order(-WAGE_RATE_OF_PAY_FROM)][1:100, .(CASE_SUBMITTED,EMPLOYER_NAME, JOB_TITLE, SOC_NAME,PREVAILING_WAGE,WAGE_RATE_OF_PAY_FROM, WORKSITE_CITY)]
```

## Plot Wages

H-1B visas 649083 in 2019
```{r plot_wages, echo=FALSE}

table(df$WAGE_UNIT_OF_PAY_1, df$VISA_CLASS)

dfs = df[VISA_CLASS== 'H-1B', .(EMPLOYER_NAME, CASE_SUBMITTED, CASE_STATUS, JOB_TITLE, SOC_TITLE, TOTAL_WORKER_POSITIONS, WORKSITE_CITY_1, WORKSITE_STATE_1 , 
                          WAGE_RATE_OF_PAY_FROM_1, WAGE_RATE_OF_PAY_TO_1, WAGE_UNIT_OF_PAY_1, PREVAILING_WAGE_1, PW_UNIT_OF_PAY_1, PW_WAGE_LEVEL_1)]

dfs[EMPLOYER_NAME %in% c("JPMORGAN CHASE & CO.", "JPMORGAN CHASE &AMP; CO.")][order(-WAGE_RATE_OF_PAY_FROM_1)]

ggplot(dfs[EMPLOYER_NAME %in% c("JPMORGAN CHASE & CO.", "JPMORGAN CHASE &AMP; CO.")], aes(1e-3*WAGE_RATE_OF_PAY_FROM_1, group = CASE_STATUS, color = CASE_STATUS)) + stat_ecdf()
ggplot(dfs[EMPLOYER_NAME %in% c("JPMORGAN CHASE & CO.", "JPMORGAN CHASE &AMP; CO.")], aes(1e-3*WAGE_RATE_OF_PAY_FROM_1, group = CASE_STATUS, color = CASE_STATUS)) + stat_ecdf()


dfs[, max_wage := 1e-3*pmax(WAGE_RATE_OF_PAY_TO_1, WAGE_RATE_OF_PAY_FROM_1, na.rm = TRUE)]

largest_employers = dfs[,.(.N), by =.(EMPLOYER_NAME)][N>1000, EMPLOYER_NAME]

largest_employers[grep('JPMORGAN', largest_employers)]

ggplot(dfs[EMPLOYER_NAME %in% largest_employers,.(.N), by =.(EMPLOYER_NAME, CASE_STATUS)], aes(EMPLOYER_NAME, N, group = CASE_STATUS, fill = CASE_STATUS)) + 
  geom_bar(stat = 'identity') + coord_flip()

ggplot(dfs[EMPLOYER_NAME %in% largest_employers & WAGE_UNIT_OF_PAY_1 == 'Year'], aes(EMPLOYER_NAME, 1e-3*WAGE_RATE_OF_PAY_FROM_1)) + 
  geom_point(alpha = 0.2) + geom_jitter() +  coord_flip()

ggplot(dfs[EMPLOYER_NAME %in% largest_employers & WAGE_UNIT_OF_PAY_1 == 'Year'], aes(EMPLOYER_NAME, 1e-3*pmax(WAGE_RATE_OF_PAY_TO_1, WAGE_RATE_OF_PAY_FROM_1, na.rm = TRUE))) + 
  geom_boxplot() +  coord_flip()  + geom_hline(yintercept = 200, color = 'red', linetype = 'dashed')

emp_set = c("JPMORGAN CHASE & CO.", "GOOGLE LLC", "FACEBOOK INC.", "GOLDMAN SACHS SERVICES LLC", "WELLS FARGO BANK, N.A.", "CITADEL AMERICAS LLC",
            'BANK OF AMERICA N.A.', 'DEUTSCHE BANK SECURITIES INC.', 'CITIBANK, N.A.', 'U.S. BANK NATIONAL ASSOCIATION')

ggplot(dfs[EMPLOYER_NAME %in% emp_set & WAGE_UNIT_OF_PAY_1 == 'Year'], aes(EMPLOYER_NAME, max_wage)) + 
  geom_violin(adjust = 0.5) +  coord_flip()  + geom_hline(yintercept = 200, color = 'red', linetype = 'dashed')

ggplot(dfs[EMPLOYER_NAME %in% emp_set & WAGE_UNIT_OF_PAY_1 == 'Year'], aes(max_wage, group = EMPLOYER_NAME, fill = EMPLOYER_NAME)) + 
  geom_density(adjust = 1) +  geom_vline(xintercept = 200, color = 'red', linetype = 'dashed') + facet_wrap(~EMPLOYER_NAME) + theme (legend.position = 'none')

ggplot(dfs[EMPLOYER_NAME %in% emp_set & WAGE_UNIT_OF_PAY_1 == 'Year'], aes(max_wage, group = EMPLOYER_NAME, fill = EMPLOYER_NAME)) + 
  geom_density(adjust = 1) +  geom_vline(xintercept = 200, color = 'red', linetype = 'dashed') + facet_wrap(~EMPLOYER_NAME) + theme (legend.position = 'none')

ggplot(dfs[EMPLOYER_NAME %in% emp_set & WAGE_UNIT_OF_PAY_1 == 'Year'], aes(max_wage, group = EMPLOYER_NAME, fill = EMPLOYER_NAME)) + 
  geom_histogram(binwidth = 10) +  geom_vline(xintercept = 200, color = 'red', linetype = 'dashed') + facet_wrap(~EMPLOYER_NAME, scales = 'free_y') + theme (legend.position = 'none')

ggplot(dfs[EMPLOYER_NAME %in% emp_set & WAGE_UNIT_OF_PAY_1 == 'Year'], aes(max_wage, group = EMPLOYER_NAME, color = EMPLOYER_NAME)) + 
  stat_ecdf() +  geom_vline(xintercept = 200, color = 'red', linetype = 'dashed') + facet_wrap(~EMPLOYER_NAME, scales = 'free_y') + theme (legend.position = 'none')

emp_set2 = c('HARTFORD HEALTHCARE MEDICAL GROUP, INC.', 'MARSHFIELD CLINIC', 'ALLEGHENY CLINIC', 'HSHS MEDICAL GROUP, INC.', "JPMORGAN CHASE & CO.", 'UNIVERSITY OF PITTSBURGH PHYSICIANS')

ggplot(dfs[EMPLOYER_NAME %in% emp_set2 & WAGE_UNIT_OF_PAY_1 == 'Year'], aes(max_wage, group = EMPLOYER_NAME, color = EMPLOYER_NAME)) + 
  stat_ecdf() +  geom_vline(xintercept = 200, color = 'red', linetype = 'dashed')  

ggplot(dfs[EMPLOYER_NAME == "JPMORGAN CHASE & CO." & WAGE_UNIT_OF_PAY_1 == 'Year' & WORKSITE_STATE_1 %in% c('NEW YORK', 'OHIO', 'TEXAS', 'NEW JERSEY')], aes(max_wage, group = WORKSITE_STATE_1, color = WORKSITE_STATE_1)) + 
  stat_ecdf() +  geom_vline(xintercept = 200, color = 'red', linetype = 'dashed')  


dfs[EMPLOYER_NAME ==  "CITADEL AMERICAS LLC"]
dfs[EMPLOYER_NAME ==  "CITADEL ENTERPRISE AMERICAS LLC"]
dfs[EMPLOYER_NAME ==  "JPMORGAN CHASE & CO." & max_wage > 250]
a = dfs[EMPLOYER_NAME ==  "U.S. BANK NATIONAL ASSOCIATION" & WORKSITE_CITY_1 == 'Charlotte']

dfs[EMPLOYER_NAME %in% emp_set & WAGE_UNIT_OF_PAY_1 == 'Year' & CASE_STATUS == 'CERTIFIED', 
    .(.N, mean_wage = mean(max_wage, na.rm = TRUE),
      q50_wage = quantile(max_wage, 0.50, na.rm = TRUE, names = FALSE),
      q90_wage = quantile(max_wage, 0.90, na.rm = TRUE, names = FALSE),
      q99_wage = quantile(max_wage, 0.99, na.rm = TRUE, names = FALSE)), by = .(EMPLOYER_NAME)]

df_wage = dfs[WAGE_UNIT_OF_PAY_1 == 'Year' & CASE_STATUS == 'CERTIFIED', 
    .(.N, mean_wage = mean(max_wage, na.rm = TRUE),
      q50_wage = quantile(max_wage, 0.50, na.rm = TRUE, names = FALSE),
      q90_wage = quantile(max_wage, 0.90, na.rm = TRUE, names = FALSE),
      q99_wage = quantile(max_wage, 0.99, na.rm = TRUE, names = FALSE)), by = .(EMPLOYER_NAME)]

a = dfs[WAGE_UNIT_OF_PAY_1 == 'Year' & CASE_STATUS == 'CERTIFIED', 
    .(mean_wage = mean(max_wage, na.rm = TRUE),
      q50_wage = quantile(max_wage, 0.50, na.rm = TRUE, names = FALSE),
      q90_wage = quantile(max_wage, 0.90, na.rm = TRUE, names = FALSE),
      q99_wage = quantile(max_wage, 0.99, na.rm = TRUE, names = FALSE)), by = .(WORKSITE_STATE_1)]

df_title = dfs[WAGE_UNIT_OF_PAY_1 == 'Year' & CASE_STATUS == 'CERTIFIED', 
    .(.N, mean_wage = mean(max_wage, na.rm = TRUE),
      q50_wage = quantile(max_wage, 0.50, na.rm = TRUE, names = FALSE),
      q90_wage = quantile(max_wage, 0.90, na.rm = TRUE, names = FALSE),
      q99_wage = quantile(max_wage, 0.99, na.rm = TRUE, names = FALSE)), by = .(SOC_TITLE)]

ggplot(df_title[q50_wage>150], aes(fct_reorder(SOC_TITLE, q90_wage), q90_wage)) + geom_bar(stat = 'identity') + geom_point(aes(fct_reorder(SOC_TITLE, q90_wage), q99_wage), color = 'blue') + coord_flip()

#
best_titles = df_title[q50_wage>150, SOC_TITLE]

ggplot(dfs[WAGE_UNIT_OF_PAY_1 == 'Year' & CASE_STATUS == 'CERTIFIED' & SOC_TITLE %in% best_titles], aes(fct_reorder(SOC_TITLE, max_wage, mean), max_wage)) +  geom_boxplot() + 
  geom_hline(yintercept = 100, color = 'grey', linetype = 'dashed') +
  geom_hline(yintercept = 200, color = 'blue', linetype = 'dashed') + geom_hline(yintercept = 300, color = 'red', linetype = 'dashed') + coord_flip()

dfs[EMPLOYER_NAME == 'CITIBANK, N.A.', ][order(max_wage)][max_wage>=250]

# by state
ggplot(dfs[WAGE_UNIT_OF_PAY_1 == 'Year' & CASE_STATUS == 'CERTIFIED' ], aes(fct_reorder(WORKSITE_STATE_1, max_wage, mean), max_wage)) +  geom_boxplot() + coord_flip() + 
  geom_hline(yintercept = 100, color = 'grey', linetype = 'dashed') +
  geom_hline(yintercept = 200, color = 'blue', linetype = 'dashed') + geom_hline(yintercept = 300, color = 'red', linetype = 'dashed')

```

