---
title: "Store Sales"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)

library(lightgbm)
library(data.table)
library(stringi)
library(ggplot2)
library(gridExtra)
library(plyr)
library(forcats)
library(lubridate)
library(zoo)
#library(mclust)

#setDTthreads(6)
#getDTthreads()

working_folder = 'D:/Github/KaggleSandbox'
#working_folder = file.path(Sys.getenv("HOME"), 'source/github/KaggleSandbox/')

source(file.path(working_folder, 'Utils/common.R'))
```

## Load Data
```{r load_data}
train <- fread(file.path(working_folder,'StoreSales/data/train.csv'), check.names = TRUE)
test  <- fread(file.path(working_folder,'StoreSales/data/test.csv'),  check.names = TRUE)
test[, sales :=NA]
df = rbind(train, test)

train_index = !is.na(df$sales)

df[, date_year  := year(date)]
df[, date_month := month(date)]
df[, month_day_count := days_in_month(date)]
df[, date_day   := day(date)]
df[, date_days_left   := month_day_count - date_day]
df[, date_wday  := wday(date)]
df[, date_float := date_year + (date_month-1 + (date_day - 1)/month_day_count )/12  ]

df[, sales_log  := log(sales + 1)]

df_stores   <- fread(file.path(working_folder,'StoreSales/data/stores.csv'),  check.names = TRUE)
df_oil      <- fread(file.path(working_folder,'StoreSales/data/oil.csv'),  check.names = TRUE)
df_holidays <- fread(file.path(working_folder,'StoreSales/data/holidays_events.csv'),  check.names = TRUE)
df_tr       <- fread(file.path(working_folder,'StoreSales/data/transactions.csv'),  check.names = TRUE)

df[df_stores, city     := i.city, on =.(store_nbr)]
df[df_stores, state    := i.state, on =.(store_nbr)]
df[df_stores, type     := i.type, on =.(store_nbr)]
df[df_stores, cluster  := i.cluster, on =.(store_nbr)]
df[df_tr, transactions  := i.transactions, on =.(store_nbr, date)]

df[df_holidays[transferred == FALSE & locale == 'National'], nat_holiday:= i.description, , on =.(date)]
df[df_holidays[transferred == FALSE & locale == 'Local'],    loc_holiday:= i.description, , on =.(date, state = locale_name)]
df[df_holidays[transferred == FALSE & locale == 'Regional'], reg_holiday:= i.description, , on =.(date, state = locale_name)]

df[!is.na(reg_holiday)]
#df[,.(.N), by = .(date, store_nbr, family)][order(N)]

quake_date = as.Date('2016-04-16')
df[, quake := as.numeric(date == quake_date)]

roll_weights = c(-seq(14), 15, 15 - seq(14))/15
df[order(date), quake_rm15 := rollapply(quake, width = length(roll_weights), align = 'center', fill  = 0, FUN = function(x) sum(x * roll_weights) ), by = .(store_nbr, family)]

#df[family == 'AUTOMOTIVE' &  store_nbr == 1,.(date, quake, quake_rm15 )][date > '2016-04-01' & date < '2016-05-01']

df[,is_nat_holiday := as.numeric(!is.na(nat_holiday)) ]
df[order(date), nat_holiday_rm15 := rollapply(is_nat_holiday, width = length(roll_weights), align = 'center', fill  = 0, FUN = function(x) sum(x * roll_weights) ), by = .(store_nbr, family)]

df_oil[order(date), price := na.locf(dcoilwtico, na.rm = FALSE) ]
for(i in c(10, 30, 60, 90, 120)) {
  vname = sprintf('price_rm_%03d', i)
  df_oil[order(date), c(vname) := rollmeanr(price, k = i, fill = NA)]  
}

df[df_oil, price_rm_010  := i.price_rm_010, on =.(date)]
df[df_oil, price_rm_030  := i.price_rm_030, on =.(date)]
df[df_oil, price_rm_060  := i.price_rm_060, on =.(date)]
df[df_oil, price_rm_090  := i.price_rm_090, on =.(date)]
df[df_oil, price_rm_120  := i.price_rm_120, on =.(date)]

df[, weight := exp( -1.0*(max(date_float) - date_float) )]

top11_fam = df[, .(sum(sales, na.rm = TRUE)), by =.(family)][order(-V1), family][1:11]

df[,family_top11 := fct_other(family,keep = top11_fam)]

df[,date_1y := make_date(date_year-1, date_month, date_day) ]
df[,date_2y := make_date(date_year-2, date_month, date_day) ]
df[,date_3y := make_date(date_year-3, date_month, date_day) ]

df[,date_1m := date %m-% months(1) ]
df[,date_2m := date %m-% months(2) ]
df[,date_3m := date %m-% months(3) ]

for(i in c(7, 14, 21, 30, 60, 90, 120, 150, 180, 360)) {
  vname = sprintf('sales_log_rm_%03d', i)
  df[order(date), c(vname) := rollmeanr(sales_log, k = i, fill  = NA), by = .(store_nbr, family)]
}

df[order(date), sales_log_rm_30m := rollmeanr(sales_log, k = 30, fill  = NA), by = .(store_nbr, family)]
df[order(date), sales_log_rm_60m := rollmeanr(sales_log, k = 60, fill  = NA), by = .(store_nbr, family)]
df[order(date), sales_log_rm_90m := rollmeanr(sales_log, k = 90, fill  = NA), by = .(store_nbr, family)]

df[df, sales_log_1y := i.sales_log, on=.(date_1y = date, store_nbr, family)]
df[df, sales_log_2y := i.sales_log, on=.(date_2y = date, store_nbr, family)]
df[df, sales_log_3y := i.sales_log, on=.(date_3y = date, store_nbr, family)]

df[df, sales_log_1m := i.sales_log, on=.(date_1m = date, store_nbr, family)]
df[df, sales_log_2m := i.sales_log, on=.(date_2m = date, store_nbr, family)]
df[df, sales_log_3m := i.sales_log, on=.(date_3m = date, store_nbr, family)]

df[df, sales_log_rm_007_1m := i.sales_log_rm_007, on=.(date_1m = date, store_nbr, family)]
df[df, sales_log_rm_014_1m := i.sales_log_rm_014, on=.(date_1m = date, store_nbr, family)]
df[df, sales_log_rm_021_1m := i.sales_log_rm_021, on=.(date_1m = date, store_nbr, family)]
df[df, sales_log_rm_030_1m := i.sales_log_rm_030, on=.(date_1m = date, store_nbr, family)]
df[df, sales_log_rm_060_1m := i.sales_log_rm_060, on=.(date_1m = date, store_nbr, family)]
df[df, sales_log_rm_090_1m := i.sales_log_rm_090, on=.(date_1m = date, store_nbr, family)]
df[df, sales_log_rm_120_1m := i.sales_log_rm_120, on=.(date_1m = date, store_nbr, family)]
df[df, sales_log_rm_150_1m := i.sales_log_rm_150, on=.(date_1m = date, store_nbr, family)]
df[df, sales_log_rm_180_1m := i.sales_log_rm_180, on=.(date_1m = date, store_nbr, family)]
df[df, sales_log_rm_360_1m := i.sales_log_rm_360, on=.(date_1m = date, store_nbr, family)]

df[df, sales_log_rm_007_2m := i.sales_log_rm_007, on=.(date_2m = date, store_nbr, family)]
df[df, sales_log_rm_014_2m := i.sales_log_rm_014, on=.(date_2m = date, store_nbr, family)]
df[df, sales_log_rm_021_2m := i.sales_log_rm_021, on=.(date_2m = date, store_nbr, family)]
df[df, sales_log_rm_030_2m := i.sales_log_rm_030, on=.(date_2m = date, store_nbr, family)]
df[df, sales_log_rm_060_2m := i.sales_log_rm_060, on=.(date_2m = date, store_nbr, family)]
df[df, sales_log_rm_090_2m := i.sales_log_rm_090, on=.(date_2m = date, store_nbr, family)]
df[df, sales_log_rm_120_2m := i.sales_log_rm_120, on=.(date_2m = date, store_nbr, family)]
df[df, sales_log_rm_150_2m := i.sales_log_rm_150, on=.(date_2m = date, store_nbr, family)]
df[df, sales_log_rm_180_2m := i.sales_log_rm_180, on=.(date_2m = date, store_nbr, family)]
df[df, sales_log_rm_360_2m := i.sales_log_rm_360, on=.(date_2m = date, store_nbr, family)]

df[df, sales_log_rm_007_3m := i.sales_log_rm_007, on=.(date_3m = date, store_nbr, family)]
df[df, sales_log_rm_014_3m := i.sales_log_rm_014, on=.(date_3m = date, store_nbr, family)]
df[df, sales_log_rm_021_3m := i.sales_log_rm_021, on=.(date_3m = date, store_nbr, family)]
df[df, sales_log_rm_030_3m := i.sales_log_rm_030, on=.(date_3m = date, store_nbr, family)]
df[df, sales_log_rm_060_3m := i.sales_log_rm_060, on=.(date_3m = date, store_nbr, family)]
df[df, sales_log_rm_090_3m := i.sales_log_rm_090, on=.(date_3m = date, store_nbr, family)]
df[df, sales_log_rm_120_3m := i.sales_log_rm_120, on=.(date_3m = date, store_nbr, family)]
df[df, sales_log_rm_150_3m := i.sales_log_rm_150, on=.(date_3m = date, store_nbr, family)]
df[df, sales_log_rm_180_3m := i.sales_log_rm_180, on=.(date_3m = date, store_nbr, family)]
df[df, sales_log_rm_360_3m := i.sales_log_rm_360, on=.(date_3m = date, store_nbr, family)]

#df[date == '2017-02-02' & store_nbr == 10, .(date,date_1y, sales_log,sales_log_1y, family)]

```

## Charts

```{r charts, echo=FALSE}
#store_nbr - 53

df_totals = df[, .(total_sales = sum(sales, na.rm = TRUE)), by =.(store_nbr, family)]
df_no_sales = df_totals[total_sales == 0]

ggplot(df[store_nbr == 1 & family == 'GROCERY I' & date_year > 2015 ], aes(date, sales_log)) + geom_line() + 
  geom_line(aes(date, sales_log_3y), color = 'red')

ggplot(df[family == 'BOOKS'], aes(date, sales)) + geom_line() + facet_wrap(~store_nbr)


df_agg = df[, .(total_sales_log = sum(sales_log, na.rm = TRUE), total_sales = sum(sales, na.rm = TRUE), 
                date_float = mean(date_float, na.rm = TRUE),
                prom = sum(onpromotion, na.rm = TRUE),
                weight = mean(weight, na.rm = TRUE),
                transactions = sum(transactions, na.rm = TRUE)), by =.(date)]

ggplot(df_agg, aes(date, total_sales)) + geom_line() + geom_vline(xintercept = quake_date, color = 'red')
ggplot(df_agg, aes(date, total_sales_log)) + geom_line() + geom_vline(xintercept = quake_date, color = 'red')
ggplot(df_agg, aes(date, date_float)) + geom_line()
ggplot(df_agg, aes(date, prom)) + geom_line()
ggplot(df_agg, aes(date, transactions)) + geom_line()
ggplot(df_agg, aes(date, weight)) + geom_line()

ggplot(df_oil, aes(date, price_rm_060)) + geom_line()


plot_profile(df$sales_log[train_index], df$sales_log[train_index], df$date_month[train_index], error_band  = 'normal' )
plot_profile(df$sales_log[train_index], df$sales_log[train_index], df$date_wday[train_index],  error_band  = 'normal' )


df_agg = df[, .(total_sales_log = sum(sales_log, na.rm = TRUE), total_sales = sum(sales, na.rm = TRUE), 
                date_float = mean(date_float, na.rm = TRUE),
                prom = sum(onpromotion, na.rm = TRUE),
                weight = mean(weight, na.rm = TRUE),
                transactions = sum(transactions, na.rm = TRUE)), by =.(date, family)]

ggplot(df_agg, aes(date, total_sales, group = family, fill = family )) + geom_area()

ggplot(df_agg[date == '2017-03-15'], aes(fct_reorder(family,total_sales), total_sales )) + geom_bar(stat = 'identity') + coord_flip()

```

## Light GBM Model

```{r model, echo=FALSE}
set.seed(1321)

#t_index_v = which(train_index & is.na(df$total_sales))
t_index_v = which(train_index)

t_index_v1 = sample(t_index_v, length(t_index_v))

#sales_log_rm_
rm_vars = data.table(expand.grid(c('007', '014','021', '030', '060', '090', '120','150','180','360'), c('_1m', '_2m', '_3m')))
rm_vars = stri_join('sales_log_rm_', rm_vars$Var1, rm_vars$Var2)

all_vars = c('date_month', 'date_day', 'date_wday','date_year', 'family', 'type', 'cluster', 'city', 'state','nat_holiday','loc_holiday','reg_holiday','month_day_count', 'quake_rm15', 'nat_holiday_rm15', 
             'sales_log_1y', 'sales_log_2y', 'sales_log_3y', 'sales_log_1m', 'sales_log_2m', 'sales_log_3m', 
             'sales_log_rm_007_1m', 'sales_log_rm_014_1m', 'sales_log_rm_030_1m', 'sales_log_rm_060_1m', 'sales_log_rm_090_1m', 'sales_log_rm_120_1m','sales_log_rm_150_1m','sales_log_rm_180_1m','sales_log_rm_360_1m')

lgb_vars = c(all_vars) %!in_set% c('id')
obj_var = 'sales_log'

my_cat_vars =  names(which(sapply(df[,lgb_vars, with = FALSE], function(x) is.factor(x) | is.character(x) )))

dfs = df[t_index_v1, c(obj_var,lgb_vars), with = FALSE]

dtrain <- lgb.Dataset(data.matrix(dfs[, lgb_vars , with = FALSE]), label = dfs[[obj_var]], categorical_feature = my_cat_vars, weight = df[t_index_v1, weight] )
params <- list(objective = "regression", metric = "rmse")

model.lgb <- lgb.cv(
  params = params,
  data = dtrain,
  nrounds = 10000,
  nfold = 10,
  num_threads = 5, 
  
  min_data = 800, #default = 20
  learning_rate = 0.01,
  num_leaves = 90,
  bagging_fraction = 0.95,
  min_data_in_bin = 3,

  boost_from_average = TRUE,
  eval_freq = 100,
  early_stopping_rounds = 100
  #force_col_wise=TRUE
  #force_row_wise=TRUE
)

#saveRDS(model.lgb, file.path(working_folder,'StoreSales/data/model_lgb.rds'))

cv_error = as.numeric(model.lgb$record_evals$valid$rmse$eval)
ggplot(data.frame( i = seq(length(cv_error)), cv_error ), aes(i, cv_error)) + geom_line() 

min(cv_error) #7.841514

dm_all = data.matrix(df[,lgb_vars, with = F])
pred.lgb_cvi = ldply(seq(length(model.lgb$boosters)), function(i){ data.frame(cv = i, id = df$id, pred= predict(model.lgb$boosters[[i]]$booster, dm_all)) } )
setDT(pred.lgb_cvi)

pred.lgb_cv_summary = pred.lgb_cvi[, .(.N, avg=mean(pred), sigma = sd(pred)), by =.(cv)]
pred.lgb_cv         = pred.lgb_cvi[, .(.N, avg=mean(pred), sigma = sd(pred)), by =.(id)]

#%% Plot -----
#plot_profiles(df$target_lgb[train_index], df[train_index,])
#plot_profiles_2d(df$target_lgb[p_index], df[p_index,])

df[pred.lgb_cv, sales_log_pred :=  i.avg, on=.(id)]

#remove sales from stores where there is none
#df[total_sales == 0, sales_log_pred := 0]
  

lgb_importance = lgb.importance(model.lgb$boosters[[1]][[1]], percentage = TRUE)
ggplot(lgb_importance, aes(fct_reorder(Feature,Gain), Gain)) + geom_bar(stat = 'identity') + coord_flip()
#lgb.plot.interpretation(lgb_importance)

df_agg = df[, .(total_sales = sum(sales_log), total_sales_pred = sum(sales_log_pred, na.rm = TRUE)), by =.(date, family_top11)]
ggplot(df_agg, aes(date, total_sales)) + geom_line() +  geom_line(aes(date, total_sales_pred), color = 'red') + facet_wrap(~family_top11, scales = 'free')
ggplot(df_agg[year(date) == '2016'], aes(date, total_sales)) + geom_line() +  geom_line(aes(date, total_sales_pred), color = 'red') + 
  facet_wrap(~family_top11, scales = 'free')
ggplot(df_agg[date >= '2016-01-02' & date <'2017-01-01'], aes(date, total_sales)) + geom_line() +  geom_line(aes(date, total_sales_pred), color = 'red') + 
  facet_wrap(~family_top11, scales = 'free')
ggplot(df_agg[year(date) >= '2016'], aes(date, total_sales)) + geom_line() +  geom_line(aes(date, total_sales_pred), color = 'red') + 
  facet_wrap(~family_top11, scales = 'free')

#ggplot(df[family == 'BOOKS'], aes(date, sales_log)) + geom_line() + geom_line(aes(date, sales_log_pred), color = 'red') + facet_wrap(~store_nbr)


 ts_plots = llply(as.character(unique(df_agg$family_top11)), function(var_name) { #lgb_vars
   df_temp_2017 = df_agg[family_top11 == var_name & year(date) == 2017]
   df_temp_2016 = df_agg[family_top11 == var_name & year(date) == 2016]
   df_temp_2016[, date_2017 := make_date(2017, month(date), day(date))]
   
    p = ggplot(df_temp_2017, aes(date, total_sales)) + geom_line() +  geom_line(aes(date, total_sales_pred), color = 'red') +  
       geom_line(data = df_temp_2016, aes(date_2017, total_sales), color = 'blue', alpha = 0.5) + 
      ggtitle(var_name) +  theme(title =element_text(size=8))
    return( ggplotGrob(p) )
  })
  ggsave(filename = file.path(working_folder,"StoreSales/ts_2016.pdf"), plot = marrangeGrob(ts_plots, nrow=1, ncol=1), device = 'pdf', width = 14, height = 8.5, dpi = 360)
  

cc(df[date %in% as.Date(c("2017-08-15", "2017-08-16")) ])

 plots = llply(unique(c(lgb_importance$Feature, 'city', 'state', 'type', 'cluster', 'loc_holiday','price_rm_010','price_rm_030','price_rm_060', 'price_rm_090', 'price_rm_120', 'date_year','date_days_left', 'onpromotion','month_day_count', 'date_float', 'nat_holiday_rm15','quake_rm15')), function(var_name) { #lgb_vars
    p = plot_profile(df$sales_log_pred[train_index],  df$sales_log[train_index], df[[var_name]][train_index], bucket_count = 50, error_band = 'normal') +
      ggtitle(var_name) +  theme(title =element_text(size=8))
    return( ggplotGrob(p) )
  })
  marrangeGrob(plots, nrow = 3, ncol = 3, top = NULL)
  ggsave(filename = file.path(working_folder,"StoreSales/profiles.pdf"), plot = marrangeGrob(plots, nrow=2, ncol=2), device = 'pdf', width = 14, height = 8.5, dpi = 360)
  
  plot_profile(df$sales_log_pred[train_index],  df$sales_log[train_index], df[['nat_holiday_rm15']][train_index], bucket_count = 100, error_band = 'normal')
  plot_profile(df$sales_log_pred[train_index],  df$sales_log[train_index], factor(df[['quake_rm15']][train_index]), bucket_count = 100, error_band = 'normal')
  plot_profile(df$sales_log_pred[train_index],  df$sales_log[train_index], df[['city']][train_index], bucket_count = 10, error_band = 'normal')
  plot_profile(df$sales_log_pred[train_index],  df$sales_log[train_index], df[['state']][train_index], bucket_count = 10, error_band = 'normal')
  plot_profile(df$sales_log_pred[train_index],  df$sales_log[train_index], df[['date']][train_index], bucket_count = 10, error_band = 'normal')
  plot_profile(df$sales_log_pred[train_index],  df$sales_log[train_index], df[['nat_holiday']][train_index], bucket_count = 10, error_band = 'normal')
  plot_profile(df$sales_log_pred[train_index],  df$sales_log[train_index], df[['date_float']][train_index], bucket_count = 100, error_band = 'normal') 
  
  index = df$family == 'POULTRY' & !is.na(df$sales)
  plot_profile(df$sales_log_pred[index],  df$sales_log[index], factor(df[['date_wday']][index]), bucket_count = 10, error_band = 'normal')
  
#partial plots
pdp_index = sample(which(train_index), 10000)
my_model = model.lgb$boosters[[1]][[1]]
df_plot = partialPlot(my_model, data.matrix(df[pdp_index,lgb_vars, with = FALSE]), xname = "onpromotion", n.pt = 100)
ggplot(df_plot, aes(x, y)) + geom_line()

ggplot(df[pdp_index,], aes(loss, target_lgb)) + geom_point()

plot_profile(df$target_lgb[train_index],  df$loss[train_index], df[['f81']][train_index], bucket_count = 20, error_band = 'normal')
```

##Submit 
v2  - 0.54836 baseline (no optimization, no pre-processing)
v3  -  0.53349
v5  -  0.50553 - weighted: exp(-0.5*(ym - y))
v6  -  0.49601 -weighted exp(-(ym - y))
v7  -  0.48661 more iterations
v9  -  0.48221 using previous month/year
v10 -  0.45833 using rolling averages
v11 -  0.46225 zero out missing categories
v12 -  0.45796 using rolling averages

```{r submit, echo=FALSE}
  
  file = file.path(working_folder, "StoreSales/submit_v12.lgb.csv")
  #fwrite(df[test_index, .(id, target=target_lgb)], file = file, row.names = FALSE)
  fwrite(df[!train_index, .(id, sales = pmax(0, exp(sales_log_pred) - 1) )], file = file, row.names = FALSE)
  zip(paste(file, '.zip', sep = ''), file, flags = '-r9Xj')
  print(file)

```
