---
title: "Zwift Analysis"
output: html_document
date: "`r format(Sys.time(), '%d %B, %Y')`"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(dev = "png", dev.args = list(type = "cairo-png"), warning = FALSE, message = FALSE)

library(jsonlite)
library(stringi)
library(lubridate)
library(data.table)
library(ggplot2)
library(zoo)
library(plyr)
library(plotly)
library(gam)
library(knitr)
library(FITfileR)
library(forcats)
library(plotly)
library(gridExtra)
library(ggrepel)


working_folder = 'D:/Github/KaggleSandbox'

source(file.path(working_folder, 'Utils/common.R'))
```

## Convert to CSV
date: "`r format(Sys.time(), '%d %B, %Y')`"
https://github.com/grimbough/FITfileR
```{r convert_to_csv}
#first date with Assioma power: 2024-08-27
fit_folder = file.path(working_folder, 'Zwift/new_power/')

zwift_fit_files = list.files(fit_folder, pattern = '*.fit$', full.names = TRUE)
zwift_fit_files_converted = list.files(fit_folder, pattern = '*.fit.csv$', full.names = TRUE)
zwift_fit_files_converted = stri_replace_all(zwift_fit_files_converted, '', regex = '.csv$')
zwift_fit_files_new = zwift_fit_files %!in_set% zwift_fit_files_converted

print(zwift_fit_files_new)

foreach(name = zwift_fit_files_new, .combine=rbind ) %do% {
  df_temp <- data.frame(records(readFitFile(name)))
  fwrite(df_temp, stri_join(name, ".csv"))
}
```


## Read file
New power readings since 2024-08-27
https://www.fitfileviewer.com/
https://johnedevans.wordpress.com/2018/05/31/the-physics-of-zwift-cycling/

```{r load_data, fig.width = 12, fig.height = 6}
fit_folder = file.path(working_folder, 'Zwift/new_power/')

zwift_files = list.files(fit_folder, pattern = glob2rx('*fit.csv'), full.names = TRUE)

df = foreach(name = zwift_files, .combine=function(...) rbind(..., fill = TRUE, use.names = TRUE) ) %do% {
  df_temp = fread(name, drop = c('position_lat', 'position_long'))
  df_temp[, file := basename(name)]
  return(df_temp)
}

df = df[,.(timestamp, distance, heart_rate, altitude,  speed, power, cadence, file)]

df[order(timestamp), t:=seq(.N)-1, by = .(file)]
df[, date :=as.Date(stri_sub(file, 1, to=10 ))]


```
## Report
```{r report, fig.width = 14, fig.height = 8, dpi =  240, warning=FALSE}
df[heart_rate==0, heart_rate:=NA ]
df[order(timestamp), heart_rate:=nafill(heart_rate, type="locf", fill=NA, nan=NA), by = .(file)]
df[order(timestamp),power_5m_sd := frollapply(power, 5*60, sd, na.rm=TRUE), by = .(file)]
df[order(timestamp),heart_rate_5m_sd := frollapply(heart_rate, 5*60, sd, na.rm=TRUE), by = .(file)]
df[, power_bkt := cut(power, breaks = c(0, 150, 200, 250, 300, 400, 1000), ordered_result = TRUE, include.lowest = TRUE)]

df[order(timestamp), altitude_smooth := frollmean(altitude, 5, align = 'center'), by =.(file) ]
df[order(timestamp), grade     := (shift(altitude_smooth,-1) - shift(altitude_smooth))/(shift(distance,-1) - shift(distance)), by =.(file) ]

df[order(timestamp),power_5s_avg := frollmean(power, 5, na.rm=TRUE), by = .(file)]
df[order(timestamp),power_1m_avg := frollmean(power, 1*60, na.rm=TRUE), by = .(file)]
df[order(timestamp),power_3m_avg := frollmean(power, 3*60, na.rm=TRUE), by = .(file)]
df[order(timestamp),power_5m_avg := frollmean(power, 5*60, na.rm=TRUE), by = .(file)]
df[order(timestamp),power_10m_avg := frollmean(power, 10*60, na.rm=TRUE), by = .(file)]
df[order(timestamp),power_20m_avg := frollmean(power, 20*60, na.rm=TRUE), by = .(file)]
df[order(timestamp),power_30m_avg := frollmean(power, 30*60, na.rm=TRUE), by = .(file)]
df[order(timestamp), power_70s_ewma := ewma(power, exp(-log(2)/ 70)), by =.(file)]
df[order(timestamp), power_100s_ewma := ewma(power, exp(-log(2)/ 100)), by =.(file)]  

df[order(timestamp),cadence_5s_avg := frollmean(cadence, 5, na.rm=TRUE), by = .(file)]
df[order(timestamp),cadence_1m_avg := frollmean(cadence, 60, na.rm=TRUE), by = .(file)]
df[order(timestamp),cadence_20m_avg := frollmean(cadence, 20*60, na.rm=TRUE), by = .(file)]


df[order(timestamp),hr_1m_avg  := frollmean(heart_rate, 1*60, na.rm=TRUE), by = .(file)]
df[order(timestamp),hr_3m_avg  := frollmean(heart_rate, 3*60, na.rm=TRUE), by = .(file)]
df[order(timestamp),hr_5m_avg  := frollmean(heart_rate, 5*60, na.rm=TRUE), by = .(file)]
df[order(timestamp),hr_10m_avg := frollmean(heart_rate, 10*60, na.rm=TRUE), by = .(file)]
df[order(timestamp),hr_20m_avg := frollmean(heart_rate, 20*60, na.rm=TRUE), by = .(file)]

#df[order(timestamp),hr_eq := 1.064e+02 + 2.224e-01 * power_70s_ewma , by = .(date)]
#df[,hr_eq := 154.2635 -  0.4732869 * pmax(0,       211.8767 - power_70s_ewma) + 0.07484887 * pmax(0, power_70s_ewma -       211.8767) , by = .(date)]
df[order(timestamp), cum_power := cumsum(1e-3*power), by =.(file)]  

df[,hr_eq := 145.5845
  +   0.2547335 * pmax(0, power_100s_ewma -        168.9769) 
  -    0.322672 * pmax(0,        212.8317 - power_100s_ewma) 
  -  0.09903986 * pmax(0, power_100s_ewma -        212.8317) 
  -  0.01809875 * pmax(0,         475.234 -       cum_power) 
  + 0.004428587 * pmax(0,       cum_power -         475.234)   , by = .(file)]

   
#kable(df[,.(.N), .(file)])
 
df_agg = df[,.(.N, time=.N/60, kcal = 4.023349 * sum(power, na.rm= TRUE)/4200, date = max(date),
      power_avg = mean(power, na.rm= TRUE),
      power_max = max(power, na.rm= TRUE), 
      stop_time = sum(power<1), 
      power_max_1  = max(power_1m_avg, na.rm=TRUE),
      power_max_5 = max(power_5m_avg, na.rm=TRUE),
      power_max_10 = max(power_10m_avg, na.rm=TRUE),
      power_max_20 = max(power_20m_avg, na.rm=TRUE),
      power_max_30 = max(power_30m_avg, na.rm=TRUE),
      power_ftp = 0.95*max(power_20m_avg, na.rm=TRUE),
      fatigue = mean((heart_rate  - hr_eq) * (t/60 > 20), na.rm=TRUE),   
      hr_avg = mean(heart_rate, na.rm= TRUE),
      power_hr_ratio =  mean(power, na.rm= TRUE)/mean(heart_rate, na.rm= TRUE),
      power_hr_ratio_10m =  mean(power_10m_avg, na.rm= TRUE)/mean(hr_10m_avg,na.rm= TRUE),
      hr_max = max(heart_rate), 
      cadence = mean(cadence),
      dist_m = max(distance)/1609.34, 
      ascend_ft = 3.281 * sum(pmax(0, altitude - shift(altitude)), na.rm = TRUE)), by = .(file)]

df_agg = df_agg[N>300, ]

kable(df_agg)

ggplot(df_agg, aes(date, time, label = sprintf('%d', floor(time) ) ))           + geom_point() + geom_smooth(method = 'loess') + geom_text_repel(size = 3)
ggplot(df_agg, aes(date, power_max_1, label = sprintf('%.1f', power_max_1), size = time, weight = time ))           + geom_point(alpha = 0.6) + geom_smooth(method = 'loess') + geom_text_repel(size = 3) + theme(legend.position = "None")
ggplot(df_agg, aes(date, power_ftp, label = sprintf('%.1f', power_ftp), size = time, weight = time ))           + geom_point(alpha = 0.6) + geom_smooth(method = 'loess') + geom_text_repel(size = 3) + theme(legend.position = "None")
ggplot(df_agg, aes(date, power_avg, label = sprintf('%.1f', power_avg), size = time, weight = time ))           + geom_point(alpha = 0.6) + geom_smooth(method = 'loess') + geom_text_repel(size = 3) + theme(legend.position = "None")

ggplot(df_agg, aes(date, power_hr_ratio, label = sprintf('%.2f', power_hr_ratio), size = time, weight = time )) + geom_point(alpha = 0.6) + geom_smooth(method = 'loess') + geom_text_repel(size = 3) + theme(legend.position = "None")
ggplot(df_agg, aes(date, hr_avg, label = sprintf('%.1f', hr_avg), size = time, weight = time )) + geom_point(alpha = 0.6) + geom_smooth(method = 'loess') + geom_text_repel(size = 3) + theme(legend.position = "None")
ggplot(df_agg, aes(date, cadence, label = sprintf('%.1f', cadence), size = time, weight = time )) + geom_point(alpha = 0.6) + geom_smooth(method = 'loess') + geom_text_repel(size = 3) + theme(legend.position = "None")
ggplot(df_agg, aes(date, fatigue, label = sprintf('%.1f', fatigue), size = time, weight = time )) + geom_point(alpha = 0.6) + geom_smooth(method = 'loess') + geom_text_repel(size = 3) + theme(legend.position = "None")

ggplot(df_agg, aes(fatigue, power_avg, label = sprintf('%.1f', fatigue), size = time, weight = time )) + geom_point(alpha = 0.6)

df_agg = df_agg[hr_avg > 90]

ggplot(df_agg, aes(power_ftp,  fatigue)) + geom_point()

if(FALSE){
 
  last_12_days = head(sort(unique(df$date), TRUE), 12)
  dfs = df[date %in% last_12_days]

  ggplot(dfs[t>60*5], aes(grade, power)) + geom_point(alpha = 0.1) + facet_wrap(~file)
  
  ggplot(df[t>60*5], aes(power_70s_ewma, heart_rate )) + geom_point(alpha = 0.1) + geom_point(aes(power_70s_ewma, hr_eq), color = 'red')+ facet_wrap(~date)
  ggplot(df[t>60*5], aes(power_100s_ewma, heart_rate )) + geom_point(alpha = 0.1) + geom_point(aes(power_100s_ewma, hr_eq), color = 'red')+ facet_wrap(~date)
  
ggplot(df) + geom_line(aes(t/60, power_20m_avg, color = 'power')) + geom_line(aes(t/60, 1.4*hr_3m_avg, color = 'hr')) + facet_wrap(~file)
  
  ggplot(df) + geom_line(aes(t/60, power_3m_avg, color = 'power_3m_avg')) + geom_line(aes(t/60, power_70s_ewma, color = 'power_70s_ewma')) + facet_wrap(~file)

  ggplot(df) + geom_line(aes(t/60, power, group = file, color = file))+ facet_wrap(~file)
ggplot(df) + geom_line(aes(t/60, power_5m_avg, group = file, color = file))+ facet_wrap(~file)
ggplot(df) + geom_line(aes(t/60, power_10m_avg, group = file, color = file))
ggplot(df) + stat_ecdf(aes(power, group = file, color = file))
ggplot(df) + geom_density(aes(power, group = file, color = file))
ggplot(df) + geom_density(aes(power_5m_avg, group = file, color = file), adjust = 0.3)
ggplot(df) + geom_histogram(aes(power_10m_avg, group = file, fill = file), binwidth = 0.5, alpha = 0.7, position="identity")
ggplot(df[heart_rate>100]) + geom_histogram(aes(heart_rate, group = file, fill = file), binwidth = 1, alpha = 0.7, position="identity")

ggplot(df) + geom_histogram(aes(hr_5m_avg, group = file, fill = file), binwidth = 0.5, alpha = 0.7, position="identity")

ggplot(df) + geom_density(aes(power_20m_avg, group = file, color = file), adjust = 0.3)

ggplot(df, aes(cadence, power, group = file, color = file)) + geom_smooth(span = 0.2)
ggplot(df, aes(cadence, power, group = file, color = file)) + geom_point()

ggplot(df, aes(hr_5m_avg, power_20m_avg, group = date)) + geom_point(alpha = 0.5) + facet_wrap(~date)
ggplot(df, aes(heart_rate, power_5m_avg, group = date)) + geom_point(alpha = 0.5) + facet_wrap(~date)

cor(df)
#plot correlation
num_var = names(which(sapply(df, is.numeric )))
con_corr = cor(df[,num_var, with = FALSE], use="pairwise.complete.obs")
library(corrplot)
corrplot(con_corr, method="ellipse")
corrplot(con_corr, method="number")
corrplot.mixed(con_corr, lower="number", upper="ellipse")

ggplot(df) + geom_line(aes(t/60, heart_rate)) + facet_wrap(~file)
ggplot(df) + geom_line(aes(t/60, power_5m_avg)) + facet_wrap(~file)
ggplot(df) + geom_line(aes(t/60, power)) +  geom_line(aes(t/60, power_20m_avg), color = 'red') +  geom_line(aes(t/60, power_1m_avg), color = 'blue') + facet_wrap(~file)

ggplot(df) + geom_point(aes(power, heart_rate)) + facet_wrap(~file)

ggplot(df) + geom_violin(aes(date, power, group = date)) + geom_point(data = df_agg, aes(date, power_avg ))

ggplotly(ggplot(df[date == max(date)]) + geom_line(aes(t/60, power)))

cc(df[date == max(date),.(t, heart_rate, power, power_5s_avg)])


df_period = periodogram(df[date == '2024-09-04', power])
ggplot(df_period, aes((1/freq)/60, y))  +geom_step()


} #-----------------------

last_12_days = head(sort(unique(df$date), TRUE), 12)

dfs = df[date %in% last_12_days]

ggplot(dfs, aes(t/60, file, fill = power_bkt)) + geom_tile() + scale_fill_custom('mixed', discrete = TRUE)
ggplot(dfs, aes(t/60, file, fill = heart_rate)) + geom_tile() + scale_fill_custom('mixed', discrete = FALSE)
ggplot(dfs, aes(t/60, file, fill = cadence)) + geom_tile() + scale_fill_custom('mixed', discrete = FALSE)
ggplot(dfs, aes(t/60, file, fill = hr_eq - heart_rate)) + geom_tile() + scale_fill_custom('div', discrete = FALSE, limits  = c(-20, 20))

ggplot(dfs) + geom_line(aes(t/60, power)) + geom_line(aes(t/60, power_3m_avg), color = 'red') + geom_hline(data = df_agg[date %in% last_12_days], aes(yintercept = power_avg), linetype = 'dashed', color = 'blue') + facet_wrap(~file)
ggplot(dfs) + geom_line(aes(t/60, heart_rate, color = 'heart_rate')) + geom_line(aes(t/60, hr_eq, color = 'hr_eq')) + facet_wrap(~file) + scale_color_manual(values = c('black', 'red')) + 
  geom_hline(yintercept = c(120, 140, 160), linetype = 'dashed', color = 'grey')

ggplot(dfs) + geom_density(aes(heart_rate), adjust = 0.3) + facet_wrap(~file) + geom_vline(xintercept = c(120, 140, 160), linetype = 'dashed', color = 'grey')
ggplot(dfs) + geom_density(aes(power_10m_avg), adjust = 0.3) + facet_wrap(~file)
ggplot(dfs) + geom_density(aes(power_20m_avg), adjust = 0.3) + facet_wrap(~file)
ggplot(dfs) + geom_density(aes(power_100s_ewma/heart_rate), adjust = 0.3) + facet_wrap(~file)

ggplot(dfs) + geom_line(aes(t/60, power_10m_avg)) + facet_wrap(~file)
ggplot(dfs, aes(cadence, power)) + geom_point(alpha = 0.1, size = 1) + geom_rug(alpha = 0.01) + facet_wrap(~file)
ggplot(dfs, aes(speed, power)) + geom_point(alpha = 0.1, size = 1) + geom_rug(alpha = 0.01) + facet_wrap(~file)

ggplot(dfs) + geom_density(aes(power), adjust = 0.3) + facet_wrap(~file)+ geom_vline(xintercept = c(200, 300, 400), linetype = 'dashed', color = 'grey')
ggplot(dfs) + geom_density(aes(heart_rate), adjust = 0.3) + facet_wrap(~file) + geom_vline(xintercept = c(120, 140, 160), linetype = 'dashed', color = 'grey')

ggplot(dfs) + geom_line(aes(t/60, power_100s_ewma/heart_rate)) + facet_wrap(~file)

ggplot(dfs) + geom_violin(aes(date, heart_rate, group = date), adjust = 0.5) +geom_hline(yintercept = c(120, 140, 160), linetype = 'dashed', color = 'blue')
ggplot(dfs) + geom_violin(aes(date, power, group = date), adjust = 0.5) + geom_hline(yintercept = c(200,300, 400), linetype = 'dashed', color = 'blue')
ggplot(dfs) + geom_violin(aes(date, cadence, group = date), adjust = 0.5) + geom_hline(yintercept = c(80, 90, 100), linetype = 'dashed', color = 'blue')

ggplot(df_agg) + geom_point(aes(date, power_hr_ratio)) +
  geom_line(aes(date, power_hr_ratio, color = 'power_hr_ratio' )) + 
  geom_line(aes(date, power_hr_ratio_10m, color = 'power_hr_ratio_10m' )) 

ggplot(df_agg) + geom_point(aes(date, power_avg)) +
  geom_line(aes(date, power_avg, color = 'power_avg' )) + 
  geom_line(aes(date, power_max_1, color = 'power_max_1' )) + 
  geom_line(aes(date, power_max_5, color = 'power_max_5' )) +
  geom_line(aes(date, power_max_10, color = 'power_max_10' )) + 
  geom_line(aes(date, power_max_20, color = 'power_max_20' )) +
  geom_line(aes(date, power_max_30, color = 'power_max_30' )) 

ggplot(df_agg, aes(date, hr_avg )) + geom_point() + geom_line()
ggplot(df_agg, aes(date, hr_max )) + geom_point() + geom_line()
ggplot(df_agg, aes(date, power_avg )) + geom_point() + geom_line()+ geom_smooth(method = 'lm', se = FALSE )
ggplot(df_agg, aes(date, power_max_10 )) + geom_point() + geom_line()+ geom_smooth(method = 'lm', se = FALSE )
ggplot(df_agg, aes(date, power_max_20 )) + geom_point() + geom_line()+ geom_smooth(method = 'lm', se = FALSE )
ggplot(df_agg, aes(date, power_max )) + geom_point() + geom_line() + geom_smooth(method = 'lm', se = FALSE )

ggplot(df_agg, aes(date, time )) + geom_point() + geom_line()
ggplot(df_agg, aes(date, cadence )) + geom_point() + geom_line()
ggplot(df_agg, aes(date, fatigue )) + geom_point() + geom_line() + geom_smooth(method = 'lm')

ggplot(df_agg, aes(hr_avg, power_avg, color = date %in% last_12_days )) + geom_point()
ggplot(df_agg, aes(fatigue, power_hr_ratio, color = date )) + geom_point()

#power curve

df_power_curve = ldply(seq(1, 90*60), function(seconds){
  df_agg_temp = df[order(timestamp),.(power_max  = max(frollmean(power, seconds, na.rm=TRUE), na.rm=TRUE), date = max(date)),by = .(file)]
  #df_agg_temp = df[order(timestamp),.(power_max  = quantile(frollmean(power, seconds, na.rm=TRUE),prob = 0.999, na.rm=TRUE)),by = .(date)]
  df_agg_temp[, interval := seconds]
  return(df_agg_temp)
})
setDT(df_power_curve)
df_power_curve[is.infinite(power_max), power_max := NA]
df_power_curve[, last_date := date == max(date)]
df_power_curve_agg =  df_power_curve[power_max >0, .(power_max = mean(power_max, na.rm = TRUE)), by =.(interval, last_date)]

df_power_curve[df_power_curve[last_date == TRUE], power_max_last_day := i.power_max, on=.(interval)]
df_power_curve[, power_max_last_day_pct := ecdf(power_max)(power_max_last_day), by =.(interval)]

intervals = c(10, 60, 60*10, 60*20, 60*30, 60*60, 90*60)
ggplot(df_power_curve[last_date == FALSE]) + geom_line(aes(interval, power_max, group = file ), color = 'black', alpha = 0.3) + 
  geom_line(data = df_power_curve[last_date == TRUE], aes(interval, power_max, group = file ), color = 'red', alpha = 1.0) +  
  geom_line(data = df_power_curve_agg[last_date == FALSE], aes(interval, power_max ), color = 'blue' ) +    
  geom_vline(xintercept = intervals, linetype = 'dashed', alpha = 0.4) + 
  scale_x_log10(breaks = intervals, labels = ifelse(intervals<60, stri_join(intervals, 's'),  stri_join(intervals/60, 'm')))

ggplot(df_power_curve) + geom_line(aes(interval, power_max_last_day_pct, group = file ), color = 'black', alpha = 0.3) +   
  scale_x_log10(breaks = intervals, labels = ifelse(intervals<60, stri_join(intervals, 's'),  stri_join(intervals/60, 'm'))) + 
  geom_vline(xintercept = intervals, linetype = 'dashed', alpha = 0.4)

```

## Cadence vs Power
```{r cadence_power, fig.width = 12, fig.height = 6, eval = FALSE, echo = FALSE}
##deep dive into power cadence relationship, resistance 36, 37 and 38 - 20 min each
dft = df[date == '2024-09-13']
dft[, t_period := floor(t / (20*60)) ]
dft[, t_p := t - t_period * (20*60) ]

dft[, .(.N, mean(power), mean(cadence), mean(power)/mean(cadence), mean(power_1m_avg/cadence_1m_avg, na.rm = TRUE)), by =.(t_period)]

ggplot(dft[t_period<3], aes(cadence_5s_avg, power_5s_avg, group = t_period, color = factor(t_period) )) + geom_smooth(span = 0.2, method = 'loess')

ggplot(dft[t_period<3], aes(cadence_1m_avg, power_1m_avg, group = t_period, color = factor(t_period) )) + geom_smooth(span = 0.2, method = 'loess')
ggplot(dft[t_period<3], aes(t_p/60, power_1m_avg, group = t_period, color = factor(t_period) )) + geom_line() 
ggplot(dft[t_period<3], aes(t_p/60, cadence_1m_avg, group = t_period, color = factor(t_period) )) + geom_line()
ggplot(dft[t_period<3], aes(t_p/60, power_1m_avg/cadence_1m_avg, group = t_period, color = factor(t_period) )) + geom_line()

ggplot(dft[t_period<3], aes(cadence_1m_avg, power_1m_avg, group = t_period, color = factor(t_period) )) + geom_point(alpha = 0.8, size = 0.5) 

##deep dive into power cadence relationship, resistance 34, 35, 36, 37, 38, 39 - 10 min each
dft = df[date == '2024-09-14']
dft[, t_period := floor(t / (10*60)) ]
dft[, t_p := t - t_period * (10*60) ]
dft[, t_period_f := factor(t_period)]

dft_agg = dft[, .(.N, power=mean(power), cadence=mean(cadence), ppc = mean(power)/mean(cadence), ppc_1m_avg = mean(power_1m_avg/cadence_1m_avg, na.rm = TRUE), ppc_5s_avg = mean(power_5s_avg/cadence_5s_avg, na.rm = TRUE)), by =.(t_period)]

ggplot(dft_agg[N> 20], aes(t_period, power)) + geom_line() + geom_point()
ggplot(dft_agg[N> 20], aes(t_period, cadence)) + geom_line() + geom_point()
ggplot(dft_agg[N> 20], aes(t_period, power*90/cadence)) + geom_line() + geom_point() #power for 90 candence
ggplot(dft_agg[N> 20], aes(t_period, ppc_1m_avg)) + geom_line() + geom_point() #power for 90 candence
ggplot(dft_agg[N> 20], aes(t_period, ppc_5s_avg)) + geom_line() + geom_point() #power for 90 candence

ggplot(dft[t_period<6], aes(cadence_5s_avg, power_5s_avg, group = t_period, color = factor(t_period) )) + geom_smooth(span = 0.2, method = 'loess')
ggplot(dft[t_period<6], aes(cadence_1m_avg, power_1m_avg, group = t_period, color = factor(t_period) )) + geom_smooth(span = 0.2, method = 'loess')

ggplot(dft[t_period<6], aes(cadence_5s_avg, power_5s_avg, group = t_period, color = factor(t_period) )) + geom_smooth(span = 0.2, method = 'lm')
ggplot(dft[t_period<6], aes(cadence_1m_avg, power_1m_avg, group = t_period, color = factor(t_period) )) + geom_smooth(span = 0.2, method = 'lm')

ggplot(dft[t_period<6], aes(cadence_5s_avg, power_5s_avg, group = t_period, color = factor(t_period) )) + geom_point()
ggplot(dft[t_period<6], aes(cadence_1m_avg, power_1m_avg, group = t_period, color = factor(t_period) )) + geom_point()

summary(lm( power_1m_avg ~ cadence_1m_avg + t_period_f, dft[t_period<6])) #one resistance level adds about 68W on average

cadence_model = lm( power_1m_avg ~ cadence_1m_avg * t_period_f + t_period_f, dft[t_period<6])
summary(cadence_model) #one resistance level adds about 68W on average

diff(predict(cadence_model, data.frame(cadence_1m_avg  = 90, t_period_f = dft[, levels(t_period_f)[1:5]] ))) #Watt per level from 34 and up at 90 rpm: 11.938878  9.855070  6.591002  6.415589
diff(predict(cadence_model, data.frame(cadence_1m_avg  = 80, t_period_f = dft[, levels(t_period_f)[1:5]] ))) #Watt per level from 34 and up at 80 rpm: 1.360231 11.730017  3.353159  3.933653 
predict(cadence_model, data.frame(cadence_1m_avg  = 85, t_period_f = dft[, levels(t_period_f)[1:5]] )) # 6.649555 10.792544  4.972081  5.174621 

ggplot(dft[t_period<3], aes(t_p/60, power_1m_avg, group = t_period, color = factor(t_period) )) + geom_line() 
ggplot(dft[t_period<3], aes(t_p/60, cadence_1m_avg, group = t_period, color = factor(t_period) )) + geom_line()
ggplot(dft[t_period<3], aes(t_p/60, power_1m_avg/cadence_1m_avg, group = t_period, color = factor(t_period) )) + geom_line()

ggplot(dft[t_period<3], aes(cadence_1m_avg, power_1m_avg, group = t_period, color = factor(t_period) )) + geom_point(alpha = 0.8, size = 0.5) 

```

## Power vs Heart rate model

```{r power_heart_rate_model, echo=FALSE, eval = FALSE}

library(earth)

df[order(timestamp), power_100s_ewma := ewma(power, exp(-log(2)/ 100)), by =.(date)]  
df[order(timestamp), cum_power := cumsum(1e-3*power), by =.(date)]  


mars.model = earth(heart_rate ~ power_100s_ewma + cum_power, df[t>60*5], degree = 1, nfold = 10, trace = 3, thresh = 0.01)
summary(mars.model, style='pmax')
plotmo(mars.model)

df_res = ldply(seq(120), function(w_size){
  df[order(timestamp), power_ewma_temp := ewma(power, exp(-log(2)/ w_size)), by =.(date)]  
  mars.model = earth(heart_rate ~ power_ewma_temp, df[t>60*5], degree = 1, nfold = 10, trace = 0, thresh = 0.01)
  r2 = summary(mars.model, style='pmax')$rsq
  return(data.frame(w_size, r2))
})
ggplot(df_res, aes(w_size, r2)) + geom_line()

df[,hr_eq_ex := 145.5845
  +   0.2547335 * pmax(0, power_100s_ewma -        168.9769) 
  -    0.322672 * pmax(0,        212.8317 - power_100s_ewma) 
  -  0.09903986 * pmax(0, power_100s_ewma -        212.8317) 
  -  0.01809875 * pmax(0,         475.234 -       cum_power) 
  + 0.004428587 * pmax(0,       cum_power -         475.234)   , by = .(date)]

plot_profile(df$hr_eq_ex, df$heart_rate, df$t, bucket_count = 50)
plot_profile(df$hr_eq_ex, df$heart_rate, df$cum_power, bucket_count = 50)
plot_profile(df$hr_eq_ex, df$heart_rate, df$power_70s_ewma, bucket_count = 50)
plot_profile(df$hr_eq_ex, df$heart_rate, df$power_100s_ewma, bucket_count = 50)
plot_profile(df$hr_eq_ex, df$heart_rate, df$power_20m_avg, bucket_count = 50)
plot_profile(df$hr_eq_ex, df$heart_rate, df$power_10m_avg, bucket_count = 50)
plot_profile(df$hr_eq_ex, df$heart_rate, df$power_1m_avg, bucket_count = 50)
plot_profile(df$hr_eq_ex, df$heart_rate, df$power_5s_avg, bucket_count = 50)

#100 0.8633681
```

## Power vs Heart rate LASSO

```{r power_heart_rate_lasso, echo=FALSE, eval = FALSE}

dfs = df[t > 300 &  heart_rate > 90]

library(glmnet)
library(plyr)

get_all_coefs<-function(glmnet_obj){
  res = ldply(glmnet_obj$lambda, function(lambda){
    temp = data.matrix(coef(glmnet_obj,s=lambda))
    data.frame(var_name = rownames(temp), coef = as.numeric(temp), lambda)
  })
  return(res)
}

for(i in seq(360)) {
  vname = sprintf('power_rm_%03d', i)
  #dfs[order(date), c(vname) := rollmeanr(power, k = i, fill = NA), by =.(file)]
  dfs[order(date), c(vname) := ewma(power, exp(-log(2)/ i)), by =.(file)]  
}

#dfs[order(date), power_ew_150 := ewma(power,exp(-log(2)/ 150)), by =.(file)]
#ggplot(dfs) + geom_line(aes(t, power_ew_150), color = 'blue') + geom_line(aes(t, power_rm_150), color = 'red') + geom_line(aes(t, power), color = 'black', alpha = 0.3) + facet_wrap(~date)

model_rm_vars = names(dfs)[ grep('power_rm_', names(dfs)) ]


x=data.matrix(dfs[, c('heart_rate', model_rm_vars), with = FALSE])
index = complete.cases(x)
y = x[index, 1]
x = x[index,-1]

cor_matrix =  cor(dfs[, c('heart_rate', model_rm_vars), with = FALSE], use="pairwise.complete.obs")
data.table(cor_matrix[,1])[V1<1][V1 == max(V1)]


cvob3=cv.glmnet(x, y, family="gaussian", nfolds = 10, relax = FALSE)
plot(cvob3)

coef_path = data.table(get_all_coefs(cvob3))
coef_path[order(var_name), weight := seq(0, .N-1),  by =.(lambda)]
coef_path[order(var_name,  decreasing = TRUE), adj_coef := cumsum(coef / weight),  by =.(lambda)]
coef_path[, dof:=sum(coef!=0), by =.(lambda)]
coef_path[var_name != '(Intercept)', .( sum(coef),  sum(adj_coef)), by =.(lambda)] #sum of the coefs  -0.013400167
coef_path[var_name != '(Intercept)' & lambda == cvob3$lambda.1se & coef != 0]
coef_path[var_name != '(Intercept)' & dof == 4 & coef != 0]

imp_vars = sort(as.character(unique( coef_path[lambda >= 1*cvob3$lambda.1se & abs(coef) >0, var_name] )))

ggplot(coef_path[var_name != '(Intercept)'], aes(weight, log(lambda), fill = atan(1e4*coef) )) + geom_tile() +  
  theme(axis.text.x  = element_text(angle=0, size = 7)) + 
  geom_hline(yintercept = log(c(cvob3$lambda.1se, cvob3$lambda.min)), linetype = 'dashed') + 
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0)

hr.model = lm('heart_rate ~ power_rm_072', dfs)

summary(hr.model) #0.2696

dfs[, heart_rate_pred := predict(hr.model,.SD)]
ggplot(dfs) + geom_line(aes(t/60, heart_rate_pred), color = 'red') + geom_line(aes(t/60, heart_rate)) + facet_wrap(~file)
#ggplot(df) + geom_line(aes(t/60, power_avg_15s))+  geom_line(aes(t/60, 2*heart_rate),  color = 'red') + facet_wrap(~file)

plot_profile(dfs$heart_rate_pred, dfs$heart_rate, dfs$t, 30)
plot_profile(dfs$heart_rate_pred, dfs$heart_rate, dfs$date, 30)


```

## Bike Physics 
m = 88.33416, c_roll = 0.0020, c_drag = 0.3152741
```{r bike_physics, echo=FALSE, eval = FALSE}

library(deSolve)
library(gridExtra)

mph = 2.23694 #convert from m/sec to mph
c_roll = 0.0020
c_drag = 0.3152741
rho_air = 1.225
g_freefall = 9.8

bike_ride_const_power <- function(t, state, parameters, grade_d, grade_v, power) {
  with(as.list(c(state, parameters)), {
    grade = approx(grade_d, grade_v, X, yleft = 0, yright = 0, rule=2)$y
    alpha = asin(grade)
    dX <-  V
    dV <-   ( (power/m) / pmax(0.01, abs(V) ) - 0.5 * rho_air * V * V * c_drag / m -  g_freefall * sin(alpha) - g_freefall * cos(alpha) * c_roll )
    list(c(dX, dV))
  })
}

bike_ride <- function(t, state, parameters, grade_d, grade_v, power_t, power_v) {
  with(as.list(c(state, parameters)), {
    grade = approx(grade_d, grade_v, X, yleft = 0, yright = 0, rule=2)$y
    alpha = asin(grade)
    power = approx(power_t, power_v, t, yleft = 0, yright = 0, rule=2)$y
    dX <-  V
    dV <-  (power / (m *pmax(0.01, V)) - 0.5 * rho_air * pmax(0, V*V) * c_drag / m - g_freefall * sin(alpha) - g_freefall * cos(alpha) * c_roll )
    list(c(dX, dV))
  })
}

# --------------------------------------------- actual bike ride
df_phys = df[date == '2024-09-06',]
df_phys = df[date == '2024-12-06',]
df_phys = df[date == '2024-12-19',]
df_phys = df[date == '2024-12-22',]
df_phys = df[date == '2024-12-26',]

#remove jumps
df_phys[order(t), altitude_delta := altitude - shift(altitude), by =.(date) ]
df_phys[order(t), altitude_smooth := frollmean(altitude, 5, align = 'center'), by =.(date) ]
df_phys[order(t), grade     := (shift(altitude_smooth,-1) - shift(altitude_smooth))/(shift(distance,-1) - shift(distance)), by =.(date) ]
df_phys[order(t), grade_raw := (shift(altitude,-1) - shift(altitude))/(shift(distance,-1) - shift(distance)), by =.(date) ]

ggplotly(ggplot(df_phys, aes(distance, altitude )) + geom_line() +  geom_line( aes(distance, altitude_smooth ), color = 'red'))

parameters <- c(m = 88.33416, c_roll = 0.0020, c_drag = 0.3152741)
state      <- c(X = df_phys$distance[1], V = df_phys$speed[1])
times      <- seq(0, 60*55, by = 1)

eq_power <- function(V, grade) {
  alpha = asin(grade)
  0.5 * rho_air * V*V * V * parameters[['c_drag']]  + g_freefall * sin(alpha) * parameters[['m']] * V + g_freefall * cos(alpha) * parameters[['c_roll']] * parameters[['m']] * V
}
uniroot(function(x) eq_power(x, 0) - 200, interval = c(0, 20))$root
df_grid = data.table(expand.grid(Power = c(150, 200, 250, 300), grade = 0.01*c(0, seq(9) )))
df_grid[, eq_speed := mph*uniroot(function(x) eq_power(x, grade) - Power, interval = c(0, 20))$root, by =.(seq(nrow(df_grid)))]
dcast(df_grid, Power ~ grade)


out <- ode(y = state, times = times, func = function(t, state, parameters) bike_ride(t, state, parameters, df_phys$distance, df_phys$grade, df_phys$t, df_phys$power), parms = parameters)
res = data.table(out)
res[V<0, V:=0 ]
res[, grade    := approx(df_phys$distance, df_phys$grade, X, yleft = 0, yright = 0, rule=2)$y]
res[, altitude := approx(df_phys$distance, df_phys$altitude, X, yleft = 0, yright = 0, rule=2)$y]

res[, zwift_v := approx(df_phys$distance, df_phys$speed, X, yleft = 0, yright = 0, rule=2)$y ]
res[time <60*60, mean((V - zwift_v)^2, na.rm = TRUE)] # 0.04389351

ggplot(res, aes(V, zwift_v)) + geom_point(alpha = 0.6) + geom_abline(slope = 1, color = 'red', linetype = 'dashed')

ggplot(res, aes(time, X)) + geom_line()
ggplot(res, aes(time, V)) + geom_line()

ggplot(df_phys, aes(distance, altitude )) + geom_line() +  geom_line( aes(distance, altitude_smooth ), color = 'red')
ggplot(df_phys, aes(distance, grade_raw )) + geom_line() + geom_line(aes(distance, grade ), color = 'red')

ggplot(df_phys, aes(distance, altitude_delta )) + geom_line()

ggplot(df_phys, aes(distance, power )) + geom_line() + geom_line(data = res, aes(X, 10*V),    color = 'red') + 
  geom_line(data = res, aes(X, 10*zwift_v),    color = 'blue') +  geom_line(data = df_phys, aes(distance, altitude),    color = 'green')

ggplot(df_phys, aes(distance, speed )) + geom_line() + geom_line(data = res, aes(X, V),    color = 'red')

ggplotly(ggplot(df_phys, aes(distance, speed * mph )) + geom_line() + geom_line(data = res, aes(X, V * mph),    color = 'red'))

ggplotly(ggplot(df_phys, aes(distance, speed )) + geom_line() + geom_line(data = res, aes(X, V),    color = 'red'))

ggplot(df_phys, aes(t/60, speed )) + geom_line() + geom_line(data = res, aes(time/60, V), color = 'red')
ggplot(df_phys, aes(t, distance )) + geom_line() + geom_line(data = res, aes(time, X),    color = 'red')

ggplot(df_phys, aes(power, speed ))     + geom_point()
ggplot(df_phys, aes(power, grade ))     + geom_point()

res[, power_drag := 0.5 * rho_air * V * V * V * parameters['c_drag'] ]
res[, power_grav := g_freefall * grade * V * parameters['m']]
res[, power_roll := g_freefall * cos(asin(grade)) * parameters['c_roll']   * V * parameters['m']]

res[, energy_kinetic   := 0.5*parameters['m'] * V^2 ]
res[, energy_potential  := g_freefall * parameters['m'] * altitude ]

res[order(time), work_drag := cumsum(power_drag)]
res[order(time), work_grav := cumsum(power_grav)]
res[order(time), work_roll := cumsum(power_roll)]
res[order(time), work := cumsum(power)]

res[X == max(X)]

ggplot(res) + geom_line( aes(mph*V, power_drag)) + geom_hline(yintercept = c(200, 300), linetype = 'dashed')
ggplot(res) + geom_line( aes(mph*V, power_roll))

approx(res$power_drag, res$V * mph, c(200, 250, 300), yleft = 0, yright = 0, rule=2)$y
approx(res$power_drag + res$power_roll, res$V * mph, c(200, 250, 300), yleft = 0, yright = 0, rule=2)$y
  
ggplot(res) + 
  geom_line( aes(X, power_drag, color = 'drag power')) +  
  geom_line( aes(X, power_grav, color = 'gravity power')) + 
  geom_line( aes(X, power_roll, color = 'roll power')) + 
  geom_line( aes(X, power_drag + power_grav + power_roll, color = 'power'))

ggplot(res) + 
  geom_line( aes(time, work_drag, color = 'drag work')) +  
  geom_line( aes(time, work_grav, color = 'gravity work')) + 
  geom_line( aes(time, work_roll, color = 'roll work')) +  # 7% of total
#  geom_line( aes(time, work, color = 'total work')) + 
  geom_line( aes(time, work_drag + work_grav + work_roll, color = 'work'))

ggplot(res) + 
  geom_line( aes(X, energy_kinetic, color = 'energy kinetic')) +  
  geom_line( aes(X, energy_potential, color = 'energy potential')) + 
  geom_line( aes(X, energy_kinetic + energy_potential, color = 'energy'))

ggplot(res) + 
  geom_line( aes(time, power_drag, color = 'drag power')) +  
  geom_line( aes(time, power_grav, color = 'gravity power')) + 
  geom_line( aes(time, power_roll, color = 'roll power')) + 
  geom_line( aes(time, power_drag + power_grav + power_roll, color = 'power'))


#Optimize parameters ----------------
bike_speed_obj <- function(my_opt_params){
  #my_opt_params = c(87.61159, 0.0025, 0.3086613)
  max_time = 60*40
  parameters <- c(m = my_opt_params[1], c_roll = my_opt_params[2], c_drag = my_opt_params[3])
  state      <- c(X = df_phys$distance[1], V = df_phys$speed[1])
  times      <- seq(0, max_time, by = 1)
  
  out <- ode(y = state, times = times, func = function(t, state, parameters) bike_ride(t, state, parameters, df_phys$distance, df_phys$grade, df_phys$t, df_phys$power), parms = parameters)
  res = data.table(out)
  res[V<0, V:=0 ]
  
  res[, zwift_v := approx(df_phys$distance, df_phys$speed, X, yleft = 0, yright = 0, rule=2)$y ]
  res[X < 1.7e4, mean((V - zwift_v)^2, na.rm = TRUE)] # 0.8156977
  #ggplot(res, aes(time, zwift_v *mph)) + geom_line() + geom_line(aes(time, V*mph),    color = 'red')
  #ggplot(res, aes(X, zwift_v *mph)) + geom_line() + geom_line(aes(X, V*mph),    color = 'red')
}
optim(c(85, 35, 30), function(x) bike_speed_obj(x*c(1, 1e-4, 1e-2)), method  = "Nelder-Mead", control = list(trace = TRUE, maxit = 30)) #2.000866
optim(c(85, 35, 30), function(x) bike_speed_obj(x*c(1, 1e-4, 1e-2)), method  = "L-BFGS-B", lower = c(80, 20, 20), upper = c(90, 50, 40), control = list(trace = 4, maxit = 40)) #2.000866
#84.9785772  0.0020000  0.3411642

library(rBayesianOptimization)
bike_speed_obj_ex <- function(m, c_roll, c_drag) {
  list(Score = -bike_speed_obj(c(m, c_roll, c_drag)), Pred = 0)
}
OPT_Res <- BayesianOptimization(bike_speed_obj_ex,
                                bounds = list(m = c(83, 90), c_roll = c(0.002, 0.004), c_drag = c(0.25, 0.4)),
                                init_points = 10, n_iter = 30, verbose = TRUE)
#Round = 38	m = 88.33416	c_roll = 0.0020	c_drag = 0.3152741	Value = -0.1183555

#grid search
n = 10
df_params = data.table(m = seq(83, 87, length.out = 10), c_roll = rep(0.0035, n), c_drag = rep(0.3, n) )
df_params = data.table(m = rep(85, n), c_roll = seq(0.0030, 0.004, length.out = 10), c_drag = rep(0.3, n) )
df_params[, error := bike_speed_obj(c(m,c_roll, c_drag)), by =.(seq(nrow(df_params))) ]
df_params[order(error)] #85.66667
#bike_speed_obj(c(df_params$m[2],df_params$c_roll[2], df_params$c_drag[2]))
ggplot(df_params, aes(m, error)) + geom_line() 
ggplot(df_params, aes(c_roll, error)) + geom_line()
ggplot(df_params, aes(c_drag, error)) + geom_line()

#Constant Power -----------
out <- ode(y = state, times = times, func = function(t, state, parameters) bike_ride(t, state, parameters, df_phys$distance, df_phys$grade, df_phys$t, pmax(0, 0*df_phys$power+300 + 0*runif(length(df_phys$power), -10, +10)) ), parms = parameters)
res = data.table(out)
res[V<0, V:=0 ]

approx(res$X, res$time, 5700, yleft = 0, yright = 0, rule=2)$y
#time to reach distance 5700, 
#200W - 1030.224 sec
#300W - 775.0919 sec
#300W with +-10, 685.4067
#274W - 823.6481 sec
#MyResult - 857.2153
#ggplotly(ggplot(df_phys, aes(distance, altitude )) + geom_line())
ggplot(df_phys, aes(distance, speed )) + geom_line() + geom_line(data = res, aes(X, V),    color = 'red')
ggplot(df_phys, aes(t, distance ))     + geom_line() + geom_line(data = res, aes(time, X), color = 'red') + geom_hline(yintercept = 5700)
ggplot(df_phys, aes(t, power ))     + geom_line() 

df_res = ldply(seq(100, 400, by = 50), function(my_const_power){
    out <- ode(y = state, times = times, func = function(t, state, parameters) bike_ride(t, state, parameters, df_phys$distance, df_phys$grade, df_phys$t, rep(my_const_power, length(df_phys$power))), parms = parameters)
  res = data.table(out)
  res[V<0, V:=0 ]
  my_time = approx(res$X, res$time, 5700, yleft = 0, yright = 0, rule=2)$y
  
  return(data.frame(my_const_power, my_time))
})
setDT(df_res)
df_res = df_res[my_const_power >= 200]

ggplot(df_res, aes(my_const_power, my_time)) + geom_line()

mean(approx(df_res$my_const_power, df_res$my_time, 300 + 30*rnorm(100))$y)


#Grade Variable Power ------------ 
hump = function(x, x1, x2, x3, x4, grade){
  y = x
  y[x<=x1] = 0
  y[x>x4] = 0
  y[x>x1 & x<=x2] = (x[x>x1 & x<=x2] - x1) * grade
  y[x>x2 & x<=x3] = (x2 - x1) * grade
  y[x>x3 & x<=x4] = (x2 - x1) * grade - (x[x>x3 & x<=x4] - x3) * grade
  return (y)
}
  
df_sim = data.table(distance = seq(0, 6e3))
#df_sim[, altitude := 10*exp(- (distance - 500) * (distance -500) / 5000)]
df_sim[, altitude := hump(distance, 1e3, 2e3, 3e3, 4e3, 0.05)]

df_sim[order(distance), grade     := (shift(altitude,-1) - shift(altitude))/(shift(distance,-1) - shift(distance))]
ggplot(df_sim, aes(distance, grade ))     + geom_line()
ggplot(df_sim, aes(distance, altitude ))     + geom_line() 

parameters <- c(m = 87.61159, c_roll = 0.0025, c_drag = 0.3086613)
state      <- c(X = 0, V = 0)
times      <- seq(0, 800, by = 1)

bike_ride_grade <- function(t, state, parameters, grade_d, grade_v, power) {
  with(as.list(c(state, parameters)), {
    grade = approx(grade_d, grade_v, X, yleft = 0, yright = 0, rule=2)$y
    alpha = asin(grade)
    dX <-  V
    dV <-   ( (power * ifelse(grade>0, 1.0, 1.0)/m) / pmax(0.01, abs(V) ) - 0.5 * rho_air * V * V * c_drag / m -  g_freefall * sin(alpha) - g_freefall * cos(alpha) * c_roll )
    list(c(dX, dV))
  })
}

out <- ode(y = state, times = times, func = function(t, state, parameters) bike_ride_grade(t, state, parameters, df_sim$distance, df_sim$grade, 200), parms = parameters)
res = data.table(out)
res[V<0, V:=0 ]
res[, grade    := approx(df_sim$distance, df_sim$grade, X, yleft = 0, yright = 0, rule=2)$y]
res[, altitude := approx(df_sim$distance, df_sim$altitude, X, yleft = 0, yright = 0, rule=2)$y]
res = res[X<=max(df_sim$distance)]

approx(res$X, res$time, 1000, yleft = 0, yright = 0, rule=2)$y
#time to reach distance 1000, 
#200W - 126.0615 sec
#300W - 103.5121 sec
#ggplotly(ggplot(df_phys, aes(distance, altitude )) + geom_line())
ggplot() + geom_line(data = res, aes(time, V*mph),    color = 'red')
ggplot() + geom_line(data = res, aes(X, V*mph),    color = 'red')
ggplot() + geom_line(data = res, aes(X, grade),    color = 'red')
ggplot(df_sim, aes(distance, altitude ))     + geom_line() + geom_line(data = res, aes(X, V * mph), color = 'red')

ggplot(res) + geom_line( aes(mph*V, 0.5 * rho_air * V * V * V * c_drag, color = 'drag power')) 

res[, power_drag := 0.5 * rho_air * V * V * V * parameters['c_drag'] ]
res[, power_grav := g_freefall * grade * V * parameters['m']]
res[, power_roll := g_freefall * cos(asin(grade)) * parameters['c_roll']   * V * parameters['m']]
res[, power := 200]

res[, energy_kinetic   := 0.5*parameters['m'] * V^2 ]
res[, energy_potential  := g_freefall * parameters['m'] * altitude ]

res[order(time), work_drag := cumsum(power_drag)]
res[order(time), work_grav := cumsum(power_grav)]
res[order(time), work_roll := cumsum(power_roll)]
res[order(time), work := cumsum(power)]

ggplot(res) + 
  geom_line( aes(X, power_drag, color = 'drag power')) +  
  geom_line( aes(X, power_grav, color = 'gravity power')) + 
  geom_line( aes(X, power_roll, color = 'roll power')) + 
  geom_line( aes(X, power_drag + power_grav + power_roll, color = 'power'))

ggplot(res) + 
  geom_line( aes(time, work_drag, color = 'drag work')) +  
  geom_line( aes(time, work_grav, color = 'gravity work')) + 
  geom_line( aes(time, work_roll, color = 'roll work')) + 
  geom_line( aes(time, work, color = 'total work')) + 
  geom_line( aes(time, work_drag + work_grav + work_roll, color = 'work'))

ggplot(res) + 
  geom_line( aes(X, energy_kinetic, color = 'energy kinetic')) +  
  geom_line( aes(X, energy_potential, color = 'energy potential')) + 
  geom_line( aes(X, energy_kinetic + energy_potential, color = 'energy'))

ggplot(res) + 
  geom_line( aes(time, power_drag, color = 'drag power')) +  
  geom_line( aes(time, power_grav, color = 'gravity power')) + 
  geom_line( aes(time, power_roll, color = 'roll power')) + 
  geom_line( aes(time, power_drag + power_grav + power_roll, color = 'power'))

ggplot() + geom_line(data = res, aes(time, V), color = 'red')

#Grade Variable Power: how much power increase on slope add ------------ 
run_cases = expand.grid(power = c(180, 200, 220), up_mult = c(0.9, 1.0, 1.1),  down_mult = c(0.9, 1.0, 1.1))

df_power_res = ldply(seq(nrow(run_cases)), function(i) { 
parameters <- c(m = 87.61159, c_roll = 0.0025, c_drag = 0.3086613)
state      <- c(X = 0, V = 0)
times      <- seq(0, 500, by = 1)

bike_ride_grade <- function(t, state, parameters, grade_d, grade_v, power) {
  with(as.list(c(state, parameters)), {
    grade = approx(grade_d, grade_v, X, yleft = 0, yright = 0, rule=2)$y
    alpha = asin(grade)
    dX <-  V
    dV <-   ( (run_cases$power[i] * ifelse(grade>0, run_cases$up_mult[i],  ifelse(grade<0, run_cases$down_mult[i], 1.0))/m) / pmax(0.01, abs(V) ) - 0.5 * rho_air * V * V * c_drag / m -  g_freefall * sin(alpha) - g_freefall * cos(alpha) * c_roll )
    list(c(dX, dV))
  })
}

out <- ode(y = state, times = times, func = function(t, state, parameters) bike_ride_grade(t, state, parameters, df_sim$distance, df_sim$grade, 200), parms = parameters)
res = data.table(out)
res[V<0, V:=0 ]
res[, grade    := approx(df_sim$distance, df_sim$grade, X, yleft = 0, yright = 0, rule=2)$y]
res[, altitude := approx(df_sim$distance, df_sim$altitude, X, yleft = 0, yright = 0, rule=2)$y]
res = res[X<=max(df_sim$distance)]
c(power = run_cases$power[i], time = res[, time[.N]], up_mult = run_cases$up_mult[i], down_mult = run_cases$down_mult[i])
})

setDT(df_power_res)
df_power_res[, mult := sprintf("up: %.1f, dn: %.1f", up_mult, down_mult) ]
df_power_res[df_power_res[up_mult == 1 & down_mult == 1], base_time := i.time, on = .(power)]

ggplot(df_power_res, aes(power, time, group = mult, color = mult)) + geom_point() + geom_line()

ggplot(df_power_res[power == 200], aes(up_mult, time-base_time, group = down_mult, color = factor(down_mult) )) + geom_point() + geom_line()

```

## Bike Power optimization 
m = 88.33416, c_roll = 0.0020, c_drag = 0.3152741
```{r bike_power_optimization, echo=FALSE, eval = FALSE}
library(deSolve)

mph = 3.6 / 1.60934 # m/sec to mph

#Grade Variable Power ------------ 
hump = function(x, x1, x2, x3, x4, grade){
  y = x
  y[x<=x1] = 0
  y[x>x4] = 0
  y[x>x1 & x<=x2] = (x[x>x1 & x<=x2] - x1) * grade
  y[x>x2 & x<=x3] = (x2 - x1) * grade
  y[x>x3 & x<=x4] = (x2 - x1) * grade - (x[x>x3 & x<=x4] - x3) * grade
  return (y)
}
  
df_sim = data.table(distance = seq(0, 6e3))
#df_sim[, altitude := 10*exp(- (distance - 500) * (distance -500) / 5000)]
df_sim[, altitude := hump(distance, 1e3, 2e3, 3e3, 4e3, 0.05)]

df_sim[order(distance), grade     := (shift(altitude,-1) - shift(altitude))/(shift(distance,-1) - shift(distance))]
ggplot(df_sim, aes(distance, grade ))     + geom_line()
ggplot(df_sim, aes(distance, altitude ))     + geom_line() 

parameters <- c(m = 87.61159, c_roll = 0.0025, c_drag = 0.3086613, g_freefall = 9.8, rho_air = 1.225)
state      <- c(X = 0, V = 0)
times      <- seq(0, 1000, by = 1)

bike_ride_grade <- function(t, state, parameters, grade_d, grade_v, power) {
  with(as.list(c(state, parameters)), {
    grade = approx(grade_d, grade_v, X, yleft = 0, yright = 0, rule=2)$y
    alpha = asin(grade)
    dX <-  V
    dV <-   ( (power /m) / pmax(0.01, abs(V) ) - 0.5 * rho_air * V * V * c_drag / m -  g_freefall * sin(alpha) - g_freefall * cos(alpha) * c_roll )
    list(c(dX, dV))
  })
}

out <- ode(y = state, times = times, func = function(t, state, parameters) bike_ride_grade(t, state, parameters, df_sim$distance, df_sim$grade, 200), parms = parameters)
res = data.table(out)
res[V<0, V:=0 ]
res[, grade    := approx(df_sim$distance, df_sim$grade, X, yleft = 0, yright = 0, rule=2)$y]
res[, altitude := approx(df_sim$distance, df_sim$altitude, X, yleft = 0, yright = 0, rule=2)$y]

ggplot(res, aes(X, V))     + geom_line()
ggplot(res[res$X<=max(df_sim$distance)], aes(X, power))     + geom_line() + geom_line(aes(X, altitude), color = 'blue') + geom_vline(xintercept = c(1e3, 2e3, 3e3, 4e3), linetype = 'dashed')
approx(res$X, res$time, max(df_sim$distance), rule=2)$y #710.0533 sec, at 200W, 142kJ
#728.7772 sec, at 190W
#710.0533 sec, at 200W
#692.9225 sec, at 210W
#677.1774 sec, at 220W

#power as function of speed
objective_function <- function(power_v, power_lut) {

  bike_ride <-function(power_mult) {
      bike_ride_parametric_power <- function(t, state, parameters, grade_d, grade_v, power_v, power_lut) {
      with(as.list(c(state, parameters)), {
        grade = approx(grade_d, grade_v, X, rule=2)$y
        alpha = asin(grade)
        power = 200*power_mult * approx(power_v, power_lut, V, rule=2)$y
        dX <-  V
        dV <-   ( (power/m) / pmax(0.01, abs(V) ) - 0.5 * rho_air * V * V * c_drag / m -  g_freefall * sin(alpha) - g_freefall * cos(alpha) * c_roll )
        list(c(dX, dV))
      })
    }
    out <- ode(y = state, times = times, func = function(t, state, parameters) bike_ride_parametric_power(t, state, parameters, df_sim$distance, df_sim$grade, power_v, power_lut), parms = parameters)
    res = data.table(out)
    res[, power := 200*power_mult * approx(power_v, power_lut, V, rule=2)$y]
    total_energy = res[res$X<=max(df_sim$distance), sum(power)]
    c(mean(res$power, na.rm = TRUE), approx(res$X, res$time, max(df_sim$distance), rule=2)$y, power_mult, total_energy)
  }
  
  power_mult = uniroot(function(x) bike_ride(x)[4] - 142e3, interval = c(0.1, 10) )$root
  
  return (bike_ride(power_mult))
}
#res = res[X<=max(df_sim$distance)]
power_v   = c(0, 5, 8, 10,  15)
power_lut = c(2.0, 2.0, 1.9740906, 0.1000000, 0.1000000) #2.193733e+00
#power_lut = rep(200, length(power_v))
objective_function(power_v, power_lut) #598 sec

#approx(c(0, 10), c(250, 100), power_v, rule=2)$y

objective_function(c(0, 20), c(200, 200)) #flat 200W 710 sec
objective_function(c(0, 20), c(220, 220)) #flat 220W 710 sec
objective_function(c(0, 10), c(250, 100)) #667.346504 with 200W average

plot(power_v * mph, 3.633647e+00 * power_lut * 200)

optim(power_lut, function(x) objective_function(power_v, x)[2], method  = "Nelder-Mead", control = list(trace = TRUE, maxit = 30)) #2.000866
optim(power_lut, function(x) objective_function(power_v, x)[2], method  = "L-BFGS-B", lower = rep(100, length(power_v)), upper =  rep(600, length(power_v)), control = list(trace = 2, maxit = 40)) #2.000866

library(dfoptim)
hjkb(power_lut, function(x) objective_function(power_v, x)[2], lower = 0.1, upper = 2.0)

library(rBayesianOptimization)
objective_function_ex <- function(p1, p2, p3, p4) {
  list(Score = -objective_function(power_v, c(p1, p2, p3, p4))[2], Pred = 0)
}
OPT_Res <- BayesianOptimization(objective_function_ex,
                                bounds = list(p1 = c(0.1, 2.0), p2 = c(0.1, 2.0), p3 = c(0.1, 2.0), p4 = c(0.1, 2.0)),
                                init_points = 10, n_iter = 10, verbose = TRUE)
#Round = 14	p1 = 0.1000	p2 = 2.0000	p3 = 0.1000	p4 = 0.1000	Value = -602.1760 
#2d grid 
df_grid = data.table(expand.grid(p1 = seq(0.5, 1.5, by = 0.5), p2 = seq(0.5, 1.5, by = 0.5)))

df_res = ldply(seq(nrow(df_grid)), function(i){
  c(i, objective_function(c(0, 10), c(df_grid$p1[i], df_grid$p2[i])))
})
setDT(df_res)
ggplot(cbind(df_res, df_grid)[order(V3)], aes(p1, p2, fill = V3, label = sprintf('%.1f', V3))) + geom_tile() + geom_text()

#2d random guess
df_res = ldply(seq(10), function(i){
  my_power_mult = runif(length(power_v), 0.2, 2.0)
  c(i, objective_function(power_v, my_power_mult), my_power_mult)
})
setDT(df_res)

```
