---
title: "Beta Confidence Intervals"
author: "Alex"
date: "February 10, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 8, fig.height = 6, dpi = 240)

library(data.table)
library(plyr)
library(ggplot2)
library(grid)
library(gridExtra)
library(wesanderson)

source('C:/Dev/Kaggle/Utils/common.R')


```

## Mean and sample size
The beta distribution may also be parametrized in terms of its mean µ (0 < µ < 1) and 
sample size n = a + ß. Then a = µ * n and  ß = (1 - µ) * n
variance is  (1 - µ) * µ / (n + 1) = a * ß /(a + ß)^2 * (a + ß + 1)
for uniform prior n = sample_size + 2
Beta(0,0) prior
```{r beta00_dist}

df = data.table(x = seq(0, 1, by =0.01))

mean = 0.8
n = 10
conf_int = 0.95

plots = llply(seq(1,17, by = 2), function(n) {
  
  alpha = mean * (n ) #add 2 for uniform priors
  beta = (1 - mean) * (n ) #add 2 for uniform priors
   
  beta_ci = beta_conf(mean, n,conf_int)
  
 p =  ggplot(df, aes(x, dbeta(x, alpha, beta))) + geom_line() + 
  geom_vline(xintercept = mean, colour = 'red', linetype = 2) + 
  geom_vline(xintercept = beta_ci[1], colour = 'blue', linetype = 2) +
  geom_vline(xintercept = beta_ci[2], colour = 'blue', linetype = 2)+
    ggtitle(paste('n=',n))
 return( p )
})

marrangeGrob(plots, nrow = 3, ncol = 3, top = NULL)


```

## Convergence
```{r beta_dist_conv}

mean = 0.8
n = 10
conf_int = 0.95

df = ldply(seq(0,100, by = 1), function(n) {
 
  beta_ci1 = beta_conf(mean, n,  conf_int)
  beta_ci2 = beta_conf(mean, n+2,conf_int)
  
  res =  data.frame(n, mean, 
                    ci_lo1 = beta_ci1[1], ci_up1 = beta_ci1[2], 
                    ci_lo2 = beta_ci2[1], ci_up2 = beta_ci2[2])
 return( res )
})

ggplot(df, aes(n, ci_lo1)) + 
  geom_line()+
  geom_line(aes(n, ci_up1)) + 
   geom_line(aes(n, ci_lo2), linetype =2, color = 'red') + 
   geom_line(aes(n, ci_up2), linetype =2, color = 'red') + 
  scale_y_continuous(limits = c(0, 1))

ggplot(df, aes(log(n), log(mean-ci_lo1) )) + 
  geom_line()+
  geom_line(aes(log(n), log(ci_up1-mean) )) + 
   geom_line(aes(log(n), log(mean-ci_lo2) ), linetype =2, color = 'red') + 
   geom_line(aes(log(n), log(ci_up2-mean) ), linetype =2, color = 'red')

```

