---
title: "Variable Importance"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

rm(list = ls())
knitr::opts_chunk$set(echo = TRUE, fig.width = 8, fig.height = 5, dpi = 240)
options(warn=-1)

library(gbm)
library(data.table)
library(plyr)
library(stringi)
library(ggplot2)
library(gridExtra)
library(zip)
library(xgboost)
library(wesanderson)
library(knitr)

library(rBayesianOptimization)
#library(caret)

#working_folder = 'C:/Dev/Kaggle/'
working_folder = 'F:/Github/KaggleSandbox'

source(file.path(working_folder, '/Utils/common.R'))
```

## Data

```{r load_data}
df = fread(file.path(working_folder,'/Titanic/input/train.csv'))

df[,Survived := as.numeric(Survived)]

cat_vars = c('Pclass','Sex','Embarked')
df[, (cat_vars):=lapply(.SD, as.factor), .SDcols = cat_vars]

df[, Cabin_count := stri_count_fixed(df$Cabin, ' ') + 1 ]
df[, Cabin_char := stri_sub(df$Cabin, length = 1) ]

factor_vars = names(df)[sapply(df, class) == 'factor']

actual = df$Survived

```

## GBM Model

```{r gbm_model, echo=FALSE}
formula.gbm = formula(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked)

model_vars = all.vars(formula.gbm) %!in_set% c('Survived')

var.monotone = rep(0, length(model_vars))
mon_inc_vars = c('Fare')
mon_dec_vars = c('Age')
var.monotone[model_vars %in% mon_inc_vars]  =  1
var.monotone[model_vars %in% mon_dec_vars]  = -1

model.gbm  = gbm(formula.gbm, 
                            distribution = "bernoulli",
                            n.trees = 1500,
                            cv.folds=10,
                            shrinkage = 0.01,
                            interaction.depth=3,
                 train.fraction = 1.0,
                 bag.fraction = 0.9,
                 n.cores = 4,
                 var.monotone = var.monotone,
                 data = df[,all.vars(formula.gbm), with = F],
                 verbose = FALSE)

plot_gbmiterations(model.gbm)#0.84

best_it.gbm = gbm.perf(model.gbm, plot.it = F)
pred.gbm = predict(model.gbm, n.trees = best_it.gbm, type = 'response')
gbm.roc.area(actual, pred.gbm) #0.9229753

var_inf = summary(model.gbm, n.trees = best_it.gbm, plotit = F)
plot_gbminfluence(var_inf)
print(var_inf)

plots = plot_gbmpartial(model.gbm, best_it.gbm, as.character(var_inf$var), output_type = 'response')
marrangeGrob(plots, nrow = 3, ncol = 3, top = NULL)

var_interaction = gbm_interactions(model.gbm, df, iter = best_it.gbm, min_influence = 1, degree = 2) 
plot_gbminteractions(subset(var_interaction, interaction_score>0.05))
print(var_interaction)
setDT(var_interaction)
#var_interaction[, var1:=stri_split_fixed(vars, '|', simplify =T)[,1]]
#var_interaction[, var2:=stri_split_fixed(vars, '|', simplify =T)[,2]]


plots = plot_gbmpartial_2d(model.gbm, best_it.gbm, as.character(subset(var_interaction,interaction_score>0.1)$vars), output_type = 'link')
marrangeGrob(plots, nrow = 3, ncol = 2, top = NULL)

plots = plot_gbmpartial_2d(model.gbm, best_it.gbm, as.character(subset(var_interaction,interaction_score>0.1)$vars), output_type = 'response')
marrangeGrob(plots, nrow = 3, ncol = 2, top = NULL)

plot_binmodel_predictions(actual, pred.gbm)
#gbm.roc.area(actual, pred.gbm)

#all vars
plots = llply(all.vars(formula.gbm)[-1], function(var_name) {
  p = plot_profile(pred.gbm, actual, df[[var_name]], error_band = 'binom') +
    ggtitle(var_name) +  theme(title =element_text(size=6))
  return( p )
})
marrangeGrob(plots, nrow = 3, ncol = 2, top = NULL)


```

## GBM: b opt
```{r gbm_model_param_tune, echo=FALSE, eval = FALSE}

df_s = df[,all.vars(formula.gbm), with = F]

#cv_folds <- KFold(df$Survived, nfolds = 10, stratified = TRUE, seed = 0)

gbm_bayes <- function(bag_fraction, my_shrinkage, interaction_depth) {
  
  set.seed(1234)
  model.gbm_test  = gbm(formula.gbm,
                            distribution = "bernoulli",
                            n.trees = 2000,
                            cv.folds=10,
                            shrinkage = my_shrinkage,
                            interaction.depth=interaction_depth,
                            train.fraction = 1.0,
                            bag.fraction = bag_fraction,
                            n.cores = 4,
                            var.monotone = var.monotone,
                            data = df_s,
                            verbose = FALSE)
  #best_it.gbm_test = gbm.perf(model.gbm_test, plot.it = F)
  #pred.gbm_test = predict(model.gbm_test, n.trees = best_it.gbm_test, type = 'response')
  return ( list(Score = -min(model.gbm_test$cv.error, na.rm = T),   Pred = 0) )
}

my_bounds = list(my_shrinkage = c(0.001, 0.1),
                 bag_fraction = c(0.5, 1.0),
                 interaction_depth = c(1L, 10L))

opt_res <- BayesianOptimization(gbm_bayes,
                                bounds = my_bounds,
                                init_grid_dt = NULL, init_points = 10, n_iter = 30,
                                acq = "ucb",  #"ucb", "ei" or "poi"
                                kappa = 2.576, eps = 0.0,
                                verbose = TRUE)

#fixed seed(1234), ucb,  init_points = 10, n_iter = 20, kappa = 2.576, eps = 0.0 (non-mon)
#my_shrinkage = 0.0937	bag_fraction = 0.8774	interaction_depth = 3.0000 
```

### GBM Model: Partial Dependency

```{r gbm_model_pd, echo=FALSE}

n_profile = 100
n_sample = 100
sample_index = sample.int(nrow(df),n_sample )

plots = llply(as.character(var_inf$var), function(vname) {
  
  x_factor = is.factor(df[[vname]])

  range = NULL
  if( x_factor ){
    range = levels(df[[vname]])
  }else{
    min_x = min( df[[vname]], na.rm = T )
    max_x = max( df[[vname]], na.rm = T )
    range = seq(min_x, max_x, length.out = n_profile)
  }
  
  df_profiles = ldply(sample_index, function(index){
    
    if(x_factor)
      x_range = as.factor(unique( c(as.character(df[[vname]][index]), range) ))
    else
      x_range = unique( c(df[[vname]][index], range) )
    
    temp = df[rep(index, length(x_range)),]
    temp[[vname]] = x_range
    temp[['model']] = predict(model.gbm, n.trees = best_it.gbm, type = 'response', newdata = temp)
    temp[['sample_id']] = index
    
    return (temp)
  })
  
  setDT(df_profiles)
  
  rel_interactions = var_interaction[stri_detect_fixed(as.character(vars), vname),]
  setorder(rel_interactions, -interaction_score)
  
  strongest_interaction = ''
  
  if(nrow(rel_interactions)>0)
     strongest_interaction = stri_replace_all_fixed(stri_replace_all_fixed( as.character(rel_interactions$vars[1]), vname, ''), '|','')
  
  df_profiles_avg = df_profiles[, .(avg=mean(model, na.rm = T), .N), by = c(vname)]
  
  p = ggplot(cbind(df[sample_index,c(vname), with = F], p = pred.gbm[sample_index]), aes_string(vname, 'p')) + 
    geom_point(color = 'red') + geom_rug(alpha = 0.2,  position = position_jitter(width = ifelse(x_factor,0.25, 0) , height = 0)) +
    geom_line(data = df_profiles, aes_string(vname, 'model', group = 'sample_id', color = 'Sex'), alpha = 0.2) +
    #geom_line(data = df_profiles, aes_string(vname, 'model', group = 'sample_id'), color = 'blue', alpha = 0.2) + 
    geom_line(data = df_profiles_avg[N>=n_sample,], aes_string(vname, 'avg'), color = 'black', size = 1) + 
    ggtitle(vname) + theme(legend.position = 'none')
  
  if(x_factor)
    p = p + geom_point(data = df_profiles_avg[N>=n_sample,], aes_string(vname, 'avg'), color = 'black')
  
  return (p)
})
marrangeGrob(plots, nrow = 2, ncol = 2, top = NULL)



```

### GBM Model: Permutation importance

```{r gbm_model_importance, echo=FALSE}

sum_sqr <-function(x) {sum(x * x, na.rm = T)}

runs = 100

perm_importance = ldply(as.character(var_inf$var), function(vname) {
  
  orig_x = df[[vname]]
  
  res = ldply(seq(runs), function(i){
    df[[vname]] = sample(orig_x, length(orig_x))
    
    pred.gbm_i = predict(model.gbm, n.trees = best_it.gbm, type = 'response', newdata = df)
    
    data.frame(i, auc = gbm.roc.area(actual, pred.gbm_i), ks = binmodel_ks(actual, pred.gbm_i) )
  })
  df[[vname]] = orig_x
  res$name = vname
  
  return(res)
})

setDT(perm_importance)

auc_orig = gbm.roc.area(actual, pred.gbm)

ggplot(perm_importance, aes(ks, auc_orig - auc, group = name, color = name)) + geom_point()

importance = perm_importance[,.(diff = auc_orig - mean(auc), std=sd(auc) ), by = .(name)]
setorder(importance, -std)

importance$rating = 100*importance$std * importance$std/sum_sqr(importance$std)

kable(importance)

plot_gbminfluence(data.frame(var = importance$name, rel.inf = importance$rating))

ggplot(importance, aes(diff, std, group = name, color = name, label = name)) + geom_point() + 
#  geom_label(hjust = 0) +
  geom_text(hjust = 0, angle = 0, fontface = "bold", check_overlap = TRUE)

ggplot(perm_importance, aes(auc, group = reorder(name,auc), fill = reorder(name,auc))) + 
  geom_density(alpha = 0.8, adjust = 0.5)  + theme(legend.position = 'bottom')

ggplot(perm_importance, aes(reorder(name,auc), auc)) + 
  #geom_violin(adjust = 0.5) + 
  geom_boxplot(color = 'red') +
  geom_jitter(height = 0, width = 0.2, alpha = 0.5) + 
  geom_hline(yintercept = gbm.roc.area(actual, pred.gbm), color = 'red')

```

## Linear Model: Permutation importance

```{r linear_model_importance, echo=FALSE}

n_points = 1000

x1 = rnorm(n_points)
x2 = 0.5*rnorm(n_points)

df_lm = data.frame(y = 2*x1 + x2 + 0.5 * rnorm(n_points), x1, x2)

actual = df_lm$y

formula.lm = as.formula(y ~ x1 + x2)

model.lm = lm(formula.lm, df_lm)

summary(model.lm)

pred.lm = predict(model.lm, newdata = df_lm)

sum_sqr <-function(x) {sum(x * x, na.rm = T)}

runs = 100

perm_importance = ldply(all.vars(formula.lm)[-1], function(vname) {
  
  orig_x = df_lm[[vname]]
  
  res = ldply(seq(runs), function(i){
    df_lm[[vname]] = sample(orig_x, length(orig_x))
    
    pred.lm_i = predict(model.lm, newdata = df_lm)
    
    data.frame(i, r2 = summary(lm(actual ~ pred.lm_i))$r.squared )
  })
  orig_x = df_lm[[vname]]
  res$name = vname
  
  return(res)
})

setDT(perm_importance)

r2_orig = summary(lm(actual ~ pred.lm))$r.squared

importance = perm_importance[,.(diff = r2_orig - mean(r2), std=sd(r2) ), by = .(name)]
setorder(importance, -std)

importance$rating = 100*importance$std * importance$std/sum_sqr(importance$std)

kable(importance)

plot_gbminfluence(data.frame(var = importance$name, rel.inf = importance$rating))

ggplot(importance, aes(diff, std, group = name, color = name, label = name)) + geom_point() + 
#  geom_label(hjust = 0) +
  geom_text(hjust = 0, angle = 0, fontface = "bold", check_overlap = TRUE)

ggplot(perm_importance, aes(r2, group = reorder(name,r2), fill = reorder(name,r2))) + 
  geom_density(alpha = 0.8, adjust = 0.5)  + theme(legend.position = 'bottom')

ggplot(perm_importance, aes(reorder(name,r2), r2)) + 
  #geom_violin(adjust = 0.5) + 
  geom_boxplot(color = 'red') +
  geom_jitter(height = 0, width = 0.2, alpha = 0.5) + 
  geom_hline(yintercept = gbm.roc.area(actual, pred.gbm), color = 'red')

```




