---
title: "Wavelet demo"
author: "Alex"
date: "November 21, 2018"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE, fig.width = 8, fig.height = 5, dpi = 240)
options(warn=-1)

library(wmtsa)
library(WaveletComp)
library(dplR)
library(RColorBrewer)

working_folder = 'C:/Dev/Kaggle/'
#working_folder = 'F:/Github/KaggleSandbox'
#working_folder = file.path(Sys.getenv("HOME"), 'source/github/KaggleSandbox/')

source(file.path(working_folder, '/Utils/common.R'))
```

##Wavelet Example: dplR
```{r wavelet_example}
set.seed(1234)

n = 1024
x = seq(from = 0, to = 10, length.out = n)
y = sin(2*x) + sin(10*x) + 0.5*sin(20*x) + sin(50*x)

#2*pi/(2*mean(diff(x)))

out.wave <- morlet(y1 = y, x1 = x, p2 = 10, dj = 0.2, siglvl = 0.99)

levs <- quantile(out.wave$Power, probs = seq(0, 1, length.out = 11))
wavelet.plot(out.wave, wavelet.levels = levs, add.sig = FALSE)

# ------------
n = 10240
x = seq(from = 0, to = 100, length.out = n)
y = sin(x*x)
#2*pi/(2*mean(diff(x)))

out.wave <- morlet(y1 = y, x1 = x, p2 = 10, dj = 0.2, siglvl = 0.99)

levs <- quantile(out.wave$Power, probs = seq(0, 1, length.out = 11))
wavelet.plot(out.wave, wavelet.levels = levs, add.sig = FALSE)

wavelet.plot(out.wave, wavelet.levels = levs, add.sig = FALSE,key.cols=rev(brewer.pal(10, "Spectral")))

```

##Wavelet Example: WaveletComp
```{r wavelet_example2}
set.seed(1234)

n = 1024
x = seq(from = 0, to = 10, length.out = n)
y = sin(2*x) + sin(10*x) + 0.5*sin(20*x) + sin(50*x)
df = data.frame(x, y)

my.w <- analyze.wavelet(df, "y",
loess.span = 0,
dt = 1, dj = 0.1,
lowerPeriod = 2,
upperPeriod = 1024,
make.pval = TRUE, n.sim = 1)

wt.image(my.w, color.key = "quantile", n.levels = 10,
legend.params = list(lab = "wavelet power levels", mar = 4.7))

n = 10240
x = seq(from = 0, to = 100, length.out = n)
y = sin(x*x)
df = data.frame(x, y)

my.w <- analyze.wavelet(df, "y",
loess.span = 0,
dt = 1, dj = 0.1,
lowerPeriod = 2,
upperPeriod = 1024,
make.pval = TRUE, n.sim = 1)

wt.image(my.w, color.key = "quantile", n.levels = 10,
legend.params = list(lab = "wavelet power levels", mar = 4.7))
```
