---
title: "Covid-19"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(ggplot2)
library(forcats)
library(zoo)
library(ggdendro)
library(lubridate)
library(usmap)
library(plyr)
library(gridExtra)

working_folder = 'D:/Github/KaggleSandbox/'
#working_folder = file.path(Sys.getenv("HOME"), 'source/github/KaggleSandbox/')
source(file.path(working_folder, 'Utils/common.R'))
```

## Load Data

```{r load Data}

df = fread('https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv') 

df[, date := as.Date(date)]

df_usa = df[, .(cases = sum(cases),deaths = sum(deaths), fips = 0, state = 'USA' ), by = .(date)]
df = rbind(df, df_usa)
setkeyv(df, c('date', 'state'))

df[, new_cases  := cases  - shift(cases), by = .(state)]
df[, new_deaths := deaths - shift(deaths), by = .(state)]

df[, new_cases_avg_7d   := rollmeanr(new_cases, k = 7, na.pad = TRUE), by = .(state)]
df[, new_cases_avg_14d  := rollmeanr(new_cases, k = 14, na.pad = TRUE), by = .(state)]
df[, new_cases_avg_28d  := rollmeanr(new_cases, k = 28, na.pad = TRUE), by = .(state)]
df[, new_cases_avg_60d  := rollmeanr(new_cases, k = 60, na.pad = TRUE), by = .(state)]
df[, new_cases_avg_14d_inc :=new_cases_avg_14d - shift(new_cases_avg_14d),  by = .(state)]

df[, new_deaths_avg_7d   := rollmeanr(new_deaths, k = 7, na.pad = TRUE), by = .(state)]
df[, new_deaths_avg_14d  := rollmeanr(new_deaths, k = 14, na.pad = TRUE), by = .(state)]
df[, new_deaths_avg_28d  := rollmeanr(new_deaths, k = 28, na.pad = TRUE), by = .(state)]
df[, new_deaths_avg_60d  := rollmeanr(new_deaths, k = 60, na.pad = TRUE), by = .(state)]

```


## Load County Data

```{r load Data}

df_county = fread('https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv')
df_county[, date := as.Date(date)]
setkeyv(df_county, c('date', 'county', 'state'))

df_county[, new_cases  := cases  - shift(cases), by = .(county, state)]
df_county[, new_deaths := deaths - shift(deaths), by = .(county, state)]

ggplot(df_county[state ==  'North Carolina'], aes(date, new_cases)) + geom_line() + geom_smooth(span = 0.3, se = FALSE, color = 'red') + facet_wrap(~county, scales = 'free_y')
ggplot(df_county[state ==  'North Carolina'], aes(date, new_deaths)) + geom_line() + geom_smooth(span = 0.3, se = FALSE, color = 'red') + facet_wrap(~county, scales = 'free_y')


```


## Load Global Data

```{r load_global_Data}

#Load cases
df_glob        = fread('https://github.com/CSSEGISandData/COVID-19/raw/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv')
df_glob = melt(df_glob, id.vars = c('Province/State','Country/Region','Lat','Long'))
df_glob[, date := as.Date(variable, format = '%m/%d/%y')]
setnames(df_glob, c('Country/Region','Province/State','value'), c('region', 'state', 'cases'), skip_absent=TRUE)

#Load deaths
df_glob_deaths = fread('https://github.com/CSSEGISandData/COVID-19/raw/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv')
df_glob_deaths = melt(df_glob_deaths, id.vars = c('Province/State','Country/Region','Lat','Long'))
df_glob_deaths[, date := as.Date(variable, format = '%m/%d/%y')]
setnames(df_glob_deaths, c('Country/Region','Province/State','value'), c('region', 'state', 'deaths'), skip_absent=TRUE)

df_glob[df_glob_deaths, deaths:=i.deaths, on = .(region, state, date)]

df_glob[order(date), new_cases  := cases  - shift(cases), by = .(region, state)]
df_glob[order(date), new_deaths  := deaths  - shift(deaths), by = .(region, state)]
df_glob[order(date), new_cases_avg_7d    := rollmeanr(new_cases,  k = 7, na.pad = TRUE), by = .(region, state)]
df_glob[order(date), new_deaths_avg_7d   := rollmeanr(new_deaths, k = 7, na.pad = TRUE), by = .(region, state)]


my_regions = c('United Kingdom','Ukraine', 'Russia','Israel', 'US', 'India', 'Germany', 'Brazil', 'Mexico', 'Sweden', 'Japan', 'Argentina')
ggplot(df_glob[region %in% my_regions & state  == '' ], aes(date, new_cases_avg_7d)) + geom_line() + facet_wrap(~region, scales = 'free_y')

ggplot(df_glob[region %in% my_regions & state  == '' ], aes(date, new_deaths_avg_7d)) + geom_line() + facet_wrap(~region, scales = 'free_y')


##--- Global Case to Deaths model

library(glmnet)
library(plyr)

get_all_coefs<-function(glmnet_obj){
  res = ldply(glmnet_obj$lambda, function(lambda){
    temp = data.matrix(coef(glmnet_obj,s=lambda))
    data.frame(var_name = rownames(temp), coef = as.numeric(temp), lambda)
  })
  return(res)
}

for(i in seq(90)) {
  vname = sprintf('new_cases_rm_%02d', i)
  df_glob[order(date), c(vname) := rollmeanr(new_cases, k = i, fill = NA), by =.(region, state)]  
}

model_rm_vars = names(df_glob)[ grep('new_cases_rm_', names(df_glob)) ]

x=data.matrix(df_glob[date < '2021-07-01' & date > '2020-07-01', c('new_deaths_avg_7d', model_rm_vars), with = FALSE])
index = complete.cases(x)
y = x[index, 1]
x = x[index,-1]

cvob3=cv.glmnet(x, y, family="gaussian", nfolds = 10, relax = FALSE)
plot(cvob3)

coef_path = data.table(get_all_coefs(cvob3))
coef_path[order(var_name), weight := seq(0, .N-1),  by =.(lambda)]
coef_path[order(var_name,  decreasing = TRUE), adj_coef := cumsum(coef / weight),  by =.(lambda)]
coef_path[, dof:=sum(coef!=0), by =.(lambda)]
coef_path[var_name != '(Intercept)', .( sum(coef),  sum(adj_coef)), by =.(lambda)] #sum of the coefs  -0.013400167
coef_path[var_name != '(Intercept)' & lambda == cvob3$lambda.1se & coef != 0]
coef_path[var_name != '(Intercept)' & dof == 4 & coef != 0]

imp_vars = as.character(unique( coef_path[lambda >= cvob3$lambda.1se & abs(coef) >0, var_name] ))

ggplot(coef_path[var_name != '(Intercept)'], aes(var_name, log(lambda), fill = atan(1e4*coef) )) + geom_tile() +  
  theme(axis.text.x  = element_text(angle=90)) + 
  geom_hline(yintercept = log(c(cvob3$lambda.1se, cvob3$lambda.min)), linetype = 'dashed') + 
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0)

summary(lm('new_deaths_avg_7d ~ new_deaths_avg_7d_pred', df_glob))
summary(lm('new_deaths_avg_7d ~ new_cases_rm_36', df_glob))

#summary(lm('new_deaths ~ new_deaths_pred', df))
#summary(lm('new_deaths ~ new_cases_rm_50', df))

model.lm = lm('new_deaths_avg_7d ~ new_cases_rm_36', df_glob)
df_glob[, new_deaths_avg_7d_pred := predict(model.lm, df_glob[,model_rm_vars, with = F])]
ggplot(df_glob[region %in% my_regions & state  == '' ], aes(date, new_deaths_avg_7d)) + geom_line() + geom_line(aes(date, new_deaths_avg_7d_pred), color = 'red') + facet_wrap(~region, scales = 'free_y')
ggplot(df_glob[region %in% my_regions & state  == '' ], aes(new_deaths_avg_7d, new_deaths_avg_7d_pred)) + geom_point() + facet_wrap(~region, scales = 'free')

ggplot(df_glob[region %in% my_regions & state  == '' ], aes(date, new_deaths_avg_7d)) + geom_line() + geom_line(aes(date, new_deaths_avg_7d_pred), color = 'red') + facet_wrap(~region)
```


## Map

```{r maps, echo=FALSE}

df_last = df[date == max(date)]
state_pop = data.table(statepop)

df_last[state_pop, pop:=i.pop_2015, on = .(state = full)]

df_last[, new_cases_avg_7d_per_capita:=1e6*new_cases_avg_7d/pop]

plot_usmap(data = df_last, values = 'new_cases_avg_7d_per_capita') + theme(legend.position = "right") + 
  scale_fill_custom('mixed', discrete = FALSE)

plot_usmap(data = df_last, values = 'new_cases_avg_7d') + theme(legend.position = "right") + 
  scale_fill_custom('mixed', discrete = FALSE)

div_palettes  = c('BrBG', 'PiYG', 'PRGn', 'PuOr', 'RdBu', 'RdGy', 'RdYlBu', 'RdYlGn', 'Spectral')
seq_palettes  = c('Blues', 'BuGn', 'BuPu', 'GnBu', 'Greens', 'Greys', 'Oranges', 'OrRd', 'PuBu', 'PuBuGn', 'PuRd', 'Purples', 'RdPu','Reds', 'YlGn', 'YlGnBu', 'YlOrBr', 'YlOrRd')
plots = llply(seq_palettes, function(pal) {
  plot_usmap(data = df_last, values = 'new_cases_avg_7d_per_capita') + theme(legend.position = "right") + 
  scale_fill_distiller(palette = pal) + ggtitle(pal)
})
marrangeGrob(plots, nrow = 3, ncol = 3, top = NULL)

```


## Plots

```{r plots, echo=FALSE}
my_states = c('Connecticut', 'New Jersey', 'New York', 'North Carolina', 'Georgia', 'Texas', 'California', 'Minnesota', 'Florida',  'USA', 'Ohio', 'Pennsylvania')

ggplot(df[state %in% c('New Jersey', 'North Carolina')], aes(date, cases, group = state, color = state)) + geom_line()
ggplot(df[state %in% c('New Jersey', 'North Carolina')], aes(date, new_cases, group = state, color = state)) + geom_line()
ggplot(df[state %in% c('New Jersey', 'North Carolina')], aes(date, deaths, group = state, color = state)) + geom_line()

ggplot(df[state %in% my_states], aes(date, cases, group = state, color = state)) + geom_line() + facet_wrap(~state, scales = 'free_y')
ggplot(df[state %in% my_states], aes(date, new_cases)) + geom_line() + geom_smooth(span = 0.1, se = FALSE, color = 'red') + facet_wrap(~state, scales = 'free_y')
ggplot(df[state %in% my_states], aes(date, new_deaths)) + geom_line() + geom_smooth(span = 0.3, se = FALSE, color = 'red') + facet_wrap(~state, scales = 'free_y')
ggplot(df[state %in% my_states], aes(date, new_deaths_avg_7d)) + geom_line() + facet_wrap(~state, scales = 'free_y')
ggplot(df[state %in% my_states], aes(date, new_cases_avg_7d)) + geom_line() + facet_wrap(~state, scales = 'free_y')

ggplot(df[state %in% my_states], aes(make_date(2020, month(date), day(date)), new_cases_avg_7d, group = year(date), color =  factor(year(date)) )) + geom_line() + facet_wrap(~state, scales = 'free_y')

ggplot(df[state %in% my_states], aes(1e-6*cases, 1e-3*deaths)) + geom_line() + facet_wrap(~state, scales = 'free')

ggplot(df[state %in% my_states], aes(log10(cases+1), log10(new_cases_avg_7d+1) )) + geom_line() + geom_point(data = df[state %in% my_states & date == max(date)], color = 'red' ) + facet_wrap(~state, scales = 'free')

ggplot(df[state %in% my_states], aes(new_cases_avg_28d, new_deaths_avg_7d )) + geom_path() + geom_point(data = df[state %in% my_states & date == max(date)], color = 'red' ) + facet_wrap(~state, scales = 'free')

ggplot(df[state %in% my_states], aes(cases, deaths )) + geom_line() + facet_wrap(~state, scales = 'free')
ggplot(df[state %in% my_states], aes(date, new_deaths_avg_60d/new_cases_avg_60d )) + geom_line() + facet_wrap(~state, scales = 'free')
ggplot(df[state %in% my_states], aes(date, 1e-3*deaths)) + geom_line() + facet_wrap(~state, scales = 'free_y')

#where cases are increasing
inc_states = df[date == max(date)][order(-new_cases_avg_14d_inc), head(state,16) ]
ggplot(df[state %in% inc_states], aes(date, new_cases_avg_7d)) + geom_line() + geom_line(aes(date, new_cases_avg_14d), color = 'red', size = 1) + facet_wrap(~state, scales = 'free_y') #+ geom_smooth(span = 0.3, se = FALSE, color = 'red', alpha = 0.3)

ggplot(df[state %in% my_states], aes(date, 1e-3*cases)) + geom_line() +  facet_wrap(~state)
ggplot(df[state %in% my_states], aes(date, 1e-3*deaths)) + geom_line() +  facet_wrap(~state)
ggplot(df[state %in% my_states], aes(date, 1e-3*deaths)) + geom_line() +  facet_wrap(~state, scales = 'free_y')

ggplot(df[state %in% my_states], aes(date, 100*deaths/cases)) + geom_line() +  facet_wrap(~state)

ggplot(df[date == max(date),], aes(fct_reorder(state,100*deaths/cases), 100*deaths/cases)) + geom_bar(stat = 'identity') + coord_flip()

```

## Death as function of previous cases 

```{r death_model, echo=FALSE}
library(glmnet)
library(plyr)

get_all_coefs<-function(glmnet_obj){
  res = ldply(glmnet_obj$lambda, function(lambda){
    temp = data.matrix(coef(glmnet_obj,s=lambda))
    data.frame(var_name = rownames(temp), coef = as.numeric(temp), lambda)
  })
  return(res)
}

for(i in seq(90)) {
  vname = sprintf('new_cases_rm_%02d', i)
  df[order(date), c(vname) := rollmeanr(new_cases, k = i, fill = NA), by =.(state)]  
}

#ggplot(df[state %in% my_states], aes(date, new_cases_avg_7d)) + geom_line() +  facet_wrap(~state, scales = 'free_y')

model_rm_vars = names(df)[ grep('new_cases_rm_', names(df)) ]

x=data.matrix(df[state != 'USA', c('new_deaths_avg_7d', model_rm_vars), with = FALSE])
#x=data.matrix(df[state != 'USA', c('new_deaths', model_rm_vars), with = FALSE])
index = complete.cases(x)
y = x[index, 1]
x = x[index,-1]

#corrplot(cor(x), method="ellipse")
cvob3=cv.glmnet(x, y, family="gaussian", nfolds = 10, relax = FALSE)
plot(cvob3)

ggplot(data.frame(rms = cvob3$cvm, rms_hi = cvob3$cvup, rms_lo = cvob3$cvlo, lambda = log(cvob3$lambda)) , aes(lambda, rms) ) + geom_line() + geom_point() + 
  geom_ribbon(aes(ymin = rms_lo, ymax = rms_hi), fill = 'blue', alpha = 0.3) +
  geom_vline(xintercept =  c(log(cvob3$lambda.min),  log(cvob3$lambda.1se)), linetype = 'dashed') +
  ggtitle(sprintf('Best RMS %.5f', cvob3$cvm[which(cvob3$lambda == cvob3$lambda.1se)]))

coef_path = data.table(get_all_coefs(cvob3))
coef_path[order(var_name), weight := seq(0, .N-1),  by =.(lambda)]
coef_path[order(var_name,  decreasing = TRUE), adj_coef := cumsum(coef / weight),  by =.(lambda)]
coef_path[, dof:=sum(coef!=0), by =.(lambda)]
coef_path[var_name != '(Intercept)', .( sum(coef),  sum(adj_coef)), by =.(lambda)] #sum of the coefs  -0.013400167

coef_path[var_name != '(Intercept)' & lambda == cvob3$lambda.1se & coef != 0]
coef_path[var_name != '(Intercept)' & dof == 4 & coef != 0]

imp_vars = as.character(unique( coef_path[lambda >= cvob3$lambda.1se & abs(coef) >0, var_name] ))

ggplot(coef_path[var_name != '(Intercept)'], aes(var_name, log(lambda), fill = atan(1e4*coef) )) + geom_tile() +  
  theme(axis.text.x  = element_text(angle=90)) + 
  geom_hline(yintercept = log(c(cvob3$lambda.1se, cvob3$lambda.min)), linetype = 'dashed') + 
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0)

#df[, new_deaths_pred := predict(cvob3, newx=data.matrix(df[,model_rm_vars, with = F]), s= 'lambda.1se')]
#ggplot(df[state %in% my_states], aes(date, new_deaths)) + geom_line() + geom_line(aes(date, new_deaths_pred), color = 'red') + facet_wrap(~state, scales = 'free_y')

df[, new_deaths_avg_7d_pred := predict(cvob3, newx=data.matrix(df[,model_rm_vars, with = F]), s= 'lambda.1se')]
ggplot(df[state %in% my_states], aes(date, new_deaths_avg_7d)) + geom_line() + geom_line(aes(date, new_deaths_avg_7d_pred), color = 'red') + facet_wrap(~state, scales = 'free_y')
ggplot(df[state %in% my_states], aes(new_deaths_avg_7d, new_deaths_avg_7d_pred)) + geom_point() + facet_wrap(~state, scales = 'free')

summary(lm('new_deaths_avg_7d ~ new_deaths_avg_7d_pred', df))
summary(lm('new_deaths_avg_7d ~ new_cases_rm_55', df))

#summary(lm('new_deaths ~ new_deaths_pred', df))
#summary(lm('new_deaths ~ new_cases_rm_50', df))

model.lm = lm('new_deaths_avg_7d ~ new_cases_rm_55', df)
df[, new_deaths_avg_7d_pred := predict(model.lm, df[,model_rm_vars, with = F])]
ggplot(df[state %in% my_states], aes(date, new_deaths_avg_7d)) + geom_line() + geom_line(aes(date, new_deaths_avg_7d_pred), color = 'red') + facet_wrap(~state, scales = 'free_y')
ggplot(df[state %in% my_states], aes(new_deaths_avg_7d, new_deaths_avg_7d_pred)) + geom_point() + facet_wrap(~state, scales = 'free')

#model.lm = lm('new_deaths ~ new_cases_rm_50', df)
#df[, new_deaths_pred := predict(model.lm, df[,model_rm_vars, with = F])]
#ggplot(df[state %in% my_states], aes(date, new_deaths)) + geom_line() + geom_line(aes(date, new_deaths_pred), color = 'red') + facet_wrap(~state, scales = 'free_y')
#ggplot(df[state %in% my_states], aes(new_deaths_pred, new_deaths)) + geom_point() + facet_wrap(~state, scales = 'free')


```

## Cluster States

```{r cluster, echo=FALSE}
cor_mat = cor(dcast(df, date ~ state, value.var = 'new_cases')[order(date)][,-1], use = 'pairwise.complete.obs')

ggplot(melt(cor_mat), aes(Var1, Var2, fill = value)) + geom_tile()

hc = hclust(dist(1-cor_mat))

ggdendrogram( dendro_data(hc),  rotate = TRUE, size = 1)

memb <- cutree(hc, k = 6)

table(memb)

cl = data.table(state= names(memb), cluster = memb)

df[cl, cluster := i.cluster, on =.(state)]

ggplot(df[cluster == 1], aes(date, new_cases)) + geom_line() + geom_smooth(span = 0.3, se = FALSE, color = 'red') + facet_wrap(~state, scales = 'free_y')
ggplot(df[cluster == 2], aes(date, new_cases)) + geom_line() + geom_smooth(span = 0.3, se = FALSE, color = 'red') + facet_wrap(~state, scales = 'free_y')
ggplot(df[cluster == 3], aes(date, new_cases)) + geom_line() + geom_smooth(span = 0.3, se = FALSE, color = 'red') + facet_wrap(~state, scales = 'free_y')
ggplot(df[cluster == 4], aes(date, new_cases)) + geom_line() + geom_smooth(span = 0.3, se = FALSE, color = 'red') + facet_wrap(~state, scales = 'free_y')
ggplot(df[cluster == 5], aes(date, new_cases)) + geom_line() + geom_smooth(span = 0.3, se = FALSE, color = 'red') + facet_wrap(~state, scales = 'free_y')
ggplot(df[cluster == 6], aes(date, new_cases)) + geom_line() + geom_smooth(span = 0.3, se = FALSE, color = 'red') + facet_wrap(~state, scales = 'free_y')

ggplot(df[state %in% c('Alabama', 'North Carolina', 'South Carolina', 'Arkansas', 'Utah', 'Florida')], aes(date, new_cases)) + geom_line() + geom_smooth(span = 0.3, se = FALSE, color = 'red') + facet_wrap(~state, scales = 'free_y')

```

## TS Representation

```{r ts_representation, echo=FALSE}
library(gbm)

df1 = df[state %in% c('North Carolina')][order(date), .(date, x = new_cases)]

#moving average - creates bins  
df1[, x_ma_14 := rollmeanr(x, k = 14, na.pad = TRUE)]
df1[, x_ma_28 := rollmeanr(x, k = 28, na.pad = TRUE)]
df1[, x_ma_56 := rollmeanr(x, k = 56, na.pad = TRUE)]
df1[, t:=seq(nrow(df1)) ]

df1_ex = data.table(expand.grid(t1 = df1$t, t2 = df1$t))[t1<=t2]
df1_ex[df1, x:=i.x, on =.(t1 = t)]
df1_ex[df1, x_ma_14 := i.x_ma_14, on =.(t2 = t)]
df1_ex[df1, x_ma_28 := i.x_ma_28, on =.(t2 = t)]
df1_ex[df1, x_ma_56 := i.x_ma_56, on =.(t2 = t)]
df1_ex[, dt := t2 - t1]

df1_ex[t2 == 15,]

formula.gbm = formula('x ~ x_ma_14 +  x_ma_28  + x_ma_56 + dt')
model.gbm = gbm(formula.gbm, 
                data = df1_ex[!is.na(x), all.vars(formula.gbm), with = FALSE], 
                distribution = 'gaussian',
                n.trees = 1000,
                shrinkage = 0.01,#0.005
                bag.fraction = 0.5,
                interaction.depth = 2,
                n.cores = 4,
                verbose =  TRUE)
summary(model.gbm, n.trees = 1000)
gbm.perf(model.gbm)

df1_ex[, x_pred := predict(model.gbm, n.trees = 1000, newdata = df1_ex)]

ggplot(df1_ex[t2 == max(t2)], aes(t1, x)) + geom_line() + geom_line(aes(t1, x_pred), color = 'red')



```