---
title: "Santa 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(data.table)

working_folder = file.path(Sys.getenv("HOME"), 'source/github/KaggleSandbox/')
source(file.path(working_folder, '/Utils/common.R'))

```

## Load Data
   choice_n    N    np
1:        0 3790 15112
2:        1  846  4064
3:        2  271  1340
4:        3   68   360
5:        4   12    55
6:        5    6    31
7:        6    3    21
8:        7    4    20
```{r load_data}
    
      df_met = fread(file.path(working_folder, 'Santa2019/data/family_data.csv'))
  
      ggplot(df_met, aes(factor(n_people) )) + geom_histogram(stat="count")
      
      df_met = melt(df_met, id.vars = c('family_id', 'n_people'), variable.name = 'choice', value.name = "day")
      df_met[, choice_n := tstrsplit(as.character(choice), "_", fixed=TRUE, keep=2L)]
      df_met[, choice_n := as.numeric(choice_n)]
      
      df_sol = fread(file.path(working_folder, 'Santa2019/data/ex/solution.csv'))
      #df_sol = fread(file.path(working_folder, 'Santa2019/data/ex/solution.73123.csv'))
      
      df_sol[df_met, n_people := i.n_people, on =.(family_id) ]
      df_sol[df_met, choice_n := i.choice_n, on =c('family_id', 'assigned_day' = 'day') ]
      
      df_agg = df_sol[order(assigned_day),.(.N, np = sum(n_people), avg_choice = mean(choice_n)), by =.(assigned_day)]
      
      ggplot(df_agg, aes(assigned_day, np)) + geom_point(aes(color = avg_choice)) + 
        geom_line() + geom_hline(yintercept = c(125, 300), linetype = 'dashed', color = 'red') 
      
      ggplot(df_met[choice == 'choice_0',.(.N, np = sum(n_people)), by =.(day)], aes(day, np)) + geom_point() + 
        geom_line() + geom_hline(yintercept = c(125, 300), linetype = 'dashed', color = 'red') + 
        geom_line(data = df_agg, aes(assigned_day, np), color ='blue') + 
        geom_point(data = df_agg, aes(assigned_day, np), color ='blue')
    
    ggplot(df_sol[,.(.N, np = sum(n_people)), by =.(choice_n)], aes(factor(choice_n), np)) + geom_bar(stat = 'identity')
      
    #df_agg[np > 300 | np < 125, ]
  #df_agg
  
  dim(df_sol)
  table(df_sol$assigned_day)
  df_sol[order(assigned_day),.(.N, np = sum(n_people)), by =.(assigned_day)]
  df_sol[order(choice_n),.(.N, np = sum(n_people)), by =.(choice_n)]
  
  # -------- deep dive
  df_sol[choice_n == 6,]
  df_met[family_id == 4278 ,]

  ggplot(df_met[family_id %in% sample(unique(df_met$family_id), 10), ], aes(day, family_id, group =family_id, color = choice_n)) + geom_point()
```

##Mixed integer linear programming in R
```{r example}
library(dplyr)
library(ROI)
library(ROI.plugin.glpk)
library(ompr)
library(ompr.roi)

result <- MIPModel() %>%
  add_variable(x, type = "integer") %>%
  add_variable(y, type = "continuous", lb = 0) %>%
  set_bounds(x, lb = 0) %>%
  set_objective(x + y, "max") %>%
  add_constraint(x + y <= 11.25) %>%
  solve_model(with_ROI(solver = "glpk")) 
get_solution(result, x)
get_solution(result, y)



```
