---
title: "Parametric Fit  "
output: html_document
---

---
title: "Santander Transaction Model"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list = ls())
knitr::opts_chunk$set(echo = TRUE, fig.width = 8, fig.height = 5, dpi = 240)
options(warn=-1)

library(plyr)

library(data.table)
library(stringi)
library(ggplot2)
library(tabplot)
library(gridExtra)
library(zip)
library(corrplot)
library(forcats)
#library(pdp)
library(e1071)
library(glmnet)
library(lubridate)

library(gbm)
#library(randomForestSRC)
#library(xgboost)
#library(pdp) 
#library(vip) 

#library(rBayesianOptimization)

#library(lightgbm)

#working_folder = 'C:/Dev/Kaggle/'
#working_folder = 'F:/Github/KaggleSandbox/'
working_folder = file.path(Sys.getenv("HOME"), 'source/github/KaggleSandbox/')

source(file.path(working_folder, '/Utils/common.R'))
```

## Load Data

```{r load_data}

  df_train = fread(file.path(working_folder,'santander_transaction/data/train.csv'), check.names=T)#, nrows = 10000)
  df_test  = fread(file.path(working_folder,'santander_transaction/data/test.csv'),  check.names=T)#, nrows = 10000)

  df_train[,is_train:=TRUE  ]
  df_test[, is_train:=FALSE ]
  df_test[, target:=NA ]
  
  df = rbind(df_train, df_test)
  df = df[sample.int(nrow(df), nrow(df)),]
  train_index = df$is_train
  
  gc(reset = TRUE)
  
  ggplot(df, aes(var_0, group = is_train)) + stat_ecdf()
  
  ggplot(df_train[1:10000,], aes(var_81, var_139, color = factor(target) )) + geom_point(alpha = 0.2)
  
  #tableplot(df_train[1:10000,], select = c('target',stri_join('var_', seq(0, 10))), sortCol = 'var_0')
  #tableplot(df_train[1:10000,], select = c('target','var_1'), sortCol = 'var_0')
```

## Logistic regression

```{r logreg_model}
exclude_vars = c('ID_code', 'is_train', obj_var)
all_vars = names(df) %!in_set% c(exclude_vars)

formula.glm = formula(stri_join( obj_var, ' ~ ', stri_join(unique(all_vars), collapse = ' + ')))

model.glm = glm(formula.glm, df[tindex,], family = binomial(link = "logit"))
summary(model.glm)

#could be dec: var_41, var_7, var_98        var_10       var_185
#could be inc:        var_38       var_117        var_60 

pred.glm  = predict(model.glm, newdata = df, type = 'response')
plot_binmodel_roc(actual[tindex], pred.glm[tindex])
plot_binmodel_cdf(actual[tindex], pred.glm[tindex])
plot_binmodel_percentiles(actual[tindex], pred.glm[tindex], 100)
gbm.roc.area(actual[tindex], pred.glm[tindex]) #0.7474184

plots = llply(all_vars[1:30], function(var_name) {
  p = plot_profile(pred.glm[tindex], actual[tindex],df[[var_name]][tindex], error_band = 'binom', bucket_count = 20) +
    ggtitle(var_name) +  theme(title =element_text(size=6), axis.title.y = element_blank()) 
  return( p )
})
marrangeGrob(plots, nrow = 5, ncol = 6, top = NULL)

```

## Logistic Lasso

```{r log_lasso_model}

tindex = df$is_train

obj_var = 'target'
actual = df[[obj_var]]

exclude_vars = c('ID_code', 'is_train', obj_var)
all_vars = names(df) %!in_set% c(exclude_vars)

dt_train = data.matrix(df[tindex,all_vars, with = F])

set.seed(1011)
cvob3=cv.glmnet(dt_train, actual[tindex],family="binomial",type.measure="auc")
plot(cvob3)


fit2=glmnet(dt_train,actual[tindex],family="binomial")
predict(fit2,type="nonzero")
```


## Param Fit

```{r param_model}
tindex = df$is_train

obj_var = 'target'
actual = df[[obj_var]]

exclude_vars = c('ID_code', 'is_train', obj_var)
all_vars = names(df) %!in_set% c(exclude_vars)

#importance_matrix = fread( file.path(working_folder,'santander_transaction/gbm.var_inf.d1.csv'))
#all_vars = importance_matrix$var[1:3]

dt_train = data.matrix(df[tindex,all_vars, with = F])
dt_all = data.matrix(df[,all_vars, with = F])

logistic_function <- function(x, bias, a, b, k){
  return ( a + b/ (1 + exp(k*( x - bias) )) )
}

params2prop <-function(params){
  log_odds <- dt_all %*% params[-1] + params[1]
  return ( 1 / (1 + exp(-log_odds)) )
}

obj_fun <- function(x) {
    xbeta <- dt_train %*% x[-1] + x[1]
    #return( -sum( actual[tindex] * xbeta - log(1 + exp(xbeta)))  )
    return( 1.0-gbm.roc.area(actual[tindex], pred.param[tindex]) )
}

res = optim(coef(model.glm), obj_fun, method = 'L-BFGS-B', control = list(trace = TRUE))
res = optim(coef(model.glm), obj_fun, method = 'Nelder-Mead', control = list(trace = TRUE, maxit =  100))
#nlm(obj_fun, c(0,0))

pred.param = params2prop(res$par)

plot_binmodel_roc(actual[tindex], pred.param[tindex])
plot_binmodel_cdf(actual[tindex], pred.param[tindex])
plot_binmodel_percentiles(actual[tindex], pred.param[tindex], 100)
gbm.roc.area(actual[tindex], pred.param[tindex]) #0.7474184

plots = llply(all_vars[1:2], function(var_name) {
  p = plot_profile(pred.param[tindex], actual[tindex],df[[var_name]][tindex], error_band = 'binom', bucket_count = 20) +
    ggtitle(var_name) +  theme(title =element_text(size=6), axis.title.y = element_blank()) 
  return( p )
})
marrangeGrob(plots, nrow = 2, ncol = 2, top = NULL)

```


## Save Results
glm - 0.860
xgb - 0.899

```{r save_results}

submit = df[,.(ID_code, target = pred.glm)]

submit = submit[df$is_train==FALSE,]

setorder(submit, ID_code)

file = file.path(working_folder, "santander_transaction/solution_glm.csv")
  
fwrite(submit, file = file, row.names = FALSE)

zip(paste(file, '.zip', sep = ''), file)
  
print(file)

#fullVisitorId,PredictedLogRevenue

```